### ISSUE TITLE
Open Data Download funktioniert nicht

### ISSUE THREAD

**Issue by carlobeltrame** [puzzle/decidim-zuerich#10]
* [x] `zip` dependency verlangen https://github.com/decidim/decidim/pull/6464
* [x] Daten aus dem public Ordner auf Deployments serven lassen (lokal gehts schon)
* [ ] Export-Job täglich schedulen (via Cron)

**Comment by TSydekum** [comment]
Funktioniert auch mit neuem Release nicht.
![image](https://user-images.githubusercontent.com/66952143/94903197-bb12a200-0499-11eb-8da1-b65eec31abe7.png)

**Comment by Kagemaru** [comment]
Anscheinend wurde der PR noch nicht ins core gemerged, damit fehlt uns das immer noch.
Soll ich den [erwähnten Patch](https://github.com/decidim/decidim/pull/6464#issuecomment-689723197) umsetzen und ein weiteres Ticket erstellen für das ausbauen nach dem Merge.

**Comment by TSydekum** [comment]
Wir müssen die Export Funktionen dringend testen können. Es scheint ja in den aktiven Decidim Umgebungen zu funktionieren. 
In diesen Umgebungen wird das ZIP Gem durch das Gemfile geladen. Können wir das nicht auch so machen? Selbst die Grossen Installationen scheinen so aufgesetzt zu sein. Gibt das Issues?

"Without this, the exporter would not work in environments where the "zip" gem is not explicitly loaded through the Gemfile, as in most Decidim instances."

**Comment by carlobeltrame** [comment]
@Kagemaru Ich habe bereits vorletzte Woche einen temporären Fix implementiert, bis der PR gemerged und released wird. Das Problem das im PR beschrieben ist haben wir somit aktuell nicht mehr, das zip Gem ist installiert und der Exporter Job läuft problemlos. Aber das generierte Zip wird irgendwo abgelegt (vermutlich der public Ordner oder etwas ähnliches), und diesen Ordner liefern wir bisher nicht aus mit unserem Openshift Setup. Siehe Checkliste die ich im Issue erstellt habe.

**Comment by Kagemaru** [comment]
@TSydekum, @carlobeltrame Gut, merci für die updates. /public sollte eigentlich von NGiNX ausgeliefert werden, ich schau mir das gleich an.

**Comment by Kagemaru** [comment]
Update: Ausgeliefert wird alles, aber nicht sauber generiert.
Manuell konnte ich es zwar generieren, aber der Job um dies automatisch zu tun funktioniert nicht.

**Comment by Kagemaru** [comment]
Nun werden die Files sauber generiert und ausgeliefert.
Es fehlt noch die automatische nächtliche Generierung der Files.
Im Moment werden sie neu generiert **nach** jedem Download.

**Comment by larsUE** [comment]
Bei mir funktioniert das ohne Probleme. Ich close den Thread mal (bitte sonst wiedereröffnen, falls da noch was ansteht :) )
