### ISSUE TITLE
Zentrierte Texte linksbündig machen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#102]
Die Stadt Zürich verwendet grundsätzlich keinen zentrierten Text. Auf folgenden Pages anpassen:

- [x] Metadaten Prozess & Gremium (Bsp: https://mitwirken.integ.stadt-zuerich.ch/processes/feedback rechtes Kästchen)
- [x] Mitwirkungsprozesse & Assemblies Übersicht: "Erstellt am" Text und Datum linksbündig

**Comment by larsUE** [comment]
Das wirkt für mich etwas unruhig (zu viele Fontstyles und -grössen, verschiedene Farben, mal links mal rechts etc.) Bitte falls möglich nicht deployen, Ich muss das mal in Ruhe noch vereinfachen.

**Comment by Kagemaru** [comment]
Umgesetzt in Commit f712ab5
Reverted in Commit fce4b40

**Comment by Kagemaru** [comment]
Was ist hier der Stand? Soll es wieder integriert werden? Oder bleibt es vorerst noch draussen?
