### ISSUE TITLE
Decidim Feedback Module installieren

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#105]
Grundsätzlich sollten aus Spam-Gründen keine Mail-Adressen sichtbar sein. Abwarten, was hier passiert: https://meta.decidim.org/processes/roadmap/f/122/proposals/15779?page=9&per_page=50

**Comment by larsUE** [comment]
Entwicklung gemeinsam mit Luzern. Diskussion läuft [hier](https://github.com/stadtluzern/decidim-ocl/issues/50)

**Comment by larsUE** [comment]
Neu: Probehalber folgendes Modul installieren: https://github.com/mainio/decidim-module-feedback

**Comment by Kagemaru** [comment]
Dieses Modul benötigt Code Änderungen um das Feedback an bestimmte Aktionen zu binden.

Hier bräuchte ich noch eine Liste der Aktionen, nach denen nach Feedback gefragt wird.

**Comment by larsUE** [comment]
Im Moment haben wir 2 Use Cases (ich weiss nicht genau, was du von mir benötigst bzw., ob wir das mit dem Modul lösen könnten):

1.  Eine Umfrage (z.B. als Kontaktformular gestaltet) wird ausgefüllt und abgeschickt. Es wird eine Benachrichtigung an eine bestimmte E-Mail bzw. einen Nutzer verschickt (z.B. Admins oder Prozessorganisator*in).
2. Können gewisse Fehlermeldungen im Frontend damit verbessert werden? Also z.B. wenn ein verpflichtendes Textfeld in einer Umfrage nicht ausgefüllt wird, dass darauf hingewiesen wird? Oder gibt es mit diesem Modul nur Feedback fürs Backend?
