### ISSUE TITLE
Karte: Verlinkungsfehler

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#108]
Wenn ich auf einer Karte einen Pin anwähle und dann auf Vorschlag anzeigen clicke, wird die Seite nicht gefunden.

**Comment by Kagemaru** [comment]
Hast du mir dafür ein Beispiel? Ich konnte es nicht nachstellen. Wenn ich auf [der Produktionsumgebung hier](https://mitwirken.stadt-zuerich.ch/assemblies/spurgruppe/f/5/) auf der Karte klicken will, scrollt es den Button unten aus der Karte.
Wahrscheinlich passiert es danach?

**Comment by Kagemaru** [comment]
Beispiele:
INTEG: https://mitwirken.integ.stadt-zuerich.ch/processes/stadtidee/f/63/
PROD: https://mitwirken.stadt-zuerich.ch/processes/stadtidee/f/21/

Es werden solche Links generiert für den Button:
```
https://mitwirken.integ.stadt-zuerich.ch/processes/stadtidee/f/63/${link}
```
Der Button wird hier generiert:
```
decidim-meetings-0.24.3/app/cells/decidim/meetings/meetings_map/show.erb
```

Anscheinend werden diese Referenzen nachher im Javascript ersetzt. Alle anderen Referenzen werden sauber aufgelöst.
Ich hoffe @carlobeltrame weiss da mehr.

**Comment by carlobeltrame** [comment]
Die Platzhalter werden aus markersData befüllt, via die jquery $.tmpl Funktion. markersData kommt aus dem data-map Attribut des Karten-divs, dort ist address und link beides vorhanden, aber nur address wird ersetzt... Da muss ich erst mal jquery debuggen warum das so ist... Einziger Unterschied ist dass address im body eines spans steht, aber link in einem href-Attribut. Das ganze ist aber schon seit 2017 unverändert so bei decidim...

Haben wir in letzter Zeit jquery geupdatet?

**Comment by Kagemaru** [comment]
Nicht dass ich wüsste. Im Gemfile sind diese Einträge unverändert seit dem ersten Commit:
```
    jquery-rails (4.4.0)
    jquery-tmpl-rails (1.1.0)
```

**Comment by carlobeltrame** [comment]
Es lag doch nicht an JQuery, sondern daran, dass aus irgendeinem Grund das `${link}` in `<a href="${link}">` HTML escaped wurde, aber z.B. `<span>${address}</span>` nicht. Vermutlich werden in ERB die Attribute irgendwo (neuerdings?) escaped. Aber auch mit einigem Debugging habe ich nicht herausgefunden, wo das genau passiert. Als Fix gebe ich das `${link}` jetzt via ein ERB-Tag aus: `<a href="<%= '${link}' %>">`.

Fix ist auf Integration und Produktion ausgerollt.

**Comment by carlobeltrame** [comment]
Fix ist auf der Testumgebung ausgerollt. Gemäss meinen Tests funktionieren jetzt erstmals die Markers-Popup-Buttons und die Vorschlags-Filter gleichzeitig.

**Comment by larsUE** [comment]
Cool, das klappt!
