### ISSUE TITLE
Mitwirkungsprozesse im Backend funktioniert nicht.

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#110]
Seit letzten Änderungen funktioniert der Button "Mitwirkungsprozesse" (Participatory Spaces) im Backend nicht mehr.

**Comment by Kagemaru** [comment]
Das Patch-Upgrade von Rails hat zu Problemen geführt.
Ich musste Decidim auf 0.24.2 heben und execjs auf Version 2.7.0 anpinnen.

Tracking ticket: https://github.com/rails/execjs/issues/100

**Comment by larsUE** [comment]
Hoi @Kagemaru ,
Bei mir funktionieren die Mitwirkungsprozesse auf der INT nach wie vor noch nicht.
