### ISSUE TITLE
Registrierung in einem Meeting führt zu Absturz

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#112]
Gemäss @wernerliechtenhan getestet auf Windows (Chrome und Edge): Bei der Anmeldung zum Event stürzt die Seite ab.

<img width="377" alt="image001" src="https://user-images.githubusercontent.com/60926257/118667528-62a7cf00-b7f4-11eb-8001-5c49303cfa64.png">

**Comment by larsUE** [comment]
Auf dem iPhone konnte ich das Verhalten ebenfalls nachstellen. Da zeigt es mir nur eine leere Seite an. Allenfalls ist das ein fehlerhafter Redirect?

**Comment by Kagemaru** [comment]
PR bei Decidim: https://github.com/decidim/decidim/pull/8194

Bei uns temporär gefixt in Commit 254a15e
