### ISSUE TITLE
Fehlermeldung "unexpected # after "" "

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#113]
Dieser Bug wurde bereits ist bereit bei Platoniq erfasst unter: https://github.com/Platoniq/decidim-module-decidim_awesome/issues/88

Übersetzung aus dem Katalanischen: 
*Describe the bug*
If I add a header or paragraph field, I get the following error / warning below all unexpected '#' after ''. It doesn’t stop me from creating the proposal, but it makes it ugly.

-> Sorry, I rectify, it does affect the creation of proposals: turn the page but do not save the info entered between step 1 and 3

*Reproduce*
1. Add a header or paragraph type field to custom fields
2.  View proposal creation form (e.g. this one)

*Expected Behavior*
That the warning does not appear.

Wir konnten dieses Verhalten nachstellen. Diesen Bug müssen wir beheben, weil es auch Teile de Inhalts löscht, wenn man zum nächsten Schritt in der Proposal-Erstellung wechselt.

![Bildschirmfoto 2021-06-01 um 09 01 16](https://user-images.githubusercontent.com/60926257/120280411-efa05d00-c2b7-11eb-8158-192a1013dff8.png)
_Dieser Screenshot stammt aus Schritt 3  "Abschliessen" vom Proposalerstellungsprozess. Die Inhalte unter dem Header/Paragraph-Setting wurden allesamt gelöscht  und die Fehlermeldung erscheint._

**Comment by Kagemaru** [comment]
Ich habe dies gefixt und einen PR bei Platoniq eröffnet
PR: https://github.com/Platoniq/decidim-module-decidim_awesome/pull/96

Ich deploye es gleich noch.

**Comment by larsUE** [comment]
Bestens! Funktioniert prima.

**Comment by Kagemaru** [comment]
@larsUE Noch so als Information: Wenn man nur einen Header / Paragraf reintut, gibt es immer einen eher kryptischen Fehler. Dann muss man einfach ein/e Textfeld/Textbox einfügen und es passt wieder.
