### ISSUE TITLE
Umlaute werden umgewandelt

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#114]
Umlaute werden in bei der Veröffentlichung de Ideen in Codes umgewandelt. Dieses Verhalten wurde bereits bei Platoniq gemeldet: https://github.com/Platoniq/decidim-module-decidim_awesome/issues/83

Übersetzung aus dem Katalanischen:
*Describe the bug*
Accented letters within a text field or text area do not load well, neither in step 3, nor to modify proposal or edit it.

*To reproduce*
1. Go to https://coincidim.cat/assemblies/impulsem/f/49/proposals/new
2. Fill in the fields and on schedule put, for example, "Matí"
3. In step 3 of the selection of proposals, instead of "Matí" comes "Mat & # xED;".

*Expected Behavior*
Maintain accents and not offend the SCA (Special Characters Association).
![Bildschirmfoto 2021-06-01 um 09 13 09](https://user-images.githubusercontent.com/60926257/120281743-99ccb480-c2b9-11eb-94a4-097c25b77cc1.png)

**Comment by Kagemaru** [comment]
Ich konnte dies lösen und werde gleichzeitig bei uns einen Override deployen, der es fixen sollte, während ich einen Pull Request bei decidim_awesome einreiche.

PR: https://github.com/Platoniq/decidim-module-decidim_awesome/pull/94

**Comment by larsUE** [comment]
Yeah super, konnte es bereits prüfen und works like a charm!

**Comment by Kagemaru** [comment]
Ich kam gestern nicht mehr dazu zu deployen. Hast du mir einen Link zu deinem erfolgreichen Versuch?

**Comment by larsUE** [comment]
Haha ok, komisch. Hier: https://mitwirken.integ.stadt-zuerich.ch/processes/stadtidee/f/45/proposals/49

**Comment by Kagemaru** [comment]
Keine Ahnung warum das funktioniert hat. Aber jetzt ist es deployt.
https://mitwirken.integ.stadt-zuerich.ch/processes/stadtidee/f/45/proposals/53/preview

**Comment by Kagemaru** [comment]
Das PR wurde übrigens bereits gemerged und ich habe unseren hotfix wieder entfernt und ihren Branch wieder eingesetzt.
