### ISSUE TITLE
Adobe Analytics einrichten

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#115]
- technische Einbindung via OIZ
- Beantragung Zugriff via STEZ

**Comment by Kagemaru** [comment]
Was muss man hier genau machen?

**Comment by bsantschi** [comment]
Meiner Meinung nach ist der Ball noch bei Frank Loeliger. @larsUE kannst du nachfragen, wann wir "die Infos und die notwendigen Code-Schnipsel" erhalten?

**Comment by larsUE** [comment]
Hab nachgefragt.

**Comment by larsUE** [comment]
Siehe Mails. Bitte möglichst bald einbinden und direkt mit Ronny Ott / Frank Loeliger schauen, da ich weg bin.

**Comment by Kagemaru** [comment]
Eingerichtet und getestet auf INT.

**Comment by larsUE** [comment]
Gerne auf prod deployen, damit es bereits misst. Ich teste es dann nächste woche

**Comment by larsUE** [comment]
Wurde auch seitens der Stadt getestet und funnktioniert

**Comment by bsantschi** [comment]
Gemäss Ott Ronny kommen die Daten seit Montag auf auf PROD an.
