### ISSUE TITLE
Markierte Check-boxes werden gelöscht.

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#117]
Wenn ich im ersten Schritt Checkboxes markiere, so ist die Auswahl in Schritt 3 gelöscht und es erscheint die Fehlermeldung, dass ich die Auswahl noch nicht getroffen habe.

Dieser Bug wurde bereits bei Platoniq erfasst: https://github.com/Platoniq/decidim-module-decidim_awesome/issues/82

Übersetzung aus dem Katalanischen:
**Describe the bug**
I put a checkbox group field. In step 1 I select some items, but when I get to step 3 (complete your proposal) there are no items selected in the checkbox group. They are also not selected if from the preview I go to "Edit proposal" (before posting the proposal), or when I go to "Edit proposal" (after I have published it).

**To Reproduce**
Go to https://coincidim.cat/assemblies/impulsem/f/49/proposals/new
Fill in the fields and select some items from the checkbox
In step 3 of the selection of proposals, the items selected in the previous step are not selected.
Expected behavior
That the selected items are maintained, both in step 3 of creating proposals and modifying and editing proposals.

**Comment by Kagemaru** [comment]
Dieses Problem befindet sich anscheinend in einer importierten Javascript Library, die den FormBuilder und FormRenderer bereitstellt. Ausserdem geschieht es nur, wenn die Checkboxes als "Required" markiert werden.

Mein Javascript-Fu reicht leider nicht aus um dies innerhalb nützlicher Frist in der ursprünglichen Library zu fixen.
Deshalb habe ich einen Hotfix für Decidim Awesome geschrieben und ihn per Fork bei uns auf INT gepackt und das Decidim Awesome Projekt darüber informiert.

Da dieser Hotfix ziemlich unschön ist und uns momentan zwingt den Fork zu unterhalten, sollten wir uns überlegen, noch einen Frontend-Developer auf dieses Problem loszulassen, falls dies ein kurzer Fix ist.

Links:
[Decidim Awesome Issue](https://github.com/Platoniq/decidim-module-decidim_awesome/issues/82)
[Unser Fork](https://github.com/puzzle/decidim-module-decidim_awesome/blob/custom-fields/app/assets/javascripts/decidim/decidim_awesome/proposals/custom_fields.js.es6)
[Wahrscheinlich das Problem](https://github.com/kevinchappell/formBuilder/blob/902206505760b8af8417f479a4ddcdc641c46b10/src/js/control/select.js#L36)

**Comment by larsUE** [comment]
Was denkst du, wenn wir einen der Form-Builder Hacks übernehmen, wie @carlobeltrame [hier beschrieben](https://github.com/Platoniq/decidim-module-decidim_awesome/issues/82), würde es dann klappen?

https://github.com/kevinchappell/formBuilder/issues/910

**Comment by Kagemaru** [comment]
@larsUE Diese Hacks machen das selbe wie mein Hack, nur eben nicht alles. Der eine Hack setzt nur die defaults anders, der andere Hack ignoriert die "Andere" Checkbox.
