### ISSUE TITLE
Ideen-Seite nicht erreichbar.

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#118]
Auf der Prod tritt derzeit noch ein Fehler auf. Wenn ich als unregistrierter Benutzer das Vorschlagsmodul öffne, erscheint die Fehlermeldung "Auf unseren Servern ist ein Fehler aufgetreten", obwohl das Modul veröffentlicht ist. 

https://mitwirken.stadt-zuerich.ch/processes/TAZ-mobilitaet-stadtraume/f/13/

**Comment by carlobeltrame** [comment]
Das ist ein Bug im anonymous Proposals Modul. Wurde bereits [gefixt](https://github.com/PopulateTools/decidim-module-anonymous_proposals/pull/4), ich aktualisiere unsere Version. (Ich verstehe zwar nicht, wieso wir das Problem zuvor noch nicht hatten)

**Comment by larsUE** [comment]
Super, danke! Vermutung: Weil wir das Anonymous-Modul noch auf der alten Decidim-Version getestet hatten und seither keinen Use-Case mehr hatten, als Nicht-registrierter das Vorschlagsmodul zu benutzen.

**Comment by carlobeltrame** [comment]
Ist erledigt und auf Integration und Produktion ausgerollt. Du solltest wohl noch folgende Keys im Term Customizer übersetzen:
```
de.decidim.anonymous_proposals.new_session
de.decidim.anonymous_proposals.register
de.decidim.anonymous_proposals.shared.anonymous_proposals_announcement.text_html
de.decidim.anonymous_proposals.shared.anonymous_proposals_new_announcement
```
Meine Übersetzungen von unserer Erweiterung findest du hier: https://github.com/PopulateTools/decidim-module-anonymous_proposals/pull/5/files#diff-df718bd2d68738b2415f38df20a65377260003be1edb281d1f47a23896198969
