### ISSUE TITLE
Neuer Tenant auf INT einrichten

### ISSUE THREAD

**Issue by bsantschi** [puzzle/decidim-zuerich#119]
- Tenant auf OIZ-INT einrichten
- Basic-Auth beibehalten
- Name: Quartierplattform
- URL: https://pitc-stzh-decidim-int-quartiere.appuioapp.ch/
- Look & Feel: von "Mitwirken Stadt Zürich" übernehmen
- Mailabsender: Puzzle-Adresse
- Sprachen: Deutsch
- Mein-Konto anbinden: nein
- Admin-Berechtigung: Lars, Anthony, Werner

**Comment by Kagemaru** [comment]
@larsUE Ich habe dich bereits zum Admin gemacht und Anthony eingeladen. Da ich keine E-Mail Adresse von Werner habe, kann ich ihn nicht einladen. Kannst du dies erledigen?
