### ISSUE TITLE
Mobile: Logo und Burger kleben am Rand, Bild zu gross

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#120]
Bild

**Comment by larsUE** [comment]
Minimalversion: Logo verkleinern, Abstand Padding vom Rand für Burger und Logo vergrössern.

![IMG_5021](https://user-images.githubusercontent.com/60926257/122411509-1a133b00-cf85-11eb-949a-982ea4ff3c8f.PNG)

Maximalvariante: Header Stadt übernehmen: 
D.h. Suchfel, Konto und Burgeer unter Header. Umsetzung nach #83 angehen.
![Bildschirmfoto 2021-06-17 um 16 02 43](https://user-images.githubusercontent.com/60926257/122411972-7aa27800-cf85-11eb-8520-3e56ffabe2cb.png)

**Comment by carlobeltrame** [comment]
Habe vorerst mal nur Abstände hinzugefügt, weil mir das am dringendsten schien. Testbar auf Integration.

**Comment by larsUE** [comment]
Abstände sind super, danke. Mir fällt jetzt auf, dass Top-Menü jetzt aber nicht mehr zu einem Burger zusammenfällt, sondern irgendwie komisch angeordnet ist. Wenn das gefixed ist, kannst du deployen (bin weg ab morgen ;) )

**Comment by carlobeltrame** [comment]
Ich verstehe ehrlich gesagt nicht, wie du das meinst. Habs auf Desktop und Mobile getestet, und es sieht alles normal aus für mich..?

https://user-images.githubusercontent.com/7566995/125924517-31059f2b-b414-47a5-8cb1-ec3c65a2add0.mp4

Ich habe aber noch bemerkt dass das Cookie-Warnungs-Banner je nach scrolling in der Luft hängt, das habe ich noch gefixt, und deploye jetzt auf Produktion.

**Comment by larsUE** [comment]
Hmm das muss ein Fehler in meiner desktop mobile-anzeige gewesen sein. Auf dem Handy siehts prima aus. Allerdings klebt der introtext noch am rand. Kannst du das noch anpassen? Danach kann alles deployed werden :) https://user-images.githubusercontent.com/60926257/125929169-95e880f3-fc86-484b-9602-85c49fcd4c04.MOV

**Comment by carlobeltrame** [comment]
Das mit dem Introtext war schon vorher so, und es ist nicht ganz risikofrei das anzupassen weil der sich in praktisch nichts von anderen `<p>` Abschnitten unterscheidet. Ich würde das nicht überstürzt ohne zu testen ändern. Normalerweise ist dieser Text halt zentriert, daher fällt das bei standard Decidim nicht auf.
