### ISSUE TITLE
Instrumententafel funktioniert nicht

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#121]
Wenn ich im Backen auf die Instrumententafel klicke, kommt "Auf unseren Servern ist ein Fehler aufgetreten."

**Comment by larsUE** [comment]
Update: Instrumententafel funktioniert wieder, das Admin-Aktivitätsprotokoll nicht.

**Comment by Kagemaru** [comment]
Ich konnte keines der beiden Probleme rekonstruieren. Aber bei den Scope Types habe ich den gleichen Fehler gefunden und gefixt.

**Comment by larsUE** [comment]
Bestens, bei mir funktioniert jetzt auch alles wieder.
