### ISSUE TITLE
<strong>-Klasse: Kapitalisierung entfernen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#125]
Die Strong-Klasse schreibt Texte in All-Caps, was nicht mit dem Styleguide der Stadt Zürich kompatibel ist. Capitalization entfernen.

Beispiele:

- [x] Partizipationsprozesse: "Erstellt am" und weitere: https://mitwirken.integ.stadt-zuerich.ch/processes
- [x] Statistiken und Metriken: Beschreibungstexte https://mitwirken.integ.stadt-zuerich.ch
- [ ] Folgen/Nicht mehr folgen/Sie folgen bereits dem Prozess: https://mitwirken.integ.stadt-zuerich.ch/processes/feedback
- [ ] Aktivität & Metriken: https://mitwirken.integ.stadt-zuerich.ch/processes/feedback
- [ ] Metadaten Überschriften (Statt Kapitälchen einfach Fett): https://mitwirken.integ.stadt-zuerich.ch/processes/feedback

**Comment by Kagemaru** [comment]
Leider ist dies nicht direkt an <strong> gebunden sondern an mehrere CSS Regeln.
Wir müssen diese einzeln ausschalten oder einen sehr rigorosen Eingriff unternehmen, den ich nicht empfehle:
```css
* { text-transform: unset ! important; }
```
Ich habe die ersten zwei Beispiele jetzt mal umgesetzt.

**Comment by Kagemaru** [comment]
Diese Änderungen sind nun in Decidim Awesome auf INT.
