### ISSUE TITLE
Mitwirkungsprozess: Banner Ankündigung verschwindet nicht bei leerem Text

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#126]
Wenn ich ein Announcement Banner setze bei einem Mitwirkungsprozess, verschwindet das Banner nicht, wenn ich den Text wieder entferne, sondern zeigt lediglich ein leeres Banner an.

**Comment by carlobeltrame** [comment]
Gibts nicht irgendwo eine Checkbox die das definiert?

**Comment by larsUE** [comment]
Nur für das Banner auf der Startseite. Bei den Mitwirkungsprozessen und allen Modulen jedoch nicht.

Hier ein case: https://mitwirken.integ.stadt-zuerich.ch/processes/testlars

**Comment by larsUE** [comment]
Der Fehler besteht auch bei den einzelnen Modul/Komponentenankündigungen, z.B. hier beim Blog: https://mitwirken.integ.stadt-zuerich.ch/processes/testlars/f/10/

**Comment by larsUE** [comment]
Wurde bereits gefixed, bitte übernehmen: https://github.com/decidim/decidim/issues/7603

**Comment by larsUE** [comment]
Am besten gleich den ganzen https://github.com/decidim/decidim/pull/7700 übernehmen, fixed auch eine Reihe weiterer unserer Issues

**Comment by carlobeltrame** [comment]
Auf Integration ausgerollt

**Comment by larsUE** [comment]
Das scheint nicht geklappt zu haben. Das Banner ist immer noch da, auch wenn ich den Text entferne.
https://mitwirken.integ.stadt-zuerich.ch/processes/privat/f/71/

**Comment by carlobeltrame** [comment]
Das ist ein Bug in decidim awesome. Es tritt nur auf wenn man die Bilder in den Texteditoren aktiviert hat.

Vormals war der Bug auch in Decidim vorhanden, und wurde in https://github.com/decidim/decidim/pull/7224 gefixt. Da decidim awesome den Texteditor komplett ersetzt, muss derselbe Bugfix auch dort nachgeholt werden. Ich eröffne dazu einen Pull Request bei decidim awesome.

Ich kann diesen Fix aber leider nicht bei uns vorholen, weil das eine Änderung an den Assets des Admin-Bereichs benötigt, was nur mit einem Modul möglich ist (wie wir in stadtluzern/decidim-ocl#33 herausgefunden haben). Fürs Go-Live kann ich anbieten, von Hand in die Datenbank zu gehen und die "faux-leeren" Announcements von Hand wirklich zu leeren, wenn du mir sagst wo diese überall auftreten.

**Comment by larsUE** [comment]
Wir haben es derzeit bei der Stadtidee in folgenden Komponenten:

- [ ] Veranstaltungsmodul: https://mitwirken.stadt-zuerich.ch/processes/stadtidee/f/19/
- [ ] Seitenkomponente "Teilnnahmebedingungen": https://mitwirken.stadt-zuerich.ch/processes/stadtidee/f/14/

Hier bitte löschen. Ansonsten sollte das ja bald gefixed werden, wenn der PR akzeptiert wird, oder? Kann da noch ein Mail schreiben, vielleicht haben wir es bis dann ja bereits :) Auf alle Fälle am Abend bitte alles noch auf die Prod deployen.

**Comment by carlobeltrame** [comment]
Bei den Teilnahmebedingungen steht aber noch etwas drin, soll ich das wirklich löschen?

**Comment by larsUE** [comment]
Komisch, bei mir steht aber nix drin?
<img width="987" alt="Bildschirmfoto 2021-07-09 um 14 05 44" src="https://user-images.githubusercontent.com/60926257/125075338-c2b54600-e0be-11eb-8904-e9a13fcb6ee1.png">

**Comment by carlobeltrame** [comment]
Sorry, falsch geschaut. Ist erledigt.

**Comment by larsUE** [comment]
@carlobeltrame Der Decidim Awesome PR ist schon genehmigt worden :) Wenn du noch Zeit hast: Kannst du ihn noch übernehmen und dann gleich alles auf die Prod deployen?

**Comment by carlobeltrame** [comment]
Habs gerade auf Integration aufgeschaltet, klicke dort noch durch und schalts wenn alles gut läuft gleich noch auf Produktion auf.

**Comment by carlobeltrame** [comment]
Uuund wir sind live auf Produktion. Melde dich wenn irgendwas nicht funktionieren sollte wie gewünscht.

**Comment by larsUE** [comment]
Juhuiii! Scheint alle perfekt zu laufen!
