### ISSUE TITLE
Veranstaltungen/Meeting werden nicht nach Datum sortiert

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#127]
Merkwürdig, das sollte eigentlich bereits mit 0.24 geflickt worden sein: https://github.com/decidim/decidim/pull/6975

**Comment by larsUE** [comment]
Allenfalls hier gefixed: https://github.com/decidim/decidim/pull/7700

**Comment by carlobeltrame** [comment]
Auf Integration ausgerollt

**Comment by larsUE** [comment]
Das scheint nicht geklappt zu haben. Das Banner ist immer noch da, auch wenn ich den Text entferne.
https://mitwirken.integ.stadt-zuerich.ch/processes/privat/f/71/

**Comment by carlobeltrame** [comment]
Die Veranstaltungen werden nach Startdatum sortiert, aber absteigend, also die am weitesten in der Zukunft liegenden zuerst. Das ist anscheinend bewusst aber mit mässig guter Begründung so in decidim implementiert worden, vgl. die Screenshots inhttps://github.com/decidim/decidim/pull/7685

Im Admin-Backend mag das ja ein Stück weit Sinn machen, aber im Frontend wo vergangene Meetings sowieso ausgeblendet werden finde ich das überhaupt nicht sinnvoll. Habe das daher mal gepatcht und auf Integration ausgerollt. Wir könnten uns dann überlegen, da bei decidim nochmals darüber zu diskutieren.

**Comment by larsUE** [comment]
Hmm komisch! Danke für den Fix, habs bereits getestet, alles wunderbar
