### ISSUE TITLE
Karte: Pinfarbe anpassen auf "Hervorhebung, Alternative"

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#128]
Die Pins der Karte sind ziemlich dunkel. Anpassen auf die Farbe Hervorhebung, alternative, dann haben sie jeweils die gleich Farbe wie die Banner Images.

**Comment by carlobeltrame** [comment]
Auf Integration ausgerollt

**Comment by larsUE** [comment]
Farbe passt, funktioniert bei meeting und einzelnen Vorschlägen. Hingegen werde auf der übersichtskarte (z.b. bei den vorschlägen) zur Zeit gar keine pins dargestellt.
