### ISSUE TITLE
HTML Text und Parser Error

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#129]
Bei der Ideeneingabe steht im Textfeld noch HTML-Text. Zusätzlich kommt zuunterst eine Fehlermeldung (siehe Bilder). Zu sehen hier: https://mitwirken.stadt-zuerich.ch/processes/stadtidee/f/15/proposals/new

<img width="502" alt="Bildschirmfoto 2021-07-05 um 21 49 58" src="https://user-images.githubusercontent.com/60926257/124513369-f3edf780-ddda-11eb-9fa3-ee658228729c.png">
<img width="615" alt="Bildschirmfoto 2021-07-05 um 21 50 20" src="https://user-images.githubusercontent.com/60926257/124513392-01a37d00-dddb-11eb-9c63-c32fb84f176e.png">

**Comment by carlobeltrame** [comment]
@larsUE Ich kann das lokal auf die Schnelle gerade noch nicht reproduzieren, hast du mir einen Link zu einer Vorschlags-Komponente wo das auftritt? Dann kann ich die Konfiguration kopieren

**Comment by larsUE** [comment]
Yes, schau mal hier: https://mitwirken.stadt-zuerich.ch/processes/stadtidee/f/15/

-> Falls der Link nicht funktioniert kommst du übers Backend -> Stadtidee-Prozess und dann in der Komponentenübersicht auf das Vorschlagsmodul, welches nicht veröffentlicht werden soll. :) Dann einen neuen Vorschlag erstellen.

**Comment by larsUE** [comment]
Scheinbar ist dieses Problem ein Einzelfall und betrifft nur dieses spezifische Modul. Im eigentlichen Modul, kommt der Fehler nicht: https://mitwirken.stadt-zuerich.ch/processes/stadtidee/f/21/proposals/new (bitte da nichts eingeben).
Musst also hierfür keine Zeit aufwenden.

**Comment by larsUE** [comment]
@carlobeltrame: In dem Fall hing das auch mit https://github.com/Platoniq/decidim-module-decidim_awesome/issues/114 zusammen. Der dargestellte Text war  ja genau <p><br></p>.

**Comment by carlobeltrame** [comment]
Stimmt, gut möglich
