### ISSUE TITLE
Rollen im Decidim Backend

### ISSUE THREAD

**Issue by carlobeltrame** [puzzle/decidim-zuerich#13]
* Prozess Admin, also ein für einen einzelnen Prozess designierter Admin kann keine Private Users verwalten
* Kann man die Rollen "Administrator" Collaborator" "Moderator" und "Valuator" zentral definieren?

**Comment by Kagemaru** [comment]
- Prozess Admin, also ein für einen einzelnen Prozess designierter Admin kann keine Private Users verwalten
  - Theoretisch kann man die permissions.rb überschreiben.
- Kann man die Rollen "Administrator" Collaborator" "Moderator" und "Valuator" zentral definieren?
  - Nur im permissions.rb

**Comment by TSydekum** [comment]
Ist dies nur pro Server oder auch pro Tenant anpassbar?

**Comment by Kagemaru** [comment]
Wenn wir es sowieso überschreiben, können wir auch Tenantspezifische Berechtigungen vergeben.
Bedeutet allerdings eine Code Änderung für jeden Tenant, den man hinzufügen möchte.
