### ISSUE TITLE
Leere Karte wird bei nur online-meetings angezeigt

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#131]
Wenn ich nur Online-meetings erstelle, wir die Karte dennoch angezeigt, einfach leer. Bitte dann gar keine Karte anzeigen

**Comment by larsUE** [comment]
![Bildschirmfoto 2021-07-06 um 08 36 09](https://user-images.githubusercontent.com/60926257/124553601-38a67c80-de35-11eb-8520-07f38a94f5b8.png)

**Comment by larsUE** [comment]
Ebenfalls hier gefixed: https://github.com/decidim/decidim/pull/7700

**Comment by carlobeltrame** [comment]
Auf Integration ausgerollt

**Comment by larsUE** [comment]
Funktioniert, jetzt wir einfach eine Karte ohne Pins angezeigt. Kann Deployed werden.
