### ISSUE TITLE
Problem mit Quartierkarte und Swisstopo-Karte

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#134]
Bitte den geplanten Bugfix für Dialog Luzern https://github.com/stadtluzern/decidim-ocl/issues/136 auch für die Quartierplattform Zürich umsetzen. Wir benötigen das "Navigation Maps" Plugin auf der Startseite, um auf einer Quartierkartenübersicht als Bild ein Quartier per Click auswählen zu können und darauf basierend den richtigen Organisationsfilter zu initiieren. Unabhängig davon sollen auf der Startseite auch die nächsten Veranstaltungen mit der Swisstopo-Karte visualisiert dargestellt werden. Idealerweise die Bugfixing-Kosten teilen, da dasselbe.

**Comment by larsUE** [comment]
Einfach als Hinweis, falls das irgendwas bringt: Auf der Integ läuft die Veranstaltungsübersicht gemeinsam mit der "Decidim Awesome Map" ohne Probleme.

**Comment by innosmith** [comment]
Funktioniert danke
