### ISSUE TITLE
Mobile: Call to Action Button Prozess verschwindet auf Mobile

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#135]
![Jul-12-2021 15-40-42](https://user-images.githubusercontent.com/60926257/125297774-d6171a00-e327-11eb-92e1-ceef2a4193b5.gif)
Vermutung: Es wird im Feld unter den bisherigen Button geschoben und ist deshalb nicht mehr sichtbar.

**Comment by carlobeltrame** [comment]
Der Button rutscht nirgends drunter, der wird von decidim ganz bewusst versteckt auf kleinen Bildschirmgrössen. Ich habe diese Regel jetzt mal ausgehebelt. Testbar auf Integration.

**Comment by larsUE** [comment]
super, danke!
