### ISSUE TITLE
Adobe Analytics einrichten

### ISSUE THREAD

**Issue by bsantschi** [puzzle/decidim-zuerich#136]

**Comment by innosmith** [comment]
@bsantschi ist Adobe Analytics für meinquartier.zuerich bereits im Einsatz und haben wir die Zugangsdaten?

**Comment by bsantschi** [comment]
Hoi @innosmith , nein das haben wir noch nicht umgesetzt, entschuldige. Wir bräuchten dazu noch einen "Mandant" und eine "Script Source". Bei Mitwirken hat das damals Lars organisiert (glaub Ronny Ott oder Frank Loeliger konnten ihm weiterhelfen). Soll ich mit ihnen schauen oder möchtest du?

**Comment by innosmith** [comment]
Hoi @bsantschi, danke für die Info. Dann schaue ich es mit Lars an und komme bei Bedarf gerne auf dein Angebot zurück.

**Comment by larsUE** [comment]
Ich glaube,  Mandant und Script Source wären gleich wie bei der Mitwirken Plattform?
@innosmith: Den Zugriff kannst du dann über Werner bzw. Ronny Ott organiseren.

**Comment by innosmith** [comment]
@larsUE : Danke für die Info. Kenne Adobe Analytics noch nicht. Ich schaue mit Werner bzw. Ronny Ott.

**Comment by wernerliechtenhan** [comment]
Ich hatte mit Ronny Ott bereits Kontakt deswegen und frage ihn an.

**Comment by innosmith** [comment]
Nur auf PROD umsetzen, analog Mitwirkungsplattform
