### ISSUE TITLE
Bilder werden auf den Kopf gedreht.

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#138]
Einige Bilder werden bei erstmaligem Hochladen auf den Kopf gedreht. Wenn ich das Bild erneut hochlade, kommt es richtig. Zu sehen auf der Stadtidee:

– Zuerst auf dem Kopf, dann erneut hochgeladen (nun richtig): https://mitwirken.stadt-zuerich.ch/processes/stadtidee/f/21/proposals/77
– Immer noch auf dem Kopf: https://mitwirken.stadt-zuerich.ch/processes/stadtidee/f/21/proposals/78?order=random&per_page=50

**Comment by carlobeltrame** [comment]
Wow, kannst du mir ein Original-Bild geben, bei dem das passiert? Könnte allenfalls an den EXIF-Daten liegen die im Bild eingebettet sind und angeben wie das Bild orientiert sein muss. Aber sehr seltsam dass es beim erneuten Hochladen dann besser funktioniert...

**Comment by bsantschi** [comment]
Verdacht: iOS Geräte halten sich nicht immer an den EXIF-Standard und erscheinen daher oft auf dem Kopf.

**Comment by larsUE** [comment]
Kann gut sein, meins hab eich mit dem iPhone gemacht. Bin mir nicht mehr sicher, vielleicht habe ich es dannach auf dem Kopf gespeichert und ernneut hochgeladen und es hat es dann "falsch-richtig" gedreht. @carlobeltrame ich schick dir das Bild per Mail, hier wirds ev. komprimiert...

**Comment by larsUE** [comment]
Vermutung: Der Fehler tritt auf weil unterschiedliche Hochladen-Funktionen verwendet werden (Vorschlag erstellen vs. Vorschlag bearbeiten).
