### ISSUE TITLE
Proposal-Marker Bug

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#139]
Die Markers auf der Übersichtkarte zur den Proposals erscheinen nicht mehr. Zusätzlich wird bei nur einer Idee eine sehr grosse Zoomstufe gesetzt. Bei Einzelproposals werden sie zwar angezeigt, aber wenn ich auf den Marker klicke, dann erscheint nur der Titel des Vorschlags. Eigentlich sollte da eine Kurzübersicht des gesamten Vorschlags kommen.

Beispiele: 
– INTEG: https://mitwirken.integ.stadt-zuerich.ch/processes/stadtidee/f/63/
–PROD: https://mitwirken.stadt-zuerich.ch/processes/stadtidee/f/21/

**Comment by Kagemaru** [comment]
Anscheinend ist dies ein Problem im leaflet-tilelayer-swiss. Dies muss ein JSler mal debuggen.

@carlobeltrame Es gibt einen Javascript Fehler im leaflet-tilelayer-swiss.js. Anscheinend wird es mit einem null object aufgerufen, wo es {lat: x, long: y} erwartet.
Ich habe es upgedated v2.1.0 => v2.2.1 aber der Fehler besteht weiterhin.

**Comment by carlobeltrame** [comment]
Ist auf Integration gefixt. Grund war dass Decidim nur Proposals rausfiltert die `null` in den Koordinaten haben. Bei unseren Proposals steht aber `NaN` in die Koordinaten, daher versucht es auch Markers für Proposals anzuzeigen die keine gültigen Koordinaten haben. Lösung war, diese Proposals ebenfalls rauszufiltern.
