### ISSUE TITLE
Logo: SVG Upload ermöglichen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#140]
Trotz Anpassungen im System-Backend kann ich keine SVG-Logos hochladen. Aus Skalierungs-/Schärfegründen wäre das aber sehr cool.

**Comment by carlobeltrame** [comment]
Ich verstehe nicht ganz wieso das auf Seite Decidim so implementiert ist, aber es ist tatsächlich so, dass für Logo und weitere Bilder nur PNG und JPEG erlaubt sind: https://github.com/decidim/decidim/blob/develop/decidim-core/app/uploaders/decidim/record_image_uploader.rb
Wir können das aber bei uns schön anpassen, indem wir im [`OrganizationLogoUploader`](https://github.com/decidim/decidim/blob/develop/decidim-core/app/uploaders/decidim/organization_logo_uploader.rb) `content_type_allowlist` und `extension_allowlist` überschreiben.

**Comment by larsUE** [comment]
Super, merci! Dann gerne aktivieren und ich schaue, dass ich vertrauenswürdig bleibe ;)
