### ISSUE TITLE
Sonderzeichen in Custom Fields

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#142]
In den Custom Fields Texten wird bei Veröffentlichung nach wie vor komischer Text dargestellt, dieses Mal ist es "&amp;amp;"
Beispiel hier: https://mitwirken.stadt-zuerich.ch/processes/stadtidee/f/20/posts/16

**Comment by Kagemaru** [comment]
Ich konnte dies leider nicht nachstellen. Hast du mir sonst noch ein Beispiel? Am besten auf der Integration.

**Comment by larsUE** [comment]
Yes, schau mal hier: https://mitwirken.integ.stadt-zuerich.ch/processes/stadtidee/f/63/proposals/112

Ist einfach eine fehlerhafte Konversion des "&" Zeichens

**Comment by Kagemaru** [comment]
Anscheinend ist das relevante Problem irgendwo hier drin:
https://github.com/Platoniq/decidim-module-decidim_awesome/blob/custom-fields/app/assets/javascripts/decidim/decidim_awesome/proposals/custom_fields.js.es6

Leider geht mir die Zeit aus, die ich diese Woche dafür habe.
Eventuell kann @carlobeltrame hier helfen, falls es dringend ist.

**Comment by larsUE** [comment]
Sollte via Decidim Awesome geflickt worden sein.
