### ISSUE TITLE
WAF einrichten

### ISSUE THREAD

**Issue by bsantschi** [puzzle/decidim-zuerich#146]
- Für Tenant Mitwirken einrichten
- falls einfach/gratis, auch für Quartierplattform einrichten

**Comment by larsUE** [comment]
@Kagemaru : Was ist hier der Stand? Ist die WAF erst auf der INT oder wurde sie bereits mal auf die PROD geladen? Und wie könnte ich sie testen?

**Comment by larsUE** [comment]
Das ist grundsätzlich OK, ich wollte mehr wegen dem noch anstehenden Aufwand nachfragen, weil wir das ja eigentlich letztes Jahr bestellt hatten. Gibts da noch viel zu tun?

**Comment by bsantschi** [comment]
Den Aufwand kann ich gerade nicht abschätzen, er wird euer Budget jedoch nicht belasten, da die restlichen Arbeiten im Betriebs- und Wartungsvertrag inklusive sind.
