### ISSUE TITLE
Timeout bei Kommentarantworten

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#148]
Ich hab noch ein bisschen getestet, wieso das mit den Kommentarantworten auf der Integration nicht geht. Ich habe nun folgendes Verhalten festgestellt:
1. Ich klicke auf "Antworten"
2. Dann geschieht lange nix (min. 1 Min)
3. Dann habe ich im Log folgende Fehlermeldung:
<img width="1555" alt="Bildschirmfoto 2021-09-14 um 09 32 43" src="https://user-images.githubusercontent.com/60926257/133214853-d916811e-716b-4781-9954-b03c625ae436.png">
4. Danach kann ich auf Kommentare antworten.

**Comment by larsUE** [comment]
Ich habe nun mal das Favicon ersetzt und komme auf folgende Fehlermeldung:

<img width="1491" alt="Bildschirmfoto 2021-09-14 um 09 40 17" src="https://user-images.githubusercontent.com/60926257/133216065-61277fa1-251c-41a9-88bc-bf5d7cb26105.png">

Hängt das ebenfalls mit dem HTTP-Auth zusammen?

**Comment by larsUE** [comment]
Dasselbe Problem tritt übrigens auch auf, wenn ich das Burger-Icon (Mobile Menü) klicke.

**Comment by carlobeltrame** [comment]
Ja, sieht ganz danach aus als wäre das ein Problem mit Basic Authentication. Diese Fehler in der Konsole bzw. ein teils aufpoppender Dialog der zu erneuter Basic Authentication auffordert gibts auch schon länger auf der Testumgebung, und die treten auf der Produktionsumgebung nicht auf. Das Favicon funktioniert auf Produktion ebenfalls.
Es wird wohl irgendwie damit zusammenhängen dass der Browser die Credentials nur an dieselbe Domain mitsendet für die sie eingegeben wurden, und scheinbar verwendet Decidim Zürich intern mehrere Domains (mitwirken.integ.stadt-zuerich.ch, www.integ.stadt-zuerich.ch).

@larsUE Soll ich basierend auf diesen Annahmen also noch heute deployen?

**Comment by larsUE** [comment]
Yes, gerne! Und flicken tun wir das, wenn wir etwas mehr Zeit haben

**Comment by carlobeltrame** [comment]
Das Timeout passiert nur beim Adobe Analytics Script auf www.integ.stadt-zuerich.ch, also bei der Integrations-Version dieses Skripts. Dieser Host ist von ausserhalb des städtischen Netzwerks nicht verfügbar. Daher Adobe Analytics auf Integration deaktivieren (Env-Variable `ANALYTICS_SCRIPT_SOURCE`)
