### ISSUE TITLE
Portal Partizipationsprozesse übernehmen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#152]
Die Übersicht aller laufender Beiteiligungsprozesse (https://www.stadt-zuerich.ch/prd/de/index/stadtentwicklung/mitwirkung.html) soll auf unser Portal kommen. Darin sind auch Prozesse, die nur verlinkt werden und nicht über mitwirken laufen. Eine Idee wäre, dass man Partizipationsprozesse erstellen kann, die dann gleich auf eine andere URL weiterleiten.

**Comment by carlobeltrame** [comment]
Ich habe mal eine Version umgesetzt und auf Integration aufgeschaltet. Es verhält sich jetzt so: Wenn ein Prozess im Feld "Ankündigung" einen Text mit Link eingetragen hat, dann werden die Nutzenden automatisch zu diesem Link weitergeleitet. Ich habe einen Testprozess "Test externer Prozess" erfasst, an dem du sehen kannst wie das funktioniert.
Hinweis: Der Redirect ist nur auf der "Startseite" des Prozesses aktiv, also wenn ihr Komponenten im Prozess einrichtet und direkt dorthin verlinkt wird man nicht redirectet.

Bitte mal testen und rückmelden, dann können wir gegebenenfalls iterativ verbessern.

@innosmith dasselbe gilt jetzt auch bei der Quartierplattform. Auch bei dir bitte melden falls wir euch hier auf die Füsse treten und ihr unbedingt Links in der Ankündigung haben wollt, ohne dass man gleich weitergeleitet wird.

**Comment by larsUE** [comment]
@carlobeltrame Im Grunde cool & funktioniert prima. Allerdings haben wir genau in dieser Ankündigung immer wieder Links (z.B. Stimme jetzt ab!) und da ist eine automatische Weiterleitung suboptimal. Ginge ein anderes Feld bzw. ein eigenes?

@innosmith: zu Info, dies betrifft nur Mitwirkungsprozesse :)

**Comment by carlobeltrame** [comment]
Ein komplett neues Feld kann ich leider nicht einfach so hinzufügen, das geht nur bei Komponenten so einfach. Bei Prozessen ist das im Bereich wo wir bisher immer mit einem Modul gewunken haben.
Welches Feld wäre denn besser geeignet für euch? Wichtig für die aktuelle Lösung ist, dass das Feld auf der Prozess-Seite angezeigt wird. Wir könnten auch eine Konvention schaffen, z.B. nur wenn die Ankündigung oder ein anderes Feld mit drei Bindestrichen --- beginnt und aufhört wird man weitergeleitet:
> --- Sie werden [weitergeleitet](puzzle.ch)... ---

**Comment by larsUE** [comment]
Die vorgeschlagene Konvention finde ich eine vernünftige Lösung. Dann können wir es gerne in der Ankündigung belassen. Weisst du, ob die Formatierungen auch funktionieren (Kann ich die Nachricht z.B. als H3 in die Ankündigung platzieren?)

**Comment by larsUE** [comment]
Ich habe mal mit decidim-awesome versucht, alle Prozess-Element zu verbergen, dass nur noch die Notifizierung angezeigt wird. Das macht es noch ein bisschen klarer. Allerdings kann ich die Klasse` .process-header__inner ` nicht überschreiben, bzw. greift da Decidim Awesome nicht (vielleicht wegen den Scoped styles?!) Kannst du dir das kurz anschauen?

**Comment by carlobeltrame** [comment]
Auf `.process-header__inner` sowie auf vielen weiteren Elementen dieser Seite haben wir custom CSS drauf fürs CI/CD der Stadt Zürich. Könnte daran liegen.

**Comment by carlobeltrame** [comment]
Ich habs so hingebracht dass du im Announcement selber auch Formatierungen verwenden kannst. Ist auf Integration testbar.

**Comment by carlobeltrame** [comment]
> Ich habe mal mit decidim-awesome versucht, alle Prozess-Element zu verbergen, dass nur noch die Notifizierung angezeigt wird. Das macht es noch ein bisschen klarer. Allerdings kann ich die Klasse`.process-header__inner` nicht überschreiben, bzw. greift da Decidim Awesome nicht (vielleicht wegen den Scoped styles?!) Kannst du dir das kurz anschauen?

Wäre es nicht sowieso einfacher, den ganzen `.process-header` zu verstecken?

**Comment by larsUE** [comment]
doch, aber der lässt das auch nicht zu...

**Comment by larsUE** [comment]
Ansonsten funktioniert die Konvention tipptopp, danke! Kann dann gerne auf Prod.

**Comment by carlobeltrame** [comment]
Habe das Problem gefunden, in CSS kannst du Kommentare nicht mit `//` schreiben, du musst `/* mein Kommentartext */` schreiben, mit `/*` und `*/`. Wies aussieht hatten deine Kommentare die Auswirkung dass die erste CSS-Regel nach dem Kommentar nicht greift. Ich habe deine CSS Styles jetzt angepasst und aufs Minimum vereinfacht.

Vor einem Deployment auf Produktion brauche ich noch grünes Licht von @innosmith zu diesem Feature (inkl. Konvention) und zu #171.

**Comment by larsUE** [comment]
@innosmith Kannst du hier bitte noch kurz grünes Licht geben? :-)

**Comment by innosmith** [comment]
Passt für mich, insb. auch dank der Metatags, sodass das Textfeld auch normal mit URL's verwendet werden kann.

**Comment by carlobeltrame** [comment]
Ist auf Produktion aufgeschaltet. Ich konnte sogar nur dieses Feature deployen ohne die noch nicht bestätigten Änderungen auf der Quartierplattform.
