### ISSUE TITLE
Kompakte Veranstaltungsübersicht

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#166]
Analog Dialog Luzern https://github.com/stadtluzern/decidim-ocl/issues/142 umsetzen. 

Multitenant-Umgebung berücksichtigen, resp. in Absprache mit dem städtischen Tenant umsetzen.

**Comment by carlobeltrame** [comment]
Für beide Tenants gemeinsam übernehmen (und optional noch leicht anpassen) wäre sehr einfach, ca. 1 Stunde.
Um das Tenant-spezifisch umzusetzen müssen wir die [Builders](https://github.com/trailblazer/cells#builder) verwenden, um je nach Verfügbarkeit eine andere tenant-spezifische Cell-Klasse zu rendern. Schätzung: ca. 1 Tag

**Comment by innosmith** [comment]
@larsUE : was meinst du dazu? Tenant spez. oder für beide Tenants gleich umsetzen? Um den Aufwand klein zu halten, könnten wir gemeinsam starten und bei Bedarf später ausdifferenzieren.

**Comment by carlobeltrame** [comment]
Ich habe das mal auf die einfache Art umgesetzt, da Lars sich glaube ich vormals positiv zu dieser Änderung geäussert hat. Bevor wir damit auf Produktion gehen hätte ich aber gerne noch die explizite Zusage von ihm.

@innosmith auch hier wieder ist das Default-Bild relevant, und auch hier habe ich zu Demo-Zwecken einfach mal das von Luzern wiederverwendet. Und auch hier habe ich die Besitzer-Logik von Luzern übernommen (siehe https://github.com/puzzle/decidim-zuerich/issues/174#issuecomment-974171144). Bitte melden falls das noch geändert werden soll.

**Comment by innosmith** [comment]
@carlobeltrame: funktioniert, danke. Default-Bild folgt. Anzeigelogik analog Dialog Luzern passt.
