### ISSUE TITLE
Fehlende Übersetzung Backend

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#169]
Analog Dialog Luzern https://github.com/stadtluzern/decidim-ocl/issues/135 auch für die Quartierplattform umsetzen. Auf dem städtischen Tenant funktioniert dies bereits, weshalb dort und hier nicht?

**Comment by carlobeltrame** [comment]
Was meinst du mit "Auf dem städtischen Tenant funktioniert dies bereits"?
Entweder Bug finden und wenn möglich fixen: 0.5 - 1 PT
Oder Fix von Luzern übernehmen, ist dann aber der gleiche Text für Mitwirken Zürich und Quartierplattform: 1 - 2 Stunden

**Comment by larsUE** [comment]
Es gibt auf der städtischen Plattform ein Term-Customizer Set zu den URL Aliases. @innosmith kannst du gerne übernehmen. Ich möchte dann gegen Ende Jahr mal alle "fixen" Textanpassungen ins Sprachset übernehmen, um den Term Customizer etwas zu entschlanken.

**Comment by innosmith** [comment]
@larsUE . Danke, jetzt hat es geklappt. Ich schaue jeweils schon kurz, ob schon was auf dem städtischen Tenant übersetzt ist, was sich wiederverwenden lässt. Unbedingt, lass uns die Term Customizer Sets so gut wie möglich parallel verwenden. Unterschiede wird es geben, z.B. du/sie.
