### ISSUE TITLE
Änderungsvorschläge funktionieren nicht

### ISSUE THREAD

**Issue by TSydekum** [puzzle/decidim-zuerich#17]
Wird zu einem Vorschlag ein Änderungsvorschlag gemacht wird dieser als "In Überprüfung" angezeigt. Klickt man auf den Vorschlag findet Decidim die Seite nicht. Es sollte ein neues Proposal angelegt worden sein, zumindest deutet die Nummer darauf hin. Beispiel Vorschlag: https://pitc-decidim-zuerich-int.ocp.puzzle.ch/processes/test/f/1/proposals/8
Es gibt so auch keine Möglichkeit den Vorschlag zu akzeptieren.  
Übersicht: https://pitc-decidim-zuerich-int.ocp.puzzle.ch/processes/test/f/1/

Für die Demo grad ein wenig ungünstig.. schiebe es daher in der Prio nach oben..

**Comment by carlobeltrame** [comment]
@Kagemaru Könnte das das gleiche Problem sein wie bei https://github.com/puzzle/quartieridee/issues/49 ?

**Comment by carlobeltrame** [comment]
Ich kann den Vorschlag und die zwei Amendments ohne Probleme abrufen, du inzwischen auch? Könnte es sein dass dieses Problem nur kurz nach dem Erstellen eines Amendments auftritt? Ich untersuche das mal...

**Comment by carlobeltrame** [comment]
Ah! Der Fehler tritt auf wenn man eingeloggt ist. Dann mach ich mich mal dran das zu fixen.

**Comment by carlobeltrame** [comment]
Ist behoben, war tatsächlich dasselbe Problem wie bei der Quartieridee.

**Comment by TSydekum** [comment]
Problem tritt nun einen Schritt weiter auf. Hat man einen Änderungsvorschlag akzeptiert, so lässt sich nun der akzeptierte Vorschlag nicht öffnen.
https://pitc-decidim-zuerich-int.ocp.puzzle.ch/processes/test/f/1/
![image](https://user-images.githubusercontent.com/66952143/93464872-38f77a80-f8ea-11ea-8dc9-0abd7f9fe073.png)

https://pitc-decidim-zuerich-int.ocp.puzzle.ch/processes/test/f/1/proposals/9

**Comment by TSydekum** [comment]
Beim Akzeptireren des Änderungsvorschlags kommt schon ein Fehler:
![image](https://user-images.githubusercontent.com/66952143/93465270-d6eb4500-f8ea-11ea-9169-46c7a759c917.png)
 wird aber die gleiche URsache sein, da auch dort das Proposal nur 9 nicht gefunden wird.

**Comment by carlobeltrame** [comment]
So, ich glaube ich habs jetzt geschafft. War nochmals ein Fehler in einer Übersetzung, plus du hattest die Übersetzung inklusive Fehler mit dem Term Customizer kopiert um sie anzupassen. Jetzt sollte es funktionieren, mit akzeptierten sowie abgelehnten Amendments. Bitte nochmals testen und allenfalls Ticket schliessen.
