### ISSUE TITLE
Bereichsfilter stornieren lädt Content in modalem Fenster

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#170]
Analog Dialog Luzern https://github.com/stadtluzern/decidim-ocl/issues/48 umsetzen.

**Comment by carlobeltrame** [comment]
Schätzung: 1 Stunde. Oder wäre durch Upgrade auf Decidim 0.25 gelöst.

**Comment by innosmith** [comment]
Warten auf Upgrade Decidim v0.25.
