### ISSUE TITLE
Default Bild bei Organisationen

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#171]
Analog Dialog Luzern umsetzen https://github.com/stadtluzern/decidim-ocl/issues/63. Gewünschtes Verhalten sowie Default-Bild noch mit städtischem Tenant abstimmen.

**Comment by carlobeltrame** [comment]
Gleiches Bild bei allen Tenants: 2 Stunden.
Pro Tenant ein eigenes Bild: insgesamt 4 Stunden.

**Comment by carlobeltrame** [comment]
@innosmith Welche Variante soll ich hier umsetzen? Und ich brauche noch das Bild bzw. die Bilder.

**Comment by innosmith** [comment]
@carlobeltrame : ich nehme die Frage mit zur Diskussion und melde mich dann wieder.

**Comment by innosmith** [comment]
@carlobeltrame : Default-Bild siehe Email

**Comment by carlobeltrame** [comment]
Ist umgesetzt und auf Integration aufgeschaltet. Das Bild ist überall dasselbe, das heisst das neue Bild sollte auch gleich bei Blogposts etc. angezeigt werden. (Falls auf der Startseite die Blogposts nicht aktualisiert werden, schreib oder bearbeite einen Blogpost, um das Cache zu leeren)

**Comment by innosmith** [comment]
@carlobeltrame : Bei Organisationen und Veranstaltungen passt es. Auf der Startseite bei den neuesten Blogbeiträgen sieht es bei mir mit zwei unterschiedlichen Browsern getestet wie im Attachment aus. Server-side caching?

<img width="1361" alt="Screenshot 2021-11-24 at 13 58 46" src="https://user-images.githubusercontent.com/75796635/143243072-64263cdb-2c55-4436-906d-2fe214795b23.png">

**Comment by carlobeltrame** [comment]
Ja, lag am Cache. Anders als ich angenommen hatte reicht es nicht, einen bestehenden Blogpost zu aktualisieren. Nur beim neu schreiben wird das Cache zurückgesetzt, oder wenn ich manuell das Cache neu starte.
