### ISSUE TITLE
Veranstaltungen von Organisationen nicht chronologisch

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#172]
Analog Dialog Luzern https://github.com/stadtluzern/decidim-ocl/issues/113 umsetzen.

**Comment by carlobeltrame** [comment]
Schätzung: 1 Stunde

**Comment by larsUE** [comment]
Könnte auch bereits mit Decidim V 0.25 behoben worden sein.

**Comment by carlobeltrame** [comment]
Fix ist auf Integration verfügbar.

**Comment by larsUE** [comment]
@Kagemaru: Falls möglich, gerne mit dem Antivirus/WAF auf Prod deployen.
