### ISSUE TITLE
Mehrtägige Veranstaltungen auf Startseite eindeutig darstellen

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#173]
Analog Dialog Luzern darstellen

https://github.com/stadtluzern/decidim-ocl/issues/138

Nur für die Quartierplattform, nicht die Startseite des städtischen Tenants.

**Comment by carlobeltrame** [comment]
Für beide Tenants gemeinsam übernehmen (und optional noch leicht anpassen) wäre sehr einfach, ca. 1 Stunde.
Um das Tenant-spezifisch umzusetzen müssen wir die [Builders](https://github.com/trailblazer/cells#builder) verwenden, um je nach Verfügbarkeit eine andere tenant-spezifische Cell-Klasse zu rendern. Schätzung: ca. 1 Tag

**Comment by larsUE** [comment]
Könnt ihr gerne auch für die Mitwirken-Plattform übernehmen. :-)

**Comment by innosmith** [comment]
@carlobeltrame funktioniert, danke!
