### ISSUE TITLE
Visuelle Anpassungen am Newsfeed

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#174]
Analog Dialog Luzern nur auf der Quartierplattform umsetzen 
https://github.com/stadtluzern/decidim-ocl/issues/149

**Comment by carlobeltrame** [comment]
Für beide Tenants gemeinsam übernehmen (und optional noch leicht anpassen) wäre sehr einfach, ca. 1 Stunde.
Um das Tenant-spezifisch umzusetzen müssen wir die [Builders](https://github.com/trailblazer/cells#builder) verwenden, um je nach Verfügbarkeit eine andere tenant-spezifische Cell-Klasse zu rendern. Schätzung: ca. 1 Tag

**Comment by carlobeltrame** [comment]
@innosmith Auch hier brauche ich ein Default-Bild für Blog Posts die kein Bild haben, und zwar ein gemeinsames für beide Tenants. Ich übernehme mal vorerst das Bild von Luzern um das auf der Testumgebung auszuprobieren, aber weiss nicht ob das von der Lizenz her überhaupt okay wäre, auf Produktion aufzuschalten.

**Comment by innosmith** [comment]
@carlobeltrame : any ideas weshalb ich keine Blogbeiträge auf der Startseite finde? Die Anzeigekomponente ist unter Startseite -> Aussehen aktiv. Einen aktuellen Blogbeitrag habe ich testhalber ebenfalls erstellt. Ev. noch nicht deployed auf INT?

**Comment by carlobeltrame** [comment]
Ich glaube es lag daran dass schlicht keine Blogposts in veröffentlichten Komponenten auf der Plattform waren. Ich habe eine Blog-Komponente in "Testorganisation Anthony" veröffentlicht, und schon erscheinen die Blog Posts.

**Comment by innosmith** [comment]
Jetzt funktioniert es. Seltsam dass die Komponente deaktiviert war; das war glaube ich nicht ich...
