### ISSUE TITLE
Session Timeout verlängern

### ISSUE THREAD

**Issue by TSydekum** [puzzle/decidim-zuerich#18]
Gerade zum testen und Demos ist das kurze Timeout sehr hinderlich. Ich bin mit mehreren Usern in verschiedenen Browsern unterwegs um die Aktionen mit verschiedenen Rechten durchzuspielen und möglichst real zu testen.
Wenn einfach möglich bitte hoch setzen auf maximal sinnvollen Wert. Für den Betrieb muss das dann natürlich auf einen vernünftigen Wert eingestellt werden.

**Comment by carlobeltrame** [comment]
Habe die session expire Zeit auf 24 Stunden gestellt. Damit solltet ihr vorerst ohne Probleme testen können.
