### ISSUE TITLE
Login mit Mein Konto wird nicht angezeigt auf kompakter Darstellung

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#181]
Auf der kompakten Login Seite erscheint beim Mein Konto Button kein Text. Nachstellen könnt ihr das, indem ihr bei einer Idee nicht eingeloggt auf "Endorse" drückt.

**Comment by carlobeltrame** [comment]
Das ist nicht wie ursprünglich gedacht ein CSS-Problem. Im Normalfall wird bei Decidim in diesem Dialog nur ein Logo im Button dargestellt, kein Text. Da wir bisher kein Icon für Mein Konto angegeben haben, erscheint der Button aktuell leer.

Hat Mein Konto ein Logo das wir hier einbauen könnten? Sonst müsste ich wohl die Logik überschreiben die die Buttons anzeigt, sodass ausnahmsweise für OIDC im Button ein Text erscheint.

**Comment by larsUE** [comment]
Mein Konto hat kein Icon. Teilweise wird der "User" Icon verwendet, den wir z.B. bereits im Header bei deinem Namen verwenden. Das würde also zu Verwirrungen führen, würden wir das fürs "externe" Mein Konto nochmals verwenden. Deshalb bitte so überschreiben, dass der Text angezeigt werden. Könntest du den Button Text noch zentrieren (Auch auf der Desktop-Version)? Dann ist er einheitlich mit den anderen Buttons auf der Seite.

**Comment by larsUE** [comment]
@Kagemaru ich habe deine per CSS eingebauten Text wieder entfernt, da nun Texte doppelt angezeigt wurden (übereinander). Die restlichen Styles wirken aber wie gewünscht, danke!
