### ISSUE TITLE
Filter bei Vorschlägen funktionieren nicht

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#184]
Die Filter im Vorschlagsmodul aktualisieren sich nicht selbst und passen sich nicht an.

**Comment by carlobeltrame** [comment]
Ist das gleiche Problem wie in https://github.com/puzzle/decidim-zuerich/issues/196#issuecomment-989973920 beschrieben. #196 wurde fälschlicherweise geschlossen, als Thomas meinen Commit der den ersten Schritt machte auf master übernommen hat. Daher nochmals hier meine Frage an @Kagemaru:

Beim Filtern wird ein data-remote Formular via AJAX abgesendet, mit Header `Accept: text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.0`. Der Server ignoriert das aber immer, und rendert index.html.erb statt index.js.erb. Auf [Meta Decidim](https://meta.decidim.org/processes/roadmap/f/122/) funktionierts korrekt. Hast du eine Ahnung was in Decidim Zürich das noch beeinflussen könnte? Ich habe versucht `format: :js` hinzuzufügen bzw. `.js` an die URL des AJAX requests anzuhängen, aber das hat nicht geholfen.

**Comment by bsantschi** [comment]
Zuerst auf v0.25 upgrade, evtl. behebt es sich von selbst :)

**Comment by larsUE** [comment]
@carlobeltrame @Kagemaru : Leider behebt sich das (wie in der Update-Liste schon angedeutet) mit dem Update nicht. Ich erhalte folgende Fehlermeldung, wenn ich die Filter anwende, vielleicht hilft das weiter:
<img width="1203" alt="Bildschirmfoto 2022-05-02 um 10 17 45" src="https://user-images.githubusercontent.com/60926257/166205068-e478d0a3-dd02-4014-b2d0-5989103e7ca1.png">

**Comment by carlobeltrame** [comment]
Das deckt sich immer noch mit meinen Beobachtungen vom Kommentar oben, als ich @Kagemaru um Rat gefragt habe.

**Comment by Kagemaru** [comment]
@carlobeltrame Der Filter funktioniert nicht richtig, sobald das Overwrite Template [app/views/decidim/proposals/proposals/index.html.erb](https://github.com/puzzle/decidim-zuerich/blob/8c5b2b3cc8904b79395805fee5a52e5ee7f348e5/app/views/decidim/proposals/proposals/index.html.erb)

**Comment by larsUE** [comment]
@carlobeltrame @Kagemaru : So weit ich mich erinnere, war dies der GID Bug, den wir im Herbst gefixed haben? Hierzu habe ich eben noch einen kleinen Bug entdeckt (https://github.com/puzzle/decidim-zuerich/issues/247), vielleicht hängt das ja zusammen?

**Comment by larsUE** [comment]
Cool, dann müssen wir #108 noch testen, sobald die Karte funktioniert. Danke!
