### ISSUE TITLE
PROD Quartierplattform aufbauen

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#185]
Bitte analog der INTEG auch eine PROD Quartierplattform aufbauen.

Freischalten auf SYSTEM: gleich wie INTEG

Zu einem späteren Zeitpunkt folgen noch:
- zukünftige Domain
- Mailsystem
- Allenfalls zusätzliches OAuth-Verfahren (Mein Konto)
- Anpassungen Mime-Types

**Comment by Kagemaru** [comment]
Die Produktivumgebung ist nun online.

Momentane Settings:
- Domain: Interne Domain (Link in Einladung)
- Mailadresse: Interne Mailadresse (Versender der Einladung)
- Login nur mit internem Konto
- Zugriff nur nach Login
- OAuth: Alle deaktiviert
- Mime-Types: Standard

Ich habe noch nicht alle Admins aus der INT auch auf PROD eingeladen. Falls dies notwendig ist könnt ihr selbst noch einladen oder mir eine Nachricht schicken, dann hole ich dies noch nach.

**Comment by innosmith** [comment]
Vielen Dank @Kagemaru !
