### ISSUE TITLE
Städtische Quartierkarte

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#189]
Siehe Emails. Ist die Quartierkarte auf der Startseite mit den Shapefiles wirtschaftlich sinnvoll umzusetzen? Ist der Aufwand in der Pflege der URLs je Quartier mit diesem Approach grösser als mit "Navigation Map"?

**Comment by carlobeltrame** [comment]
Ich habe mir jetzt die Quartierkarte mal im Detail angesehen.

Ich habs hingekriegt, dass die Beispiel-Karte aus der Dokumentation angezeigt wird (https://statistikstadtzuerich.github.io/sszvis/#/map-standard, https://test.meinquartier.zuerich/). Es ist also grundsätzlich möglich eine SSZVIS Karte auf Decidim anzuzeigen, wenn SSZ uns ein extra topoJSON bereitstellt (und am besten gleich hostet), welches die gewünschte Quartiereinteilung beschreibt (was Werner bisher Shapefile genannt hat).

Was ich noch nicht geschafft habe ist die exakte Quartierkarte von https://www.stadt-zuerich.ch/prd/de/index/statistik/kreise-quartiere.html anzuzeigen, inklusive klickbaren Quartieren. Diese Karte verwendet einen vorprogrammierten Modus "zurichStatistischeQuartiere", zu dem ich nirgends Dokumentation gefunden habe. Um genau diese Karte zu übernehmen müsste ich jetzt reverse engineeren wie die Karte auf der stadt-zuerich.ch Seite genau eingerichtet ist, und dann noch (wenn überhaupt möglich) das "Shapefile" JSON austauschen und die Farben anpassen, auf Mobile optimieren etc.. Da komme ich dann schätzungsweise schon mal an die Grenze von dem was in zwei Tagen dieses Jahr noch möglich ist. Einfacher könnte es werden, wenn Dokumentation zu diesem vorprogrammierten "zurichStatistischeQuartiere" Modus vorhanden wäre, je nach Qualität dieser Dokumentation.

Alternativ könnte ich die Karte die ich jetzt hingebracht habe selber anpassen bis sie möglichst so aussieht wie gewünscht. Aber auch dann müsste ich mich in die Maus-Interaktion und Farbgebung mit den zugrundeliegenden Technologien SSZVIS, D3 und topoJSON einlesen.

Fazit: Es ist möglich, eine solche Karte auf Decidim anzuzeigen. Ich werde aber an die Grenzen der Zeit kommen die dieses Jahr noch dafür verfügbar ist.

**Comment by innosmith** [comment]
@carlobeltrame: Wir möchten gerne für die Quartierübersicht die städtische Lösung umsetzen. 

Bitte Prio 1 auf der Startseite gemäss Designvorschlag von Sascha umsetzen. Links Text, rechts die Quartierkartenübersicht mit clickbarem Filter auf die entsprechenden Organisation. Die passenden Farben solltest du erhalten haben, sonst bitte melden. Auf dem Desktop sollen Text und Quartierkarte nebeneinander angeordnet sein, auf dem Mobile untereinander. Ich passe dann für die 25 Quartiere die URL's für die Filter an. Auf INT werden die URL's anders sein als auf PROD.

Prio 2 - vermutlich Anfang 2022 - möchten wir die Organisationsübersichtsseite ebenfalls um die Karte ergänzen.

**Comment by carlobeltrame** [comment]
@innosmith die gelbgrüne Farbe wie auf Saschas Mockup ist klar. In welcher Farbe soll ein Quartier aufleuchten auf das man mit der Maus zeigt?

**Comment by innosmith** [comment]
@carlobeltrame : ich würde dafür die eingestellte Sekundärfarbe nehmen, in welchem auch der Logohintergrund gestaltet ist.

**Comment by carlobeltrame** [comment]
Die gewünschte Karte ist nun auf https://test.meinquartier.zuerich aufgeschaltet. Die Links der einzelnen Quartiere kannst du selber im HTML-Block 2 anpassen @innosmith, ich habe nur Affoltern und Seebach testhalber mal verlinkt.

Die WAF hat mich zuerst blockiert, da der Code zusammen mit dem TopoJSON so gross wäre dass die WAF einen Angriff vermutet. Daher lade ich derzeit das TopoJSON von der Dokumentations-Seite der Statistik Stadt Zürich herunter: https://statistikstadtzuerich.github.io/sszvis/topo/stadt-zurich.json
Das ist aber nicht ganz optimal, da unsere Karte so spontan und ohne Warnung kaputt gehen könnte wenn das TopoJSON z.B. mal umbenannt wird. Ich könnte das TopoJSON stattdessen bei uns in Decidim hosten, dann wären wir aber selber verantwortlich es bei Bedarf zu aktualisieren, und Änderungen am TopoJSON würden dann ein Deployment verlangen. @Kagemaru @innosmith habt ihr weitere Ideen wo wir das TopoJSON hosten könnten? Gibt es irgend einen freien Dateiupload in Decidim den wir dafür nutzen könnten?

**Comment by innosmith** [comment]
Danke @carlobeltrame. Ich kläre folgende Punkte mit Werner:
- Ich hätte erwartet, dass jeweils nur ein Quartier highlighted ist und nicht jeweils auch noch benachbarte Quartiere in einem Zwischenfarbton.
- Das Hosting des stadt-zurich.json würde ich eher nicht sep. hosten mit dem Nachteil der Abhängigkeit -> Rückfrage bei der GIS-Abteilung.
- Die englische Übersetzung (Text links der Karte) zwingt uns mit der jetzigen HTML-Block Lösung, zwei sep. Versionen für INT sowie PROD zu führen.

**Comment by carlobeltrame** [comment]
Das Highlighting des Stadtkreises habe ich von der Vorlage übernommen, das kann ich auch ganz einfach ausschalten.

Was ich selber noch nicht optimal finde ist das Verhalten auf Mobile bzw. auf touch-Geräten. Bei einmaligem Tippen wird man bereits weiter zur URL geleitet. Das ist mühsam wenn man sich geografisch nicht gut auskennt. Ich könnte es z.B. einrichten dass auf Touch-Geräten der erste Tap ein Quartier auswählt und den Tooltip öffnet, und erst ein zweiter Tap zur URL weiterleitet. Oder im Tooltip könnte man auf Touch-Geräten einen Link einfügen er es offensichtlich macht dass man erneut drücken muss.

**Comment by innosmith** [comment]
@carlobeltrame : In dem Fall bitte das Highlighting des Stadtkreises ausschalten und nur auf Mobile-Geräten die letzte vorgeschlagene Lösung umsetzen. Das muss ich einmal ausprobieren können.

**Comment by carlobeltrame** [comment]
Ist beides umgesetzt.

Das "panning" Verhalten auf Mobile funktioniert leider nicht wie [dokumentiert](https://statistikstadtzuerich.github.io/sszvis/#/behaviors?a=panning-behavior). Eigentlich sollte es möglich sein, mit dem Finger über die Quartiere zu fahren und so ein Hover-Verhalten zu simulieren. Das funktioniert aber auch in der [Beispiel-Karte](https://statistikstadtzuerich.github.io/sszvis/#/map-standard?a=z%C3%BCrich-quartiere) aus der Dokumentation nicht. Da könnte man dann noch beim SSZ anklopfen, ob sie das beheben können.

Ausserdem könnte es auf Mobile eher mühsam werden, wenn man auf der Karte nicht mit zwei Fingern zoomen kann. Aber jetzt hat man wenigstens mehrere Versuche, um das richtige Quartier zu erwischen, bevor man zum eigentlichen Quartierverein navigiert.

**Comment by innosmith** [comment]
@carlobeltrame : bestens! Das Hover-Verhalten gebe ich nebst Hosting ebenfalls mit zur Klärung.

**Comment by innosmith** [comment]
@carlobeltrame : wieviel Aufwand schätzt du, die neue Karte auch zuoberst auf der Organisationsseite https://test.meinquartier.zuerich/assemblies anzuzeigen? ich könnte von Sascha hierfür noch einen Mockup-Vorschlage machen lassen, damit klar ist, wo die verschiedenen Filterelemente am besten anzuordnen sind. Z.B. Karte und darunter die bestehenden drei Filter oder ev. Dropdowns neben Karte angeordnet, bevor dann die passenden Organisationen angezeigt werden.

**Comment by carlobeltrame** [comment]
Wenn du gleichzeitig an den Filterelementen etwas ändern möchtest wäre ich froh um ein Mockup.
Grundsätzlich gibt es auf dieser Seite keinen HTML-Block den auch du nachträglich einfach abändern kannst. Wenn sich also die URL eines Quartiers ändert würde das in der einfachsten Variante ein Deployment verlangen. Alternativ könnte ich versuchen, den Inhalt vom HTML-Block 2 dort hin zu rendern. Was wäre dir lieber? Würde sich die Karte sowieso in irgendeiner Hinsicht von derjenigen auf der Startseite unterscheiden?

**Comment by innosmith** [comment]
Nachfolgend der Designvorschlag von Sascha. Die Filter wären neu alle untereinander und links von der Karte dargestellt. Entsprechend könnten wir auch nicht einfach den HTML-Block 2 der Startseite wiederverwenden; oder doch? Die Karte auf der Startseite soll die gleiche wie auf der Organisationsseite sein.

![Mein-Quartier-Organisationen-mit-Karte](https://user-images.githubusercontent.com/75796635/147985679-865a8386-fa22-4772-88d5-f38573cb0da0.png)

**Comment by innosmith** [comment]
Ergebnis der Diskussion mit Carlo: wir benötigen ein eigenes Modul um damit:
- auf der Multi-Tenant Umgebung die Anzeige nur für die Quartierplattform genutzt wird
- Texte in EN/DE übersetzbar sind
- auf INT und PROD unterschiedliche Links für die Quartierfilter hinterlegt werden können
- Geschätzter Aufwand 2t

**Comment by innosmith** [comment]
@carlobeltrame : passt jetzt alles, danke.
