### ISSUE TITLE
Benachrichtigungen Ansicht funktioniert nicht

### ISSUE THREAD

**Issue by TSydekum** [puzzle/decidim-zuerich#19]
https://pitc-decidim-zuerich-int.ocp.puzzle.ch/notifications

**Comment by carlobeltrame** [comment]
Das ist in der nächsten Decidim-Version [gefixt](https://github.com/decidim/decidim/pull/5964). Ich habe zudem einen temporären Fix eingefügt den wir schon für die Quartieridee entwickelt hatten, damit das für den Moment bereits funktioniert.
