### ISSUE TITLE
Bilder Resizing wird immer wieder zurückgesetzt

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#190]
Bilder, welche mit Decidim Awesome in Texteditoren eingesetzt werden, sind nach dem Speichern wieder in Originalgrösse im Backend-Texteditor. D.h. die Wunschgrösse wird immer wieder verworfen, resp. ist nur solange im Frontend passend sichtbar, solange im Backend-Editor nichts verändert wird.

Dasselbe Problem existiert z.B. auch auf test.dialogluzern.ch. Bitte Aufwände je zur Hälfte auf die beiden Projekte Dialog Luzern und Quartierplattform Zürich aufteilen.

Bitte mit Decidim Awesome prüfen und koordinieren.

**Comment by Kagemaru** [comment]
https://github.com/Platoniq/decidim-module-decidim_awesome/issues/98

**Comment by innosmith** [comment]
@Kagemaru ist der Fix wirklich auf INT? Eben (Fr 10.12.2021 13:35) getestet und immer noch dasselbe Fehlverhalten.

**Comment by Kagemaru** [comment]
@innosmith Ich habe es erneut deployt:
https://mitwirken.integ.stadt-zuerich.ch/admin/participatory_processes/feedback/edit

**Comment by innosmith** [comment]
Funktioniert, danke!
