### ISSUE TITLE
Kompakte Organisationsübersicht

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#192]
Bitte analog Dialog Luzern gemäss Ticket https://github.com/stadtluzern/decidim-ocl/issues/151 umsetzen.

**Comment by Kagemaru** [comment]
Ich brauche hierfür noch ein default Bild. Bei dialogluzern ist es momentan dieses: https://dialogluzern.ch/assets/organization-default-image-a178f0480dae1b69e7969c441b36f47ce662c0bb6ce7360968ccc589efe330ea.png

**Comment by carlobeltrame** [comment]
Ich hatte für https://github.com/puzzle/decidim-zuerich/issues/174 und andere Issues bereits ein Default-Bild im Repo... hast du den antivirus-Branch geforcepusht?

**Comment by Kagemaru** [comment]
@carlobeltrame Ich habe den vorherigen Stand wiederhergestellt und meine Changes draufgepackt. Sorry für die Umstände.

**Comment by innosmith** [comment]
@bsantschi : bitte allfällige Zusatzaufwände aufgrund Überschreibens siehe Ticket nicht verrechnen.
