### ISSUE TITLE
Filterfunktion & Suchfunktion in Vorschlags-Komponente funktionieren nicht

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#196]
Auf Prod & Int

Beispiel hier, betrifft die gesamte linke Spalte:
https://mitwirken.integ.stadt-zuerich.ch/processes/feedback/f/34/proposals?filter%5Bsearch_text%5D=&filter%5Bstate%5D%5B%5D=&filter%5Borigin%5D%5B%5D=

**Comment by carlobeltrame** [comment]
Das Problem scheint vielschichtig zu sein. Ich habe eine erste Schicht gefixt. Das unmittelbare Problem kam von einer kleinen Änderung die wir bei der Quartieridee gemacht hatten und dann bei Decidim-Updates nicht aktualisiert hatten. Zur Referenz, es war die Zelle I108 im [Übersetzungs-Google-Sheet](https://github.com/puzzle/quartieridee/issues/25#issuecomment-625120663) der Quartieridee. Ich habe die Änderung jetzt mal vorerst ganz entfernt, weil sie mir nicht über die Quartieridee hinaus sinnvoll erschien (ihr könnt einfach offizielle Proposals aktivieren, dann ist der Herkunfts-Filter wieder da) und weil es gerade schneller war, einfach zum Decidim-Standard zurückzukehren.

Ich hab das mal auf der Integrationsumgebung ausgerollt. Es tritt jetzt mal kein Konsolenfehler mehr auf wenn man filtert, aber die Filterung funktioniert trotzdem noch nicht. @Kagemaru beim Filtern wird ein Rails-UJS data-remote Formular via AJAX abgesendet, mit Header `Accept: text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.0`. Der Server ignoriert das aber immer, und rendert index.html.erb statt index.js.erb. Auf [Meta Decidim] funktionierts korrekt. Hast du eine Ahnung was in Decidim Zürich das noch beeinflussen könnte? Ich habe versucht `.js` an die URL des AJAX requests anzuhängen, aber das hat auch nicht geholfen.
