### ISSUE TITLE
Footeranpassungen

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#198]
Rechts neben das Stadt Zürich Logo bitte noch einen clickbaren Text hinzufügen: «Website mit der freien Software Decidim.org erstellt» mit Link auf https://decidim.org. Mockup inkl. passendes Stadt Zürich Logo folgt noch.

**Comment by innosmith** [comment]
@Kagemaru : Die Spezifikation hierzu war noch nicht fertig, sorry. Das Logo muss kleiner und passend zum Design sein. Hinzu kommt noch ein clickbarer Text, den wir noch festlegen müssen. Das liefere ich alles noch.

**Comment by innosmith** [comment]
![Mein-Quartier-Footer-2](https://user-images.githubusercontent.com/75796635/146209675-d7f077e0-34cd-4bbf-8431-d6e779f39808.png)
![Mein-Quartier-Header-Footer-Mobile](https://user-images.githubusercontent.com/75796635/146209733-5a79b1f3-2379-41de-bc44-cbd424c026c8.png)

**Comment by carlobeltrame** [comment]
Das Layout auf Mobile habe ich so ergänzt.

Die Reihenfolge von Impressum, und rechtlichen Hinweisen und weiteren Seiten könnt ihr selber ändern, indem ihr das "Reihenfolge" Feld der entsprechenden Seiten anpasst.

Um das Logo einzufärben brauche ich es entweder bereits korrekt eingefärbt als PNG, oder in beliebiger Farbe als SVG damit ich es selber einfärben kann. Ich habe jetzt wieder die eingebaute Funktion von Decidim wiederhergestellt, dass ihr das Footer-Logo sowie der Link zu dem das Logo führt ("Offizielle Organisations-URL") selber unter Einstellungen -> Aussehen anpassen könnt.

Nur einen Teil der Schrift anders einfärben kann ich nicht mit reinem CSS, da immer die ganze Zeile ein einziger Link ist. Diese Änderung würde eine Code-Änderung verlangen und somit auch Mitwirken Zürich tangieren. @innosmith ist dies wirklich so wichtig, oder belassen wirs beim einfarbigen dunklen Text?

**Comment by innosmith** [comment]
@carlobeltrame besten Dank!  Ich hoffe diese Änderung folgt nicht wieder zu Side-Effects auf die Mitwirkungsplattform.

Die Textlinks inkl. Reihenfolge passen wir an. Eine Schriftfarbe für die ganze Linkzeile ist i.O. Ich organisiere uns ein passend eingefärbtes Footer-Logo und füge es dann ein.

**Comment by innosmith** [comment]
@carlobeltrame : Footer auf INT ist soweit in Ordnung. Das CSS habe ich auf PROD kopiert. Vermutlich müsstet ihr noch ein Software-Deployment auf PROD machen, damit das Logo dann richtig im Footer angezeigt wird.

**Comment by carlobeltrame** [comment]
Ja, korrekt. Ich könnte das Produktionsdeployment heute über den Mittag machen wenn ihr nichts dagegen habt? @innosmith @larsUE

**Comment by innosmith** [comment]
Für mich ok! @larsUE auch?

**Comment by larsUE** [comment]
@carlobeltrame Go for it! :-)

**Comment by carlobeltrame** [comment]
Ist durchgelaufen. Auf der Mitwirken-Plattform hatte ich bereits vorgängig das nötige CSS ergänzt um das Logo zu verstecken.
