### ISSUE TITLE
Logo SVG Upload ermöglichen

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#202]
Bitte analog https://github.com/puzzle/decidim-zuerich/issues/140 das Meinquartier.Zuerich Logo oben links als SVG nutzbar machen, damit das Logo schärfer wird.

**Comment by carlobeltrame** [comment]
Ich habe meine geplante Änderung umgesetzt, aber es funktioniert leider noch nicht. Wies aussieht verarbeitet Decidim intern die hochgeladenen Bilder noch mit einem Tools namens minimagick, vermutlich um das Bild für spätere Verwendung in verschiedene Grössen zu konvertieren, oder allfällig die Bildorientierung zu korrigieren, etc.. Dieses Tool kann nur mit Pixelbildern umgehen, und bei SVG wäre ja das vorab-Skalieren auf verschiedene Grössen ohnehin nutzlos.

Um das also wirklich zu lösen müsste ich da etwas tiefer in Decidim eingreifen als ursprünglich gedacht, und z.B. eine Ausnahme bei der vorab-Skalierung einführen falls das Bild ein SVG ist. Ich habe noch nicht im Detail angeschaut wie man das genau umsetzen würde, aber es übersteigt auf jeden Fall den zuvor klein scheinenden Aufwand. @innosmith bitte bestätigen ob ich hier noch weitermachen soll. Ev. auch mit @larsUE absprechen wegen Aufteilung des Aufwands.

**Comment by innosmith** [comment]
@carlobeltrame, @larsUE  : dann bitte abbrechen und wir uploaden eine Pixelgrafik gemäss Vorgaben.

**Comment by larsUE** [comment]
@carlobeltrame @innosmith : Wir haben tatsächlich auch noch Budget bei uns für das SVG-Logo. Für die mitwirken-Plattform wäre das noch wichtig, da das unscharfe Logo immer wieder bemängelt wird. Könntest du eine Aufwandschätzung machen?

**Comment by innosmith** [comment]
@larsUE : In Abstimmung mit Werner dieses Ticket bei Bedarf über die Mitwirkungsplattform umsetzen. Seitens Quartierplattform haben wir hierfür aktuell kein Budget.
