### ISSUE TITLE
Design Organisation anpassen

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#206]
Bitte das Design einzelner Organisationsseiten gemäss Mockup anpassen, um es so vom städtischen CI/CD abzugrenzen.

**Comment by innosmith** [comment]
![Mein-Quartier-Organisationen-V1](https://user-images.githubusercontent.com/75796635/146679272-e3f6eece-525a-4134-8a59-a30fe356d333.png)

**Comment by innosmith** [comment]
Bitte die optimale Bildgrösse für Desktop und auch Mobile optimiert festhalten

**Comment by carlobeltrame** [comment]
Ist auf Integration implementiert. Optimale Bildgrösse ist 1410x600. Das gleiche Seitenverhältnis wird auf allen Bildschirmgrössen beibehalten.

**Comment by innosmith** [comment]
@carlobeltrame : danke! Auf Mobile sieht es sehr gut aus. Auf meinem 13"-Laptop unterwegs füllt das Bild fast den ganzen Bildschirm, siehe Screenshot. Sollten wir nicht links und rechts noch weiss lassen, damit man mehr vom Bild sieht; aber alles etwas kleiner? Was meinst du?
![Uploading Screenshot 2022-01-11 at 19.03.33.png…]()

**Comment by carlobeltrame** [comment]
Das weiss links und rechts ist da sobald der Bildschirm breiter als 1410 Pixel ist. Wenn du willst kann ich das Verhältnis noch auf z.B. 1410x500 ändern sodass auf deinem Bildschirm weniger der Höhe vom Bild eingenommen wird. Aber schmaler kann ich es nicht wirklich machen, wenn das Bild immer noch breiter sein soll als der Inhalt (wie auf dem Mockup von Sascha).

**Comment by innosmith** [comment]
@carlobeltrame : bin nun am grossen Bildschirm und kann es besser vergleichen, danke. Bitte das Bild wie vorgeschlagen auf 1410 x 500 anpassen. Kommt hinzu, dass wenn man einen Navigationspunkt unterhalb des Bildes selektiert, die Seite nach dem neu laden automatisch von oben nach unten scrollt, was etwas unschön aussieht. Ich vermute wir machen dann noch eine weitere Optimierung nach morgen. Kannst du diese Anpassung bitte gleich auf PROD bringen?

**Comment by carlobeltrame** [comment]
Format ist angepasst und auf Prod übernommen.

Das automatische Scrollen musst du mit Lars ausdiskutieren, das hat Thomas für die Mitwirken-Plattform implementiert. Bisher können wir das noch nicht pro Tenant ausschalten.

**Comment by innosmith** [comment]
@carlobeltrame : bestens, vielen Dank!
