### ISSUE TITLE
Umfrage Field Checks sind von Beginn an aktiviert

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#207]
Bei Umfragen erscheinen von Beginn an Fehlermeldungen (z.B. dass das Feld noch nicht ausgefüllt wurde), ohne dass man mit dem Ausfüllen der Umfrage zusammenhängt. M.E. erscheint dieser Bug seit wir die Kontaktmöglichkeit per E-Mail für Umfragen aktiviert haben. 

Beispiel hier: https://mitwirken.stadt-zuerich.ch/processes/stadtidee/f/67/

**Comment by larsUE** [comment]
@carlobeltrame bist du hier bereits vorwärtsgekommen?

**Comment by carlobeltrame** [comment]
Puh das war jetzt tricky zu debuggen. Das Problem wird von Decidim Awesome's [Auto-Save](https://mitwirken.stadt-zuerich.ch/admin/decidim_awesome/config/surveys) Feature verursacht. Sobald ein Browser die lokale Speicherung (localStorage) der Daten überhaupt unterstützt, wird beim Laden der Umfrage-Seite auf jedem Eingabefeld eine "Änderung" simuliert, auch wenn gar keine Daten aus der localStorage wiederhergestellt wurden. Der Validierungs-Code von Decidim hört auf diese Änderungen und validiert die geänderten Felder (alle), und markiert folglich alle obligatorischen aber leeren Eingabefelder als ungültig.

Das Problem ist kurzfristig behoben, wenn ich das Decidim-Awesome-Feature "Auto save forms" bei "Umfragen" deaktiviere. Ich habe noch ein [Issue](https://github.com/Platoniq/decidim-module-decidim_awesome/issues/153) bei Decidim Awesome eröffnet, da ich keines gefunden habe welches das schon meldet.

Zusätzlich sind wir noch von diesem offenen Bug bei Decidim betroffen: https://github.com/decidim/decidim/issues/7691
Das führt zur überflüssigen Nachricht "Es wurden zu viele Auswahlmöglichkeiten ausgewählt" unter jedem Eingabefeld.

**Comment by carlobeltrame** [comment]
Das wurde in der neuesten Version von decidim awesome gefixt. Sobald wir auf Decidim 0.26 (nicht 0.25) updaten und das Modul aktualisieren kannst du das Auto-Save-Feature wieder aktivieren.
