### ISSUE TITLE
Logo in generierten Emails nicht komplett sichtbar

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#209]
Siehe Screenshot, ist das Logo aufgrund weisser Farbe in automatisch generierten Emails mit weissem Header nur teilweise erkennbar. 

Wie machen wir dies am besten komplett sichtbar?
a) alternative Email-Hintergrundfarbe anstatt weiss?
b) alternatives Logo mit z.B. grün herum analog Startseite?

Wäre beides gleich einfach technisch umsetzen?

**Comment by innosmith** [comment]
![Screenshot 2022-01-09 at 17 12 11](https://user-images.githubusercontent.com/75796635/148690855-b6dcc1b4-8315-46d6-9e5b-2f4e4b88eba6.png)

**Comment by innosmith** [comment]
@carlobeltrame : konntest du dieses Ticket bereits anschauen? Danke.

**Comment by larsUE** [comment]
Vergleicht auch bitte mit https://github.com/puzzle/decidim-zuerich/issues/93
Da lassen sich bestimmt Synergien nutzen.

**Comment by carlobeltrame** [comment]
CSS-Änderungen in Mails können wir analog f87d52b88511051dc0ddb03b875fdd165b695dbf machen.
Ein anderes Logo könnten wir ebenfalls durch ersetzen des Mail-Templates einsetzen.

Beides ist relativ einfach (nur etwas mühsam zum testen), aber beides ist nicht Tenant-spezifisch änderbar. Um das Tenant-spezifisch unterschiedlich zu gestalten sehe ich derzeit keine andere Möglichkeit als mit einem Modul das die Einstellungen pro Tenant speichern kann. Also auch hier müsste entweder Decidim Awesome übernehmen, oder wir müssen ein eigenes Modul erstellen welches sich ähnlich wie Decidim Awesome an den richtigen Stellen einhängt.

Aufwand falls dasselbe Design für beide Tenants angewendet werden kann: 0.5 PT, je nach Menge der Anpassungen.
Aufwand für den Aufbau eines Moduls das tenantspezifische Mail-Styles ermöglicht: 2-3 PT.

**Comment by innosmith** [comment]
Danke @carlobeltrame für die Vorschläge. Wenn ich #93 anschaue, schwebt beiden Tenants ein etwas eigenes Design der automatisch generierten Emails vor. Demzufolge müssten wir entweder ein neues Modul entwickeln oder Decidim Awesome dafür gewinnen. Vorschlag @larsUE : ich frage bei Ivan von Decidim Awesome nach, was sie für Pläne haben.

**Comment by larsUE** [comment]
Danke fürs Nachfragen @innosmith . Vielleicht schaffen wir aber auch eine gemeinsame Lösung. Z.B. würde es der Leserlichtkeit bereits sehr viel helfen, wenn das Logo zuoberst linksbündig in einem Banner der Primärfarbe (bei uns züriblau, bei euch türkis) erscheinen würde. Und wenn der Newsletter in der Plattformfont verschickt würde

**Comment by innosmith** [comment]
Issue bei Decidim Awesome eingereicht https://github.com/Platoniq/decidim-module-decidim_awesome/issues/151.

**Comment by innosmith** [comment]
Für das Backend ebenfalls eingereicht https://github.com/Platoniq/decidim-module-decidim_awesome/issues/152.
