### ISSUE TITLE
Logo-Anpassung

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#213]
Für einen Mitwirkungsprozess haben wir einen besonderen Case. Und zwar sollen für alle Prozess der VBZ-Prozessgruppe ein eigenes Erscheinungsbild verwendet werden, um es etwas von der Stadt abzuheben. Per Decidim Awesome lässt sich das gut umsetzen. Nun die Frage: Lässt sich für die Prozessgruppe das Stadtzürcher -Logo oben rechts ersetzen? Wenn ja wie (bevorzugt per CSS, sonst per Code)? Was wäre der Aufwand?

**Comment by larsUE** [comment]
Link zur Test-Prozessgruppe: https://mitwirken.integ.stadt-zuerich.ch/processes_groups/3

**Comment by carlobeltrame** [comment]
Angenommen mit "oben rechts" meinst du "oben links", und angenommen das gewünschte Logo ist irgendwo auf dem Internet verfügbar: Ja, ist mit reinem CSS möglich, siehe https://css-tricks.com/replace-the-image-in-an-img-with-css/
Aufwand wohl 1-2 Stunden.

Aber Vorsicht mit leichtfertigen CSS-Anpassungen: Auf Mobile sieht die VBZ Mitreden Seite jetzt noch nicht so prickelnd aus.

**Comment by larsUE** [comment]
Ups, haha! Genau, oben links. Super, danke für die Info. Das war nur ein Testing meinerseits, wie viel innerhalb einer Prozessgruppe möglich ist. Die endgültigen Änderungen würden wir aber professionell durchführen lassen.

**Comment by larsUE** [comment]
@innosmith @carlobeltrame : Ich hab den oben erwähnten Trick mal angewendet (auf ein SVG, dass bei uns über Google Drive gehostet ist), und es funktioniert tatsächlich. Man müsste es allerdings noch deutlich finetunen, aber da sind meine Kenntnisse leider noch nicht so weit. Aber die Methode funktioniert!

**Comment by larsUE** [comment]
Alle VBZ CSS Prozessanpassungen werden extern durchgeführt.
