### ISSUE TITLE
Kommentare ohne Login

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#214]
Für den VBZ-Prozess kam die Frage, ob das Kommentar-Modul dahingehend verändert werden könnte, das Kommentare ohne Konto erfasst werden könnten (wie bei den analog Proposals). Was wäre hier der Aufwand?
Wir müssten wohl bei allen Funktionen, wo die Kommenatrfunktion an- und abgeschaltet wird auch angegeben, ob Anonyme Kommentare erlaubt sein sollen oder nicht (per default: nicht erlaubt).
Was wäre der Aufwand?

**Comment by larsUE** [comment]
Hinweis: V0.25 führt Änderungen am Kommentarsystem ein:

- https://github.com/decidim/decidim/pull/6916: Verifizierungsstufe von Kommentare kann eingestellt werden (soweit ich weiss ist die anoynme Teilnahem aber nicht möglich)
- https://github.com/decidim/decidim/pull/8035: Erweitert vorherigen Fix auf alle Funktionen wo Comments möglich sind.

**Comment by carlobeltrame** [comment]
Ich habe mir das mal angeschaut. Aufgrund der Grösse des Eingriffs ist eine genaue Schätzung sehr schwierig. Die Änderungen in Decidim 0.25 scheinen uns nicht zu tangieren. Ich habe es mit dem anonymous_proposals Modul verglichen, und dem Aufwand den wir dort betrieben haben, um das pro Prozess konfigurierbar zu machen, und verglichen mit der Menge an Code-Änderungen überhaupt in diesem Modul. Grob gesagt sind unsere 4 von 35 Commits innert 1.5 Tagen entstanden, aber Commits können unterschiedlich viele Änderungen enthalten.
Die Kommentare anonym zu ermöglichen würde tendenziell eher mehr Aufwand bedeuten als bei den Vorschlägen, weil die Vorschläge in einem Modul konzentriert sind, aber Kommentare an mehreren Orten möglich sind.

Somit schätze ich (eher optimistisch) in der Grössenordnung von 1-2 Wochen Aufwand für dieses Feature.
