### ISSUE TITLE
Auzählungspunkte im Backend werden zu Gedankenstrichen im Frontend

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#219]
Siehe Backend und Frontend Screenshot werden Aufzählungspunkte - im Backend als Punkte dargestellt - im Frontend mit einem zu langen Gedankenstrich dargestellt. Bitte im Frontend ebenfalls als Aufzählungspunkt darstellen.

**Comment by innosmith** [comment]
![Screenshot 2022-01-14 at 11 31 47](https://user-images.githubusercontent.com/75796635/149501639-c12bf582-1bd2-48e4-b049-ce9358261626.png)
![Screenshot 2022-01-14 at 11 31 56](https://user-images.githubusercontent.com/75796635/149501658-54c832a4-57d8-4e79-85e6-9b48e16d88c4.png)

**Comment by larsUE** [comment]
Das ist wegen dem städtischen CSS so. Soll ich das abändern? Falls ja, als was hättest du es gerne (Punkte, Kreise, Quadrate)?

**Comment by larsUE** [comment]
Testbar auf INT: https://test.meinquartier.zuerich/assemblies/testmqz
