### ISSUE TITLE
Prozessschritt nur an einem Tag

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#221]
Prozessschritte müssen derzeit eine Zeitspanne von mehreren Tagen abdecken. Viele unserer Prozesse haben jedoch einzelne Veranstaltungen, die wichtig sind und als eigenständige Prozessschritte zu verstehen sind. 

Deshalb folgendes anpassen:
- Im Backend: Derzeit laufen Checks bei der Datumeingabe, so dass das Enddatum nach dem Startdatum liegen muss (und auch umgekehrt). So anpassen, dass das Startdatum vor ODER GLEICH dem Enddatum ist (und das Enddatum nach ODER GLEICH dem Startdatum ist).
- Im Frontend: Wenn beide Daten gleich sind, wir bei der Schrittübersicht auf der Prozessseite (kleines Kästchen) und in der Einzelübersicht keine Zeitspanne angezeigt, sondern nur ein Einzeldatum

**Comment by Kagemaru** [comment]
Ich hab mal kurz die Validations angeschaut. Ich denke, dieser Ansatz sollte funktionieren:
```
start_options = Decidim::ParticipatoryProcessStep._validators[:start_date].first.options
end_options = Decidim::ParticipatoryProcessStep._validators[:end_date].first.options

new_start_options = start_date.options.except(:before).merge(before_or_equal_to: :end_date)
new_end_options = start_date.options.except(:after).merge(after_or_equal_to: :start_date)

Decidim::ParticipatoryProcessStep._validators[:start_date].first.instance_variable_set(:@options, new_start_options)
Decidim::ParticipatoryProcessStep._validators[:end_date].first.instance_variable_set(:@options, new_end_options)
```

Ich probiere dies sobald ich mehr Zeit habe.

**Comment by larsUE** [comment]
Carlo hat richtig vermutet, dass nur ein Startdatum (oder gar kein Datum) ausgefüllt werden muss. Nicht ausgefüllte Daten werden mit einem Fragezeichen angezeigt. Wir können also die Validators sein lassen (bzw. das ist sogar gut, dass sie so funktionieren). Wir bräuchten also eine Anpassung, die nur einzelne Daten anzeigt, falls vorhanden, und nicht die Spanne mit Fragezeichen.

Hier ein paar Cases:
<img width="694" alt="Bildschirmfoto 2022-01-18 um 12 35 23" src="https://user-images.githubusercontent.com/60926257/149930156-4cf46214-3976-49c8-b033-d97813761883.png">

**Comment by Kagemaru** [comment]
Ich habe mal diese Formate verwendet:
![decidim_zuerich_step_dates2](https://user-images.githubusercontent.com/12155/150140161-36291e23-491f-483e-8959-66b5b44962c8.png)
![decidim_zuerich_step_dates1](https://user-images.githubusercontent.com/12155/150140162-6589f1c7-db20-4793-80e4-b55291edf84e.png)

Ich werde es mal so auf INT deployen. Melde dich falls du ein anderes Format wünschst.

**Comment by larsUE** [comment]
Das sieht super aus! Ich sehe es noch nicht auf der INT & nehme an, du bist noch dran. Funktioniert diese Darstellung auch im Schrittübersichtsfenster?
<img width="1262" alt="Bildschirmfoto 2022-01-19 um 16 25 20" src="https://user-images.githubusercontent.com/60926257/150161365-0091d6f2-46d7-48c4-8eab-cc8eed49f5d2.png">

**Comment by Kagemaru** [comment]
@larsUE Ja, hatte es noch nicht getagt. Nun ist es drauf.

**Comment by larsUE** [comment]
Funktioniert prima, vielen Dank! Könntest du Ende Woche einen Prod-Release machen, denn die Änderung wird zu Beginn nächster Woche gebraucht.
