### ISSUE TITLE
WAF blocked Adobe Analytics

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#234]
Seit dem WAF Update werden keine Statistiken durch Adobe Analytics mehr erfasst

**Comment by larsUE** [comment]
@Kagemaru könntest du hier bitte möglichst bald eine exception definieren?

**Comment by Kagemaru** [comment]
@larsUE 
Ich habe dir am 31.03. zu diesem Thema ein Mail geschickt.
Von meiner Seite aus sieht es gut aus. Kannst du dies testen und wieder Feedback geben, falls dem nicht so ist?

**Comment by larsUE** [comment]
@Kagemaru Sorry, habe nachgeschaut und deine E-Mail irgendwie nicht erhalten. Auf alle Fälle habe ich in den Logs von Analytics geschaut und da werden seit dem 31. März wieder Zahlen erfasst. Danke dir!
