### ISSUE TITLE
Umfrage Export funktioniert nicht

### ISSUE THREAD

**Issue by TSydekum** [puzzle/decidim-zuerich#24]
Auch nach dem Update kann ich keine Umfrageresultate herunterladen:
![image](https://user-images.githubusercontent.com/66952143/94903378-02992e00-049a-11eb-8dc4-588416abdff7.png)

Es kommt kein Mail.

**Comment by Kagemaru** [comment]
Bitte nochmals testen nach dem Storage Fix für Ticket #10
Ich habe es persönlich getestet und für mich funktioniert es jetzt.
