### ISSUE TITLE
Javascript-Edits zum laufen bringen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#240]
- [x] Process redirects
- [x] Jump down bei Prozessmenü: funktioniert nicht ⇨ betrifft unsere JS Erweiterung @carlobeltrame
- [x] Menü Down-Slider: funktioniert nicht (Menü Down-Slider ist die Funktion, dass das Top-Menü (mit Suchbar) mit dem runterscrollen verschwindet. Siehe hier: https://github.com/puzzle/decidim-zuerich/issues/83)

**Comment by larsUE** [comment]
Notizen Process Redirects:

- Prozess Redirects testen: Funktionieren derzeit nicht, weil Decidim eine neue Funktion eingeführt hat und ein Warnfenster bei externen Links einblendet.
-  EDIT: auch mit Whitelist-Domains (z.B. stadt-zuerich.ch) funktionieren Redirects derzeit nicht.
-  Edit @Kagemaru: Ich konnte dieses Verhalten nicht nachstellen. Mit dem Whitelisten der vollen Domain scheint dies zu funktionieren. ACHTUNG: stadt-zuerich.ch und mitwirken.stadt-zuerich.ch sind unterschiedliche Domains und müssen beide eingetragen sein. (https://mitwirken.stadt-zuerich.ch/ funktioniert nicht, da es nur den Domainteil prüft.)
-  Edit @larsUE: @Kagemaru: Das Whitelisting funktioniert gut. Aber die automatischen Redirects per Konvention, wie @carlobeltrame hier umgesetzt hat, scheinen nicht zu laufen. Beispiel siehe hier: https://mitwirken.integ.stadt-zuerich.ch/processes/extern.

**Comment by carlobeltrame** [comment]
@larsUE ich konnte diese 3 Dinge flicken, war jeweils derselbe Fix für alle drei. Testbar auf Integration.

**Comment by bsantschi** [comment]
Hoi @lars, Carlo konnte es umsetzen und auf Integration deployen.

**Comment by larsUE** [comment]
Cool, danke! Process Redirects funktionieren super.
@carlobeltrame Könntest du beim Jump-Down noch etwas weiterspringen? Schön wäre, dass das Menü bündig zum oberen Seitenrand ist. Im Moment schauts so aus, auch wenn die Seite gegen unten noch mehr Platz hätte: 
<img width="1523" alt="Bildschirmfoto 2022-05-06 um 09 26 51" src="https://user-images.githubusercontent.com/60926257/167086688-d2261de3-7e15-413d-a097-1a8355b65fb7.png">

Beispiel hier: https://mitwirken.integ.stadt-zuerich.ch/processes/testprozess/f/181/budgets/8/projects

Beim Header Down gibts noch ein Konflikt mit dem allgegenwärtigen Banner, wenn es eingeschaltet ist. Ich löse das aber gleich wie auf der MeinQuartierPlattform und nehme das Banner einfach an den unteren Seitenrand. Da musst du nichts mehr unternehmen.

**Comment by carlobeltrame** [comment]
@larsUE klar, kann ich probieren. Das ist aber auf der Produktion auf decidim 0.24 auch schon so: https://mitwirken.stadt-zuerich.ch/processes/probstei/f/98/
Ich vermute dass das durch das Zusammenspiel des Scroll-Features und des slidenden Hauptmenüs entsteht.

**Comment by carlobeltrame** [comment]
Habe eine einfache Lösung gefunden. Werde diese dann bald mal noch auf Integration ausrollen, wenn wir noch mehr Fixes haben.

**Comment by larsUE** [comment]
Yeah, supernice!, danke!
