### ISSUE TITLE
Site Crash bei Schritten

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#242]
Die Seite crashed bei mir (und bei Werner) wenn auf der INTEG in diesem Prozess (https://mitwirken.integ.stadt-zuerich.ch/admin/participatory_processes/nina/steps) folgende Links angeklicked werden: 
![image001](https://user-images.githubusercontent.com/60926257/166706195-18936d74-a0e6-49a9-9a29-4947450f9b12.png)

**Comment by Kagemaru** [comment]
Hier waren die Daten des Schritts korrupt.
Das Feld `description` hatte einen Wert von `""` in der Datenbank.
Ich habe es zu `null` geändert und jetzt funktioniert es.
