### ISSUE TITLE
Site Crash bei Seiten-Komponente

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#243]
Die Seite crashed bei mir (und bei Werner) wenn auf der INTEG in diesem Prozess (https://mitwirken.integ.stadt-zuerich.ch/admin/participatory_processes/nina/steps) folgende Links angeklicked werden: 
![image001](https://user-images.githubusercontent.com/60926257/166706195-18936d74-a0e6-49a9-9a29-4947450f9b12.png)

**Comment by larsUE** [comment]
Es gibt noch zahlreiche weitere Crashes, ein Zusammenhang konnte ich bislang nicht erkennen (führe laufend nach), als 500-Fehler:

- [ ] https://mitwirken.integ.stadt-zuerich.ch/admin/participatory_process_groups/1/landing_page/edit
- [ ] https://github.com/puzzle/decidim-zuerich/issues/242
- [ ] https://github.com/puzzle/decidim-zuerich/issues/241
- [ ]

**Comment by larsUE** [comment]
Falls es wirklich wie angegeben mit einem crashenden Kommentarfeld zusammenhängt: Wir haben letzten Herbst ja mal noch Änderungen an der GID-Darstellung vorgenommen, nun gibt es da teilweise noch Probleme: https://github.com/puzzle/decidim-zuerich/issues/247

Nur als Vermutung, seit dann etwa funktionieren auch die Filter im Vorschlagsmodul nicht mehr richtig. Vielleicht hängt das ja alles irgendwie zusammen.

**Comment by Kagemaru** [comment]
@larsUE Auch hier war es anscheinend falsche Daten in der Datenbank. Die Page mit der ID 40 hatte `body=""`. Mit `body=nil` funktioniert es nun. Ich hoffe, dies ist kein oft auftretendes Problem.

**Comment by larsUE** [comment]
@Kagemaru Weisst du wieso diese body="" auftreten? Und die müssen wir wohl jedes mal einzeln flicken, der?
