### ISSUE TITLE
Prozess-Import bringt Rails zum Abstürzen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#244]
Wenn ich einen Mitwirkungsprozess mittels .json-File importieren möchte, wird dies durch die WAF geblockt. Dieses ist für uns sehr wichtig, wenn wir Prozesse von der INT auf die PROD kopieren.

Reproduce: 
Auf der INT einen Mitwirkungsprozess exportieren, und wieder importieren. (Bitte nicht zu viel testen, ansonsten füllt sich das Verzeichnis unnötigerweise)

**Comment by Kagemaru** [comment]
@larsUE 
Dieses Problem besteht beim Import, wenn Attachments an den Prozess angehängt sind.
Attachments können mit diesem Export nicht zwischen Installationen migriert werden,
deshalb muss beim Import die Checkbox `Import attachments` deaktiviert werden.

**Comment by larsUE** [comment]
Ach so, das macht eigentlich Sinn. Also ist "Import Attachments" nur dann möglich, wenn auf demselben Tenant ex- und importiert wird (z.B. ein Backup oder so).
