### ISSUE TITLE
Newsletter: Logo wird nicht geladen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#245]
Auf beiden Integrationsumgebungen werden in den Newslettern die Logos und Bilder derzeit nicht geladen, auch nicht im verschickten Mail:
<img width="644" alt="Bildschirmfoto 2022-05-05 um 10 31 57" src="https://user-images.githubusercontent.com/60926257/166887994-9db46d3f-e745-4a67-9f26-f428844e133b.png">
_[Case auf Mitwirken](https://mitwirken.integ.stadt-zuerich.ch/admin/newsletters/22), keine Logos und Bilder geladen_

**Nachforschungen**
Wenn ich auf «Auf der Website anzeigen» im Mail klicke erscheint folgendes (es ist ein 404-Errror):
<img width="732" alt="Bildschirmfoto 2022-05-05 um 10 34 02" src="https://user-images.githubusercontent.com/60926257/166888265-7f30f5e6-8167-4b5a-802d-2676e1ca04ce.png">

Wenn ich das iFrame der Newsletter-Vorschau analysiere, finde ich folgende Fehlermeldung:
<img width="1641" alt="Bildschirmfoto 2022-05-05 um 10 35 05" src="https://user-images.githubusercontent.com/60926257/166888425-c6df4a87-039a-462b-b5f7-00b945b0d2d2.png">

Lustigerweise, wenn ich aber den angezeigten Link selbst klicke, lande ich bei folgender Fehlermeldung:
<img width="1212" alt="Bildschirmfoto 2022-05-05 um 10 36 44" src="https://user-images.githubusercontent.com/60926257/166888706-f79d4751-b05f-4635-a4cf-eab13fae86f6.png">

**Comment by Kagemaru** [comment]
Die URLs die ausgeliefert werden für die Bilder scheinen abzulaufen. Das müssen wir bei uns anpassen, damit permanente URLs verwendet werden.

**Comment by Kagemaru** [comment]
Mit S3 hat das wenig zu tun. Es wäre der Rails/Decidim gewesen, die falsche Links herausgeben.
Aber ich kann hier entwarnen, der Link im Newsletter ist ok so. Er macht einen Redirect über Rails auf das Bild auf S3. Das ist das erwartete Verhalten.

Kannst du mal testen, ob alles so funktioniert, wie es soll?

**Comment by larsUE** [comment]
Ok, danke für die Erklärung. Ich erhalte den Newsletter auch wie gewünscht mit den Bildern. Somit ist nur die Vorschau defekt. -> Das können wir von mir aus auch erst nach dem Update flicken. Ich habe die Tags angepasst und die Ticket zurück ins ready verschoben.

**Comment by larsUE** [comment]
@Kagemaru und ich haben hier getestet und scheinbar ist dies ein Safari-spezifisches Caching-Problem. Der Newsletter Versand funktioniert ohne Probleme. Deshalb werden wir diesen Bug nicht flicken.
