### ISSUE TITLE
Partizipationsportal anpassen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#246]
Wir brauchen erweiterte Filter- und Sortierungsmöglichkeiten in unserer Prozessübersicht. Und zwar möchten wir die Prozessübersicht so ergänzen, dass wir über Abschnitte mit Titel verfügen (siehe Grafik unten), um die Prozesse nach Typ zu sortieren. Die Sortierung nach Prozesstyp erfolgt durch das Übernehmen der Funktion Organisationstyp / `Assembly type`, wie es bei den Organisationen bereits möglich ist. Dabei wird nun in der Aufführung der Prozesse nach Typ sortiert, und jedoch Typgruppe hat einen eigenen Titel, nämlich den der Typklasse. Bei einer Kombination mit den anderen Filtern (Themen & Gebiete), passen sich die Typen automatisch an. Leer Typengruppen werden verborgen.

<img width="588" alt="Bildschirmfoto 2022-05-06 um 16 19 59" src="https://user-images.githubusercontent.com/60926257/167151829-97a0a413-8e10-4c9f-aa6e-086af0a12b89.png">

**Konkrete To-do's**:

Paket A
1. Übernahme der `Assembly type` Funktion für Processes und Einbau der Konfigurierungsmöglichkeiten im Backend.
2. Anpassung der Prozessdarstellung, sodass automatisch nach Typen sortiert wird (wie bei den assemblies), jedoch mit Darstellung eine Titels zur jeweiligen Gruppe (H1)

Paket B
Prozesse per Karte verortbar machen und auf der Prozessübersichtsseite zuoberst darstellen.

**Comment by larsUE** [comment]
Zusätzlich als separate Funktion zu schätzen: Eine Verortung von Prozessen auf Karten, die im auf der Seite /processes zuoberst dargestellt wird.

**Comment by larsUE** [comment]
Mittlerweile wurde der 1. Punkt bereits für V0.27 entwickelt: https://github.com/decidim/decidim/pull/8583

**Comment by carlobeltrame** [comment]
Ich habe mir das mal im Detail angeschaut. Wir sitzen damit leider ein bisschen in der Klemme.

**Variante 1**: Wenn wir das Feature nur für Decidim Zürich von 0.27 zu 0.26 backporten, dann ist es immer noch der grösste Eingriff den wir bisher in Decidim gemacht haben. Das Feature umfasst 52 veränderte Dateien, während unsere bisherigen Anpassungen eher 2-3 Dateien berührt haben. Wir müssen all diese Dateien bei uns patchen (und beim späteren Decidim-Upgrade wieder allesamt entfernen), während decidim halt einfach die Originale aktualisieren kann. Zudem muss für dieses Feature die Datenbank verändert werden (die Types brauchen eine Tabelle, und die Processes müssen einen speicherbaren Type bekommen). Wenn ich das vorhole, dann muss ich beim späteren Upgrade auf 0.27 die Datenbankmigration (DB-Veränderungs-Code) von decidim wieder patchen, damits nicht auf die Nase fliegt wenn diese Änderungen bereits vorgeholt vorhanden sind.
**Geschätzter Aufwand: 3-4 PT**, plus erhöhte Komplexität bei einem späteren Upgrade auf Decidim 0.27

**Variante 2**: Wenn wir das Feature auf ähnliche Art einfach komplett neu implementieren (entweder bei uns im Projekt oder als Modul), dann könnte ich mir das Decidim-Feature als Vorbild nehmen, was die Neuimplementation eines solchen Features sicher beschleunigen würde. Durch die Grösse des Features wäre das aber dennoch ein gewisser Aufwand, und vor allem wäre dann der Migrationspfad sehr unklar, wenn wir mal auf Decidim 0.27 upgraden. Das heisst, wir müssten dann später nochmals Arbeit reinstecken um die Daten von unserem custom feature ins offizielle Decidim-Feature zu migrieren, oder um das offizielle Decidim-Feature "auszublenden".
**Geschätzter Aufwand: 3-4 PT**, plus stark erhöhte Komplexität bei einem späteren Upgrade auf Decidim 0.27

**Variante 3**: Ich könnte auch versuchen, direkt bei Decidim selber das Feature zu backporten. Damit würden wir uns keine Komplexität beim Upgrade auf 0.27 aufbürden. Ich bin mir allerdings unsicher ob sie überhaupt Backports für so grosse Features akzeptieren würden. Mit dieser Variante würden wir also riskieren, dass es dann abgelehnt oder verschoben wird und wir aufgrund des Zeitdrucks doch wieder auf eine der anderen beiden Varianten zurückgreifen müssen.
**Geschätzter Aufwand: 1-2 PT**, plus **Unsicherheit** ob diese Variante überhaupt klappen kann.

**Comment by larsUE** [comment]
Ja, das ist mir klar. Wir hatten ja auch gesagt, nicht mehr so schnell wechseln zu wollen. Ich mache mir weitere Gedanken und schaue das mit Werner an, sobald er aus den Ferien zurück ist.

@bsantschi für einen externen Auftrag haben wir dieses Jahr leider kein Budget mehr.

**Comment by larsUE** [comment]
@carlobeltrame : Was wäre denn der Aufwand für deine vorgeschlagene Lösung, sprich wenn wir die Kategorisierung durch die Prozessgruppen vornehmen würden, und diese dann ausgeklappt anzeigen würden? Wir finden das einen spannenden Ansatz! :)

**Comment by bsantschi** [comment]
Aufwandschätzung für Prozessgruppen alles automatisch aufklappen.

**Comment by carlobeltrame** [comment]
Aufwand: 1.5 PT

Tech Spec:
- Im Controller die `collection` nach ProcessGroups gruppiert zu Verfügung stellen. So werden die Filter direkt aktiv
- app/views/decidim/participatory_processes/participatory_processes/index.html.erb überschreiben und den Teil `#processes-grid` ersetzen durch custom Code
- Code soll gemäss Mockup (tbd) die Prozessgruppen als Übertitel anzeigen
- Übertitel ohne Inhalte (Prozessgruppen ohne Prozesse welche die Filterkriterien erfüllen) sollen ausgeblendet werden

**Comment by larsUE** [comment]
Zusätzlich noch: Falls eine Prozessgruppe eine Startseite hat (z.B. https://mitwirken.stadt-zuerich.ch/processes_groups/11), dann einen Button unterhalb der Prozesse anzeigen, der auf diese Startseite verweist. Hat die Prozessgruppe keine Startseite, Button entsprechend nicht anzeigen. Je nach Aufwand kann dies auch als Prio 2 angesehen werden.

**Comment by larsUE** [comment]
Hier ein erweiterter Mockup:
[Gescanntes Dokument.pdf](https://github.com/puzzle/decidim-zuerich/files/9927539/Gescanntes.Dokument.pdf)

Folgende Design Choices:

- [ ] Titel mit Anzeige der Anzahl Prozesse bestehen zu Filter umwandeln. Style wie hier: https://designsystem.stadt-zuerich.ch/current/?path=/story/components-chipselect--default Falls ich dazukomme arbeite ich hier was vor.
- [ ] Prozessgruppentitel jeweils als h1.section-heading


Falls die Prozessgruppe über eine Startseite verfügt:

- [ ] Titel verlinkt auf Prozessgruppestartseite
- [ ] Button nach den Prozessen rechtsbündig (und ausgefüllt) mit «Mehr Informationen», verlinkt auf Prozessgruppenstartseite

**Comment by larsUE** [comment]
To-Do 2. Prio: Lösung für Sortierung der Prozessgruppen finden.

**Comment by carlobeltrame** [comment]
Ich habe dieses Feature mal in einer ersten Version umgesetzt und auf Integration ausgerollt. Folgende Dinge sind noch zu klären:
- Ich habe es bisher nicht tenantspezifisch gemacht, weil wir dafür die [Tenant-Identifiers](https://github.com/stadtluzern/decidim-ocl/commit/5f39264a1373137f907d774e631b639d5fab0375) von Luzern / decidim.swiss erst noch nach Zürich übernehmen müssten. Es wird also gleichermassen bei meinquartier auftauchen, sobald dort Prozessgruppen eingesetzt werden.
- Es ist ja sehr gut möglich dass es auch Prozesse gibt die keine Prozessgruppe haben (z.B. beim meinquartier Tenant). Ich habe jetzt mal entschieden, dass diese Einzel-Prozesse unter den Prozessgruppen aufgelistet werden, und dass in dieser Liste von Einzel-Prozessen weder die Prozessgruppen noch die Prozesse die in einer Prozessgruppe sind auftauchen. Bitte melden falls das anders gehandhabt werden soll. Die Liste der hervorgehobenen Prozesse ist unverändert, es kann dort weiterhin auch ein Prozess aus einer Gruppe beworben werden.
- Die Filter nach Bereichen (scopes) und Bereichen (areas) tauchen wie mal mündlich besprochen nur bei der Liste von Einzel-Prozessen auf. Trotzdem habe ich es so eingerichtet dass diese Filter auch die Prozessgruppen und ihre enthaltenen Prozesse filtern. Falls das nicht gewünscht ist bitte melden.
- Ist eine Prozessgruppe leer (keine Prozesse darin, oder keine zum Filter passenden Prozesse darin), dann wird sie auch nicht angezeigt, egal ob sie eine Landing Page hat oder nicht.

**Comment by larsUE** [comment]
Das ist bereits mega cool, vielen Dank @carlobeltrame ! Zu deinen Punkten

- Wir müssen es bei uns nicht tenant-spezifisch machen, weil meinQuartier keine Prozesse durchführt (und dies auch nicht geplant ist). Ansonsten können wir das später noch nachholen.
- Das mit den Einzelprozessdarstellung finde ich super gelöst.
- Mit den anderen Punkten bin ich einverstanden.

Aus Stylesicht habe ich folgendes gleich geändert in decidim awesome:
- [ ] Underlines in den headingsentfernt (gleich für alle section headings: 
`.section-heading a {
  text-decoration: none;
}`

Ich habs mal getestet und seh noch folgende to-do's:

- [ ] Klasse vom "Mehr Informationen" button ändern zu `button button--sc pull-right` (ohne hollow)
- [ ] Auf Mobile (getestet auf Safari Mac und iPhone) werden die Titel noch vom Button in den Rand geschoben (siehe Bild). Der in .section-heading definierte margin-top greift nicht auf den button. Kannst du die "column", wo der button drin ist, einzeln ansteuerbar machen und einstellen, dass die in .section-heading definierten Abständen ab Unterseite des Buttons greifen (im Moment agreifen sie ab Unterseite der Kacheln, deshalb schiebt der button den Text weg.

![Bildschirm­foto 2022-11-15 um 07 40 52](https://user-images.githubusercontent.com/60926257/201846548-01630beb-26f1-4e6f-ab00-97d30f3fa07e.png)

- [ ] Wenn ich die Filter anklicke, kommt im Moment nur "Ergebnisse werden geladen", ohne dass sie geladen werden. Wenn ich die Seite neu lade, werden die Resultate angezeigt.
![Bildschirm­foto 2022-11-15 um 07 57 41](https://user-images.githubusercontent.com/60926257/201850863-db1d2a9a-1cbf-4859-baa9-c2e4e936b990.png)

- [ ] Können wir die Filter ganz zuoberst haben (noch vor den hervorgehobenen Mitwirkungsprozessen), ohne Titel?

**Comment by larsUE** [comment]
Noch ein Nachtrag: Weisst du, wie die Prozessgruppen sortier werden in der Ansicht?

**Comment by larsUE** [comment]
Sortierung der Prozessgruppen: Am liebsten auch ein Feld für Weight bei den Prozessgruppeneinstellung einfügen und dann Prozessgruppen nach Weight sortieren. Das ist aber wohl einiges an Aufwand und ist nicht tragisch, wenn du das nicht für den Release morgen schaffst.

**Comment by larsUE** [comment]
Notizen für mich zum Prod-Release:

- [ ] Prozessgruppen erstellen, wie von Werner gewünscht
- [ ] CSS Styles für Chip Select übertragen

**Comment by larsUE** [comment]
@carlobeltrame und noch was letztes: kannst du für die Chips die .section-heading Klasse entfernen und eine eigene Klasse/ID anlegen? Dann kann ich die Abstände noch etwas customizen.

**Comment by carlobeltrame** [comment]
@larsUE könnte ich, aber da müsste ich noch mehr von Decidim überschreiben. Du kannst stattdessen einen genaueren Selektor verwenden:
* `.order-by__text.section-heading` um die Styles (z.B. Margins) nur dieses spezifischen Section-Headings anzupassen
* `.order-by__text .order-by__tabs` für das Rechteck um alle Chips und "Anzeigen:" Text herum
* `.order-by__text .order-by__tab` für die einzelnen Chips
* `.order-by__text .order-by__tab:first-of-type` für den ersten Chip

Achtung: Abstände (Spaces, Leerzeichen) sind wichtig in diesen Selektoren. Beim ersten Selektor hats bewusst keinen Abstand drin, bei den anderen hingegen bewusst schon.

**Comment by larsUE** [comment]
@carlobeltrame Eben auf der PROD aufgefallen: Die Scopes & Areas filtern auch noch nicht richtig (gleiches Verhalten bei bei den Chips, bevor du es geflickt hast. Wenn ich einen Scope auswähle, gibt es keinen automatischen Refresh, wenn ich jedoch die Seite neu lade wird der Scope angewandt. Kannst du das noch fixen?

**Comment by bsantschi** [comment]
- Counter bitte flicken
- Rest für den Moment pausieren

**Comment by carlobeltrame** [comment]
@larsUE counters sind auf Integration angepasst.
