### ISSUE TITLE
GID-Fehler bei Hashtags in den Vorschlägen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#247]
GIDs werden teilweise als ganze Links statt nur als Hashtags dargestellt

**Comment by carlobeltrame** [comment]
Hast du hier ein Beispiel? Screenshot oder Link? Wo ist "teilweise"?

**Comment by larsUE** [comment]
Whuups, das ging beim Copy-Pasten verloren: https://mitwirken.integ.stadt-zuerich.ch/processes/testlars/f/4/proposals/235

Beispielsweise in diesem Prozess, sobald Hashtags hinzugefügt werden

**Comment by Kagemaru** [comment]
Wir haben das vor 0.26 mal gefixt. Jetzt ist ein anderer Fix in 0.26 eingebaut. Dieser Fix macht unseren Fix kaputt... und das macht die Hashtags kaputt :grin:

**Comment by larsUE** [comment]
Cool, thanks!
