### ISSUE TITLE
Swisstopo-Karte auf PROD verschwunden

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#252]
Auf meinquartier.zuerich (PROD) erscheinen nur in der "Veranstaltungsübersicht" siehe Screenshot plötzlich keine Swisstopo-Karten mehr. Ist da etwas schiefgegangen im Kontext der Anpassung auf die städtischen Karten? Auf der Startseite sowie Veranstaltungsübersicht einzelner Organisationen wird die Swisstopo-Karte noch angezeigt.

![Screenshot 2022-05-12 at 16 00 39](https://user-images.githubusercontent.com/75796635/168093498-a8531969-2f20-4694-a3a3-61d128d1dd93.png)

**Comment by carlobeltrame** [comment]
Grund war, dass bei dieser Veranstaltung: https://meinquartier.zuerich/assemblies/kreisflohmi/f/122/meetings/90 die Koordinaten 52.404/13.447 eingetragen sind. Das kommt daher dass der OpenStreetMaps Geocoder als erstes Resultat bei der Adresse "Kreis 3" diesen Ort in Deutschland liefert: https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=495150401&class=landuse

Als Fix habe ich jetzt mal manuell die Koordinaten von Wiedikon eingetragen. In Zukunft könnten wir wie es bereits in Luzern gemacht wird die Suchresultate des Geocoders auf ein Koordinatenrechteck limitieren. Oder man könnte auch die Nutzenden schulen und ihnen mitteilen, dass ins Feld "Adresse" nur konkrete Adressen statt allgemeine Orte wie "Kreis 3" eingetragen werden sollen. Es wird ja auf der Karte sowieso nicht eine ganze Fläche (Kreis 3) markiert, sondern ein ganz spezifischer Ort.

**Comment by innosmith** [comment]
Besten Dank @carlobeltrame ! Wir besprechen die Anpassung analog Luzern, um zukünftig solche Fälle zu verhindern.
