### ISSUE TITLE
Umfrage: Aktualisierung (und Bild in Textfeld)

### ISSUE THREAD

**Issue by Sabethtoedtli** [puzzle/decidim-zuerich#253]
Beim aktualisieren einer Umfrage im Testprozess kommt die Nachricht: <Uups! Der Zugriff auf diese Seite ist dir nicht gestattet>. 

https://mitwirken.integ.stadt-zuerich.ch/processes/nina/f/256/
(passiert bei Nina und Werner)

Ausserdem gelingt es nicht, Bilder in Textfelder zu ziehen.

**Comment by Sabethtoedtli** [comment]
Habe eine neue Umfrage kreiert namens "Umfrage NEU"  (im Admin Testprozess auf INTEG). 
Das hat problemlos geklappt, und ich konnte sie anschliessend auch ändern, an der Umfrage teilnehmen, sie nochmals ändern etc...

Was aber gar nicht mehr klappt ist der Zugriff auf vorher schon bestehende Umfragen. Schon wenn ich im Backend-Menu auf die Komponente "Umfrage" klicke kommt die Meldung " Uups! Auf dem Server ist ein Fehler aufgetreten.

**Comment by carlobeltrame** [comment]
Aktueller Stand der Untersuchungen: Es sind zwei separate Probleme.

Dass Prozess-Admins keine Bilder hochladen können wurde auch in #256 gemeldet, und wird möglicherweise in der nächsten Version von Decidim Awesome [behoben](https://github.com/Platoniq/decidim-module-decidim_awesome/issues/112). Ich habe probiert, diese neue Version von Decidim Awesome bereits vorab zu installieren, aber es hat mehr kaputt gemacht als gefixt, die Texteditoren haben danach gar nicht mehr funktioniert. Probiere es später nochmals, falls es ein Fehler auf meiner Seite war.

Das andere Problem mit dem verweigerten Zugriff kann ich lokal nicht nachstellen, nicht einmal wenn ich den Datenbankstand der Testumgebung bei mir lokal einspiele und es mit Ninas Account probiere: Es funktioniert lokal alles korrekt. Das macht das Debugging ziemlich schwierig. Auf der Testumgebung bekomme ich mit einem Plattform-Admin ein anderes Problem als ihr beschreibt, nachdem ich auf Speichern klicke bekomme ich wieder das Formular mit Fehlern zurück, und alle Umfrage-Fragen gehen verloren. Workaround für dieses Problem ist aber, einfach eine neue Umfrage zu erstellen. Gemäss Sabeth funktioniert es bei frischen Umfragen korrekt.

**Comment by bsantschi** [comment]
- Betrifft möglicherweise alle Umfragen, die vor dem Upgrade erstellt wurden.
- Sabeth klärt noch mit Werner, ob es auf PROD überhaupt Umfragen gibt

**Comment by carlobeltrame** [comment]
Decidim Awesome ist auf der Integrationsumgebung geupdatet. Bitte den Bild-Upload erneut testen.

Den Fehler "Uups! Der Zugriff auf diese Seite ist dir nicht gestattet" beim Bearbeiten der Umfrage konnte ich inzwischen auf der Testumgebung reproduzieren, obwohl wir soweit ich weiss nichts geändert hatten. Bitte noch abklären wie kritisch dieses Problem ist und wie hoch ich das einpriorisieren soll.

> https://mitwirken.integ.stadt-zuerich.ch/admin/participatory_processes/testlars/components/11/manage/

Das ist ein nochmals komplett separater Fehler. @larsUE machst du ein separates Issue dafür?

**Comment by larsUE** [comment]
@Kagemaru und @carlobeltrame klären noch ab, ob dies ein WAF-Issue ist.

**Comment by carlobeltrame** [comment]
Das von Nina und Werner gemeldete Problem ist tatsächlich ein WAF-Problem und tritt in Umfragen auf die sehr viele Fragen enthalten. Die WAF blockiert Anfragen mit zu vielen Parametern (zu viele Textfelder / Einstellungen aufs Mal). Thomas macht sich an einen Fix.

**Comment by larsUE** [comment]
Cool, ich habs mal auf "In Progress" verschoben.

**Comment by carlobeltrame** [comment]
WAF wurde aktualisiert, und bei mir funktionierts jetzt. Bitte erneut testen oder Werner oder Nina mitteilen dass sie testen sollen @larsUE

**Comment by larsUE** [comment]
Bestens! Bei mir funktioniert es auch wieder :)
