### ISSUE TITLE
Adress-Suche geografisch einschränken

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#254]
Wir möchten die möglichen gültigen Adressen bei der Adress-Suche einschränken auf die Stadt Zürich. Siehe Screenshots die Start X/Y sowie End X/Y Koordinaten. Ich gehe davon aus, dass diese Einschränkung für alle Tenants gilt.

![Screenshot 2022-05-16 at 11 15 38](https://user-images.githubusercontent.com/75796635/168686061-3db27fc4-db11-49c8-9652-7048f86873d2.png)

![Screenshot 2022-05-16 at 11 16 24](https://user-images.githubusercontent.com/75796635/168686097-97023941-de77-483c-92ea-c39703241d92.png)

**Comment by carlobeltrame** [comment]
Das ist jetzt zusammen mit der Karte auf der Integration verfügbar.

Bei der Implementation der Karten ist aufgefallen, dass einzelne Meetings bereits zuvor ausserhalb des Kantonsgebiets eingeordnet wurden. Diese musste ich beim Anzeigen der Karte noch herausfiltern, sonst wäre die Karte auf https://test.meinquartier.zuerich/meetings nur grau geblieben (wegen fehlendem Kartenmaterial auf der nötigen Zoom-Stufe).

@innosmith soll ich noch herausfinden welche Meetings das konkret sind und diesen allenfalls den Standort korrigieren oder entfernen? Oder setzt ihr darauf dass die falsch eingeordneten Veranstaltungen irgendwann durch sind und ab dann alle Veranstaltungen normal als Marker auf der Karte auftauchen?

**Comment by larsUE** [comment]
Falls es nur vergangene INT-Veranstaltungen betrifft, würde hier keine Zeit verschwenden. Solange nichts kaputt geht mit "falschem" Standort spielt das keine Rolle und kann bei Bedarf dann manuell angepasst werden.
