### ISSUE TITLE
Vorstandsmitglieder bei einer Org nicht angezeigt?

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#257]
Vermutlich ein Bedienerfehler: ich verstehe nicht, weshalb bei der Organisation https://test.meinquartier.zuerich/assemblies/Drehscheibe-Altstetten-Gruenau die Vorstandsmitglieder siehe Screenshot nicht als eigener Reiter "Vorstand" direkt nach "Die Organisation" angezeigt werden. Bei der Organisation https://test.meinquartier.zuerich/assemblies/testax/members funktioniert dies einwandfrei. Any ideas?

![Screenshot 2022-05-20 at 17 54 39](https://user-images.githubusercontent.com/75796635/169566243-bba37aa3-ed97-4129-b5ec-9ab69c9aa7be.png)

**Comment by carlobeltrame** [comment]
Auf dieser Vorstands-Ansicht werden nur Vorstandsmitglieder angezeigt die nicht zurückgetreten sind ("Aufgegeben Datum" leer oder in der Zukunft).
Bei der Drehscheibe ist das Rücktrittsdatum beider Vorstandsmitglieder am 18. Mai eingetragen, bei deiner Testorganisation ist das Rücktrittsdatum bei beiden Vorstandsmitgliedern leer.
