### ISSUE TITLE
Organisationsimport funktioniert nicht

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#258]
Beim "Import" einer Organisation auf der Quartierplattform PROD mittels JSON generiert auf der INT-Plattform erfolgt die Fehlermeldung "Uups! Auf dem Server ist ein Fehler aufgetreten."

Liegt dies ev.:
- WAF?
- Inkompatibles Datenformat zwischen INT (Decidim v0.26) und PROD?
- Anwendungsfehler?

Anbei noch der Screenshot, wie ich die Konfiguration für den Import gemacht habe, bevor die Fehlermeldung geworfen wird.

<img width="1491" alt="Screenshot 2022-05-24 at 22 46 34" src="https://user-images.githubusercontent.com/75796635/170129684-9569a4c6-8848-432b-837b-1b25ebeae368.png">

**Comment by larsUE** [comment]
Wurde schon gelöst, siehe #244

**Comment by innosmith** [comment]
@larsUE : jetzt müsste nur PROD wieder laufen, dann kann ich es testen. Danke für den Tipp!

**Comment by innosmith** [comment]
Ohne Attachments funktioniert es. Der Original-Scope sowie geographische Filter werden nicht importiert. Das liegt ev. auch daran, dass diese Informationen plattformweit gelten resp. die ID's auf INT und PROD nicht identisch sind. So wurde aus "Quartierleben" auf INT "Alter" auf PROD.
