### ISSUE TITLE
Angenommene EInladungen stimmen nicht

### ISSUE THREAD

**Issue by TSydekum** [puzzle/decidim-zuerich#26]
https://pitc-decidim-zuerich-int.ocp.puzzle.ch/admin/participatory_processes/feedback/participatory_space_private_users
Die meisten User wurden diese Woche erst hinzugefügt und zumindest einzelne (Besp. Marianne Bickel) waren schon drin. Dies wird in der Admin Konsole nicht wiederspiegelt.  Es sieht so aus wie wenn keiner der User die einladung akzeptiert hätte. 
Einzig mein Testuser (Hans Muster) hat am Montag noch funktioniert.

**Comment by Kagemaru** [comment]
Ich habe dies mal mit 2 Adressen nachgestellt und folgende Erkentnisse erhalten:

- Wenn man bereits eingeloggt ist, wird die Registrierung abgebrochen und es wird nicht im Admin Interface als akzeptiert angezeigt
- Wenn man bereits einen Account hat und dieser eingeladen wird, muss man einen Teil der Registrierung erneut ausfüllen, damit es als akzeptiert angezeigt wird.

Ansonsten hat es bei mir funktioniert wie ich es erwartet hatte.

**Comment by bsantschi** [comment]
@TSydekum kannst du mit Decidim und ihrem Prozess so leben oder wünscht du, dass wir das umbauen? Wäre ein grosser Eingriff in Decidim.
