### ISSUE TITLE
Gefundene Veranstaltungsadresse wird nicht angezeigt

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#268]
Die Veranstaltung https://test.meinquartier.zuerich/assemblies/qv-altstetten/f/285/meetings/75 findet am Lindenplatz in Zürich statt. Für diese Adresse werden mehrere Matches bei OpenStreetMap gefunden, wenn man die Adresse im Backend eingibt. Wählt man einen passenden Vorschlag aus, wird bei dieser Veranstaltung jedoch keine Stecknadel auf der Karte angezeigt. Andere Adressen wie Bahnhofstrasse funktionieren auch nicht. Ist dies ein Anwendungsfehler, fehlende Koordinaten oder was könnte sonst die Ursache sein?

**Comment by larsUE** [comment]
bereits unter #267 erfasst.
