### ISSUE TITLE
Veranstaltungen werden falsch sortiert

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#270]
Veranstaltungen werden in der Veranstaltungskomponente falsch sortiert (späteste zuerst). 

Bsp. Mitwirken: https://mitwirken.stadt-zuerich.ch/processes/stadtidee/f/19/
Bsp. MeinQuartier: https://meinquartier.zuerich/assemblies/qvwitikon/f/89/

**Comment by Kagemaru** [comment]
Wurde schon letzten Donnerstag gefixt, wie per Whatsapp geschrieben.

**Comment by larsUE** [comment]
Yes, danke! Getestet hab ich's auch :-)
