### ISSUE TITLE
Umfrage auf Prod wird durch WAF geblockt

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#272]
Dieser Umfrage kann nichts mehr hinzugefügt werden (Frage oder Trennzeichen o.ä.) da sie gleich von der WAF geblockt wird. Kannst ihr bitte die Entity Size erhöhen?

https://mitwirken.stadt-zuerich.ch/processes/wohnformen-im-alter?participatory_process_slug=wohnformen-im-alter

**Comment by Kagemaru** [comment]
Ich habe die WAF aktualisiert. Muss aber am nächsten Stand-up noch angeschaut werden.

**Comment by Kagemaru** [comment]
Die Länge der Zeichen ist in ein weiteres Limit gelaufen. Dies habe ich nun zusätzlich zur Datenmenge erhöht.
