### ISSUE TITLE
Unordered List fügt zahlreiche Abstände hinzu

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#274]
Wenn ich eine unordered list erstelle, dann werden beim erneuten Aufrufen der Seite vor und nach dem jeweiligen List Element je ein zusätzliche Abstand eingefügt. Das ist sehr umständlich beim arbeiten.

Nachzustellen hier: https://mitwirken.stadt-zuerich.ch/admin/participatory_processes/wohnformen-im-alter/components/165/manage/meetings/150/edit
Und hier: https://mitwirken.stadt-zuerich.ch/processes/wohnformen-im-alter/f/165/meetings/179

Ich habe verschiedene Text probiert, auch komplett unformatierten Text, und das Problem tritt auf, sobald ich eine Liste in dieser Veranstaltung erstelle. Komischerweise tritt es bis anhin nur in diesem Prozess auf.

**Text frontend nach Erstveröffentlichung**
<img width="900" alt="Bildschirmfoto 2022-06-23 um 14 51 12" src="https://user-images.githubusercontent.com/60926257/175302741-ebffef21-4bdb-40d7-8669-84211d6ca623.png">

**Backend, sobald ich den Text bearbeiten möchte**
<img width="1218" alt="Bildschirmfoto 2022-06-23 um 14 52 03" src="https://user-images.githubusercontent.com/60926257/175302897-ecd6b417-7f84-46bf-8519-4e606518865a.png">

Bei erneuter Speicherung werden auch die neuen Elements übernommen.

**Comment by carlobeltrame** [comment]
Hast du noch einen anderen Ort wo dasselbe Problem trotz Präsenz einer Aufzählung nicht auftritt?
Beim Speichern und wieder Abrufen sieht eigentlich alles gut aus. Ich vermute daher einen Bug im Rich Text Editor, ein Vergleich mit einem funktionierenden Text könnte aber helfen.

**Comment by larsUE** [comment]
Ich muss präzisieren, der Bug tritt überall bei Veranstaltungen auf. Andere Listen, z.B. hier: https://mitwirken.stadt-zuerich.ch/admin/participatory_processes/stadtidee/components/107/manage/posts/25/edit
sind nicht betroffen.

**Comment by larsUE** [comment]
Ich glaube, daran wird derzeit gearbeitet: https://github.com/decidim/decidim/issues/9763
