### ISSUE TITLE
Anbindung OIDC/Mein Konto

### ISSUE THREAD

**Issue by bsantschi** [puzzle/decidim-zuerich#28]
- benötigt möglicherweise Firewall Anpassungen beim OIZ

**Comment by larsUE** [comment]
Zum Thema SMS-Verfikation @maximilianstern im Issue #41 

> Hello Zusammen, zur Info: "Mein Konto" bietet bereits zwei Sicherheitsstufen: Einmal nur eMail und einmal mit SMS-Verifizierung. Wichtig wäre also, dass Decidim dies sieht... ich weiss nicht genau, wie sich das lösen lässt...

**Comment by carlobeltrame** [comment]
> Zum Thema SMS-Verfikation @maximilianstern im Issue #41
> 
> > Hello Zusammen, zur Info: "Mein Konto" bietet bereits zwei Sicherheitsstufen: Einmal nur eMail und einmal mit SMS-Verifizierung. Wichtig wäre also, dass Decidim dies sieht... ich weiss nicht genau, wie sich das lösen lässt...

Hm das ist leider nicht ganz so einfach. Möglicherweise kann Mein Konto diese Information mitliefern, aber in decidim können wir das nur mit Zusatzaufwand verarbeiten.

Für die eingebaute Verifikation speichert decidim einen Fingerprint der verifizierten Telefonnummer in der Datenbank. Der Fingerprint (Hash) ist für jede Telefonnummer anders, aber die Nummer kann daraus nicht mehr wieder reproduziert werden. Das wird aus Datenschutzgründen so gemacht, nur so kann decidim überprüfen ob eine gegeben Telefonnummer schon mal für einen anderen Account verwendet wurde, ohne sich die Telefonnummern in Klartext zu merken.

Falls nun die SMS-Verifikation extern bei Mein Konto gemacht wird, müsste Mein Konto die verifizierte Nummer an decidim mitliefern (das kann es), und wir müssten quasi eine erfolgreiche Verifikation in decidim "faken". Ziemlich unschön, einen Sicherheitsmechanismus auf politisch relevanter Software so zu umgehen.

Alternativ könnten wir eine weitere Verifikations-Methode programmieren, die zusätzlich zur decidim-eigenen SMS-Verifikation zu Verfügung steht. Diese könnten wir dann je nach Information von Mein Konto automatisch als verifiziert markieren. Aber auch das bedeutet Aufwand, die Verifikationsmethode zu programmieren.

**Comment by carlobeltrame** [comment]
Ich habs hingekriegt mit der Mein Konto Anbindung. Auf Integration ist es aber nicht testbar, da der DNS-Eintrag mitwirken.integ.stadt-zuerich.ch noch immer nicht stimmt. Ich habe das daher gleich auf die Produktion deployt damit du es dort schon mal ausprobieren kannst. Sobald die Domain korrekt eingestellt ist kann man es dann auch auf der Integration mit beliebig vielen Fake-Mein-Konto-Accounts testen.

**Comment by larsUE** [comment]
Also, ich kriege folgendes Verhalten: 

- Erster Versuch: Registrierung via MeinKonto: Weiterlitung auf die städtische Login Seite klappt, Anmeldung klappt, beim Redirect zurück auf Decidim kommt es nachher zu langen Wartezeiten und dann erscheint die "Auf unseren Servern ist ein Fehler aufgetreten Seite"
- Danach mehrmaliges Versuchen von registrieren und anmelden, jedes Mal mit Timeout.
- Plötzlich geht die Anmeldung, mit Redirect zurück auf die Seite und ohne Timeout (und Erfolgsbestätigung auf Decidim)
- Ich kann mich nun sowohl anmelden als auch erneut registrieren und ich werde immer in mein decidim Konto eingeloggt (ohne Umweg über die städtische Login-Page).
- Konto gelöscht und neuangemeldet: Neues Konto wird automatisch erstellt, ohne "Ausflug" auf die städtische Loginpage

Die Erfolgsmeldung nach dem Login lautet wie gemäss Bild: Könntest du sie noch per Term-Customizer anpassbar machen? Oder ändern in: Sie haben sich erfolgreich mit «Mein Konto» angemeldet.

<img width="647" alt="Bildschirmfoto 2021-04-07 um 15 51 17" src="https://user-images.githubusercontent.com/60926257/113878897-4eff5680-97ba-11eb-85e2-7104266636ef.png">

Alles gut! Die Timeouts müssen wir ein bisschen im Auge behalten und dann genauer testen, wann sie auftreten (oder vielleicht stabilisiert sich das ja auch).

**Comment by carlobeltrame** [comment]
Der Translation-Key ist folgender: `devise.omniauth_callbacks.success`. Dieser enthält einen Platzhalter `%{kind}`, in den je nach OAuth-Provider z.B. Facebook, Google, oder Oidc (so heisst die Mein Konto Anbindung intern) eingesetzt wird. Solange ihr nur Mein Konto nutzt kannst du diese Übersetzung problemlos mit einem Satz deiner Wahl ohne Platzhalter überschreiben. Wenn wir mal mehrere OAuth / OIDC Provider gleichzeitig haben könnte ich noch nachforschen, ob ich es hinkriege dass `%{kind}` mit "Mein Konto" ersetzt wird, aber für den Moment sollte es auch ohne gehen.

**Comment by carlobeltrame** [comment]
Die Timeouts kann ich mir gerade noch nicht erklären, aber ja, schauen wir mal wie sich das entwickelt.

**Comment by larsUE** [comment]
Super, danke! Ich konnte es ohne Probleme anpassen.  Mit den Timeouts hatte ich auch keine Probleme mehr und es funktioniert alles schnell. Ich close hier mal.
