### ISSUE TITLE
Veranstaltungsdetails schliessen führt erneut zu /meetings#close

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#283]
Auf PROD sowie INT haben wir erneut den Fehler, dass sobald in der Veranstaltungsübersicht Details zu einer Veranstaltung auf der Kartenübersicht geschlossen werden, der Filter auch alte Veranstaltungen lädt mit dem Suffix #close in der URL. Analog auch auf anderen Kartenausschnitten mit Veranstaltungen wie z.B. beim QV Witikon.

**Comment by carlobeltrame** [comment]
Das tritt nicht "erneut" sondern immer noch auf. Wir hatten das bisher erst in Luzern gefixt: https://github.com/stadtluzern/decidim-ocl/commit/31a1b6eb9f60f39670444391a3457617e3100ddc
Ich habe den Fix jetzt auf der Zürcher Integration noch nachgeholt. Für ein Produktivdeployment desselben bräuchte ich einen Termin von dir, wenn das soweit funktioniert auf der Testumgebung.

**Comment by innosmith** [comment]
Funktioniert, besten Dank @carlobeltrame
