### ISSUE TITLE
Bildergrösse anpassen führt zu Server-Fehler

### ISSUE THREAD

**Issue by innosmith** [puzzle/decidim-zuerich#285]
Zumindest auf MeinQuartier führen folgende Use Cases zum Fehler gemäss Attachment:
- Bild hinzufügen und gleichzeitig resizen
- Bild nachträglich resizen

Normal funktioniert:
- Bild ohne Resizing hinzufügen

Getestet als Plattform-Admin mit Processes sowie Assemblies, dasselbe Fehlverhalten.

<img width="1667" alt="Screenshot 2022-07-28 at 11 53 47" src="https://user-images.githubusercontent.com/75796635/181478957-8183134e-cd56-46ca-8449-dbd35d3917a0.png">

**Comment by innosmith** [comment]
Die beschriebenen Use Cases des Resizings funktionieren noch nicht. Bitte prüfen @Kagemaru, merci.

**Comment by larsUE** [comment]
Kann dies auch auf der mitwirken-INT bestätigen

**Comment by Kagemaru** [comment]
Dies war ein neuer Fehler auf der WAF. Ich habe es gleich auf allen Plattformen ausgerollt. INT & PROD

**Comment by innosmith** [comment]
Bestens @Kagemaru , es funktioniert!
