### ISSUE TITLE
Reply-To Adressen stimmen bei der Multitenant nicht mehr

### ISSUE THREAD

**Issue by bsantschi** [puzzle/decidim-zuerich#287]
Seit der Migration lautet die „Reply-To“ Adresse auf Mails info@puzzle.ch statt mitwirken.kontakt@zuerich.ch

Bei der Quartierplattform gleich: Bitte auf info@meinquartier.ch anpassen.

Könntest du das anpassen?

Danke und liebe Grüsse,
Lars

**Comment by Kagemaru** [comment]
Ich habe das nun so gelöst, dass man es mit dem TermCustomizer anpassen kann.
Der Key dazu ist: `decidim_zuerich.reply_to`
Ich muss es noch auf INT deployen

**Comment by larsUE** [comment]
Das funktioniert irgendwie noch nicht @Kagemaru 
Key ist ersetzt & cache geleert, aber die reply-to Adresse ist stets info@puzzle.ch
<img width="1393" alt="Bildschirmfoto 2022-08-16 um 08 41 06" src="https://user-images.githubusercontent.com/60926257/184814274-aa4808be-9cac-4220-945a-2729680de6cd.png">

**Comment by larsUE** [comment]
Beobachtungen auf test.meinquartier.zuerich

Der Daten-Export zeigt die richtige Reply-to Adresse an. Wenn ich mich jedoch [hier](https://test.meinquartier.zuerich/admin/assemblies/testmqz/user_roles) zum Organisations-Admin mache, kommt immer noch info@puzzle.ch als Adresse.

**Comment by larsUE** [comment]
<img width="742" alt="Bildschirmfoto 2022-09-04 um 13 39 35" src="https://user-images.githubusercontent.com/60926257/188311435-e943c5ba-c904-4344-83fd-b0e9d6c31a5f.png">

Bei der Begrüssungsmail kommt auch noch Info@puzzle.ch

Allenfalls hat das auch noch was mit #96 zu tun.
