### ISSUE TITLE
Unprocessable Entity bei File-Upload

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#288]
Es kamen in den Ferien einige Rückmeldungen, dass beim File-Upload in einer Umfrage immernoch der "Unprocessable Entity" Bug auftritt, Beispielsweise in dieser Umfrage: 
[https://mitwirken.stadt-zuerich.ch/processes/stadtidee/f/82/](https://mitwirken.stadt-zuerich.ch/processes/stadtidee/f/82/)

Celia hat mich gestern darauf hingewiesen, dass beim Abschicken der Schlussberichte diese Fehlermeldung kommt.
 
![image](https://user-images.githubusercontent.com/60926257/183584353-81805bbe-a673-49d1-8305-8d3969eb9255.jpeg)

 
Die Schlussberichte kommen im Hintergrund auch nicht an, das habe ich kurz kontrolliert. Bei mir hat es jedoch geklappt, ich konnte den Fehler noch nicht nachstellen. Ich versuche mal, an die Originaldokumente zu kommen.

**Comment by larsUE** [comment]
@Kagemaru gibt es hier Updates?

**Comment by Kagemaru** [comment]
Ich habe letzte Woche mal die CPU Limits des Webservers hochgeschraubt, da dieser einige Male in einen Engpass lief. Anscheinend hat dies noch keine Verbesserung gebracht.
Ich bin mit unserem Nginx Profi am Schauen, was es sonst noch sein könnte.

**Comment by larsUE** [comment]
Update heute: Im Moment kann ich in keinem Textfeld ein Bild hochladen, immer kommt der Unprocessable entity. File Upload via Backend läuft, aber wenn ich auf die Seite zugreifen möchte kommt ein 500er. Beispiel hier: https://mitwirken.integ.stadt-zuerich.ch/processes/testprozess/f/183/results/4

Das ist also wirklich sehr dringend.

**Comment by larsUE** [comment]
> Bei meinen Versuchen mit den Bildern ist mir aufgefallen, dass es nicht um die Filegrösse geht.
> 
> Dann ist mir dieser Fehler eingefallen: https://github.com/stadtluzern/decidim-ocl/issues/28
> 
> Kannst du prüfen, ob deine Bilder eine zu hohe Auflösung haben?
> 
> LG Thomas

**Comment by larsUE** [comment]
Uuh, heisse Spur.

Tests: 
PNG: 1400 x 900 -> funktioniert
JPG: 1200 x 860 -> funktioniert
PNG: 1500 x 1600 -> funktioniert
JPG: 1250 x 1530 -> funktioniert nicht
PNG & JPG: : 1920 x 2022 -> funktioniert nicht

Das könnte also sehr gut der von dir erwähnte Bug sein. Wieso löst dass denn aber hier andere Fehlermeldungen aus? Gerne mal den Fix übernehmen.

Übrigens, ich finde es sehr ungünstig, dass 4000*3000px  Bilder nicht funktionieren. Das sind ja nun wirklich Standard-Handy-Kamera-Dimensionen. Lässt sich am hardgecodeten Code nichts ändern? Bzw. was für Implikationen hätte das?

**Comment by larsUE** [comment]
@Kagemaru: wobei, der Fehler schlägt ja auch an, wenn das Bild unter 3'840 px ist.

**Comment by Kagemaru** [comment]
> Das ist also wirklich sehr dringend.
Sorry, das hatte ich übersehen. Ich überprüfe dies als Nächstes.
Danach teste ich deine Bilder aus der Mail, um weitere Probleme herauszufinden.

> wobei, der Fehler schlägt ja auch an, wenn das Bild unter 3'840 px ist.
Es ist einer der Gründe, warum es fehlschlägt und es war bei mir der häufigste. Jetzt weiss ich worauf ich achten muss beim Testbilder auswählen.

**Comment by Kagemaru** [comment]
Die Unprozessable Entity bei den Formularen wird wahrscheinlich durch das Authenticity Token ausgelöst.

Wir versuchen nun über eine bessere Dokumentation die Leute zu informieren.

Dazu muss ich allerdings einen Pullrequest auf dem WAF Basisrepo machen: https://github.com/puzzle/centos-apache-modsecurity
Updates melde ich hier.
