### ISSUE TITLE
Initialer Projektsetup: neue Rails App analog Quartieridee erstellen

### ISSUE THREAD

**Issue by bsantschi** [puzzle/decidim-zuerich#3]
Allgemein:
- neue Rails App analog Quartieridee erstellen
- Kartenmodul analog Quartieridee
- kein Matomo

Sprachen:
- Deutsch und Englisch von quartieridee.ch übernehmen
- Zudem Französisch und Italienisch (Standardübersetzungen von decidim übernehmen)

**Comment by Kagemaru** [comment]
https://pitc-decidim-zuerich-int.ocp.puzzle.ch
