### ISSUE TITLE
Umfragedaten-Löschen Setting standardmässig deaktivieren

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#302]
Diese Einstellung bei der Umfragekomponente könnte zur Folge haben, dass unbeabsichtigt Daten gelöscht werden. Es ist standardmässig aktiviert. Bitte so einstellen, dass es standardmässig nicht aktiviert ist.

![Bildschirmfoto 2022-09-08 um 14 38 11](https://user-images.githubusercontent.com/60926257/189123679-6a98f47e-d2ac-44de-b75d-7fca66a540c7.png)

**Comment by Kagemaru** [comment]
Ist das nicht nur, damit man, wenn man es öffentlich schaltet, die Testantworten nicht mehr drin hat?

Ich habe es mal umgesetzt und auf INT deployt.

**Comment by larsUE** [comment]
Ja, aber wir verwenden es auch wenn eine Formular mehrmals ausgefüllt werden soll (z.B. beim Kontaktformular). Das geht nur, wenn wir in regelmässigen Abständen die Antworten löschen.

Und dann gibts noch den Case wo vielleicht ein Prozess die Umfrage auf "Unveröffentlicht" stellt, z.B. weil sie etwas abklären müssen oder weil der Prozess in die nächste Phase geht. Veröffentlichen sie die Komponente dann wieder, ist halt alles weg.

Habs getestet auf INT, sieht super aus, danke!

**Comment by larsUE** [comment]
Übrigens: Bald wird das dann richtig gemacht https://github.com/decidim/decidim/issues/9168
