### ISSUE TITLE
Umfrage-Erfolgsmeldung HTML customizable machen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#313]
Wir würden gerne den Key decidim.forms.questionnaires.show.questionnaire_answered.body
per HTML konfigurierbar machen, um z.B. Links einfügen zu können.

**Comment by Kagemaru** [comment]
Dies ist meiner Meinung nach ein Template, welches wir überschreiben müssen. Ich habe lokal ein Problem mit den Questionnaires. Ich habe den change mal gemacht und auf INT gepackt.

@larsUE Könntest du mal testen, ob dies so geht?

**Comment by larsUE** [comment]
Funktioniert prima, danke!
