### ISSUE TITLE
Metrics installieren

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#314]
Siehe hier: https://docs.decidim.org/en/develop/metrics

Bitte auch für die PROD die Werte seit Launch (11.4.2021) berechnen. Gemäss Dokumentation sollte das möglich sein.

**Comment by bsantschi** [comment]
Für dieses Modul (wie auch später für Decidim v 0.27) müssen wir Background-Jobs (delayed-cron-jobs) einrichten, warten und supporten. Aufwand ist daher einiges grösser als bei der Installation von einfacheren Modulen (schätzungsweise 1-3 Tage). @larsUE sollen/dürfen wir das umsetzen?

**Comment by Kagemaru** [comment]
Dies ist nun erledigt und ich konnte (mit der Hilfe eines Mitarbeiters) auch gleich einen Konfigurationsfehler beheben, was das lokale Arbeiten nun vereinfacht. :+1: 

Es wird gerade gebaut und danach auf INT deployed.

**Comment by larsUE** [comment]
Cool, danke! Ist es schon auf INT?

**Comment by Kagemaru** [comment]
Ich bin sie jetzt grad noch manuell am rebuilden, danach geht es jede Nacht automatisch.

**Comment by larsUE** [comment]
Danke! Ich seh auf der INT allerdings noch nichts, weder im Backend noch in einem Prozess, wo sie angezeigt werden sollten.

**Comment by Kagemaru** [comment]
Also, die Werte stehen in der Datenbank, gelangen aber nicht auf die Seite, wo die Metriken dargestellt werden sollen.

Ich schaue nächste Woche nochmals drauf, evtl. mit Unterstützung von @carlobeltrame.

Darstellungsbeispiel:
https://docs.decidim.org/en/develop/admin/features/metrics

**Comment by Kagemaru** [comment]
Ich habe inzwischen herausgefunden, dass der `metrics` Endpoint auf der GraphQL API "fehlt".

Bei dialogluzern.ch scheint es auf 0.26.1 zu funktionieren und bei einer neuen Testinstallation von 0.26.3 auf meinem Laptop hat es auch funktioniert.

Bis jetzt bin ich noch nicht dahinter gekommen, was hier den Unterschied macht.

**Comment by larsUE** [comment]
Ich konnte es auf Dialog auch kurz testen, scheint bis auf ein paar grafische Glitches gut zu funktionieren. Wie fahren wir für die Zürcher Plattform weiter?

**Comment by larsUE** [comment]
Grafische Glitches sind behoben, wunderbar! Von mir aus bleiben noch folgende Tasks:

- [ ] Rückwirkende Erstellung seit Plattform-Beginn INT
- [ ] Rückwirkende Erstellung seit Plattform-Beginn PROD

**Comment by bsantschi** [comment]
Aktueller Stand: auf INT noch mehrere Fehler, da noch nicht auf PROD.

**Comment by Kagemaru** [comment]
Die Fehler entstehen, wenn die gleiche Metrik für einen Tag schon erstellt wurde. Das Fehlerverhalten ist etwas aggressiv für meinen Geschmack, da es direkt bis zum Sentry durchschlägt, aber das heisst wir müssen uns keine Sorgen machen und können, es auf PROD laufen lassen.

Ich starte es heute Abend mal, wenn das für dich OK ist @larsUE

**Comment by larsUE** [comment]
Cool, go for it!

**Comment by Kagemaru** [comment]
Die Neuberechnung der Metriken ist nun abgeschlossen.

**Comment by larsUE** [comment]
Cool! Ich sehe die Resultate allerdings nur bis zum 1.10.22 (PROD und INT). Zeigt decidim nur so viele Zahlen an oder wo bleibt der Rest?

**Comment by Kagemaru** [comment]
Hmm... Jetzt ist es nur noch bis am 04.10.2022, deshalb nehme ich an, es limitiert wie lange es zurückgeht.
Die Daten sind zumindest in der Datenbank. Wir haben über 20k Metrics. Über die GraphQL API sind sie auch erhältlich.

**Comment by larsUE** [comment]
Ok, könntest du mir einen export der Datenbanken machen? Dann kann ich die Zahlen mal eigenständig analysieren.
