### ISSUE TITLE
500er bei neuer Veröffentlichung

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#315]
Wenn ich auf den Link klicke, der im E-Mail zur Veröffentlichung verschickt wird, kriege ich einen 500er:
<img width="1159" alt="Bildschirmfoto 2022-09-19 um 16 16 18" src="https://user-images.githubusercontent.com/60926257/191038911-7db8373b-3446-4871-8846-3539a9f8038a.png">

Link hier: http://mitwirken.stadt-zuerich.ch/processes/wohnen-im-alter-privater-prozess/f/221/

Ich kann den ganzen Prozess nicht aufrufen. Zwei Fragen:
1. Weshalb erscheint der 500er? Das geht wieder in Richtung 500er bei der Umfrage. Diese Umfrage wurde importiert (Export von der bereits bestehenden, langen Umfrage und Import als neuer Prozess). Geht da wohl etwas kaputt?
2. Weshalb erscheint noch nicht die richtige Fehlermeldung?

**Comment by carlobeltrame** [comment]
Ich sehe noch dass Werner am 14.9. am Nachmittag zwei Mal Probleme mit dem Import eines Prozesses hatte, weil die Anhänge nicht dort waren wo decidim sie erwartet hat. War das zufälligerweise genau dieser Prozess und könnte das das Problem von heute ausgelöst haben?

**Comment by larsUE** [comment]
@carlobeltrame cool, danke! Ja, ich nehme an der Import am 14.9 war genau dieser Prozess. Seit dem Update haben wir Probleme mit den Attachments. Soll ich mal testen, ob dies ein generelles Problem ist oder nur diesen spezifischen Prozess betrifft?

**Comment by carlobeltrame** [comment]
Ja, das wäre wohl sinnvoll, die Attachment Import-Probleme mal etwas einzugrenzen.

**Comment by larsUE** [comment]
Bei V0.26.2 & 3 wurden relativ viele Fixes  für 500er bei unbekannten /kaputten Seiten eingespielt. Ich close hier mal.
