### ISSUE TITLE
Aufbau Integrationsumgebung

### ISSUE THREAD

**Issue by bsantschi** [puzzle/decidim-zuerich#32]
- neue Umgebung aufbauen
- Erweiterungen von https://pitc-decidim-zuerich-int.ocp.puzzle.ch übernehmen
- mit HTTP Auth (wie Luzern) schützen
- URL https://mitwirken.integ.stadt-zuerich.ch/
- Sprachen: nur noch DE/EN

**Comment by bsantschi** [comment]
Thomas klärt mit Severin noch ab, ob INT gleich auf APPUiO aufgebaut werden soll.

**Comment by Kagemaru** [comment]
Die Umgebung ist nach den obigen Angaben erstellt.
Interne URL: https://pitc-decidim-zuerich-new-int.ocp.puzzle.ch 
Externe URL: Braucht noch eine DNS Anpassung
HTTP Auth Login: https://cryptopus.puzzle.ch/accounts/5266

**Comment by larsUE** [comment]
@Kagemaru @bsantschi wie funktioniert das mit dem HTTP Auth Login? bzw. könnt ihr mir die Zugangsdaten zur Integration zukommenlassen? (Am liebsten gleich mit Admin-Rechten ;) )

**Comment by bsantschi** [comment]
- Hey @larsUE , ich schicke dir die Credentials über einen sicheren/anderen Weg.
- @Kagemaru , kannst du Lars' User zum Admin machen?

**Comment by Kagemaru** [comment]
Sobald er einen erstellt hat, mach ich das gerne.
System Admin sollte er jetzt sein. (Password ist das gleiche wie für HTTP Basic Auth, bitte ändern)

**Comment by larsUE** [comment]
Neuer Link für INTEG: https://pitc-stzh-decidim-int.appuioapp.ch/
