### ISSUE TITLE
Weiterleitung nach Registration anpassen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#320]
Wie hier übernehmen: https://github.com/decidim-swiss/decidim.swiss/issues/22

**Comment by carlobeltrame** [comment]
Ich habe das umgesetzt, kann es aber nicht auf Integration deployen weil in https://github.com/puzzle/decidim-module-term_customizer der Commit 13966522e8e8c30adc2655a1e9f2ec15ab567b43 nicht (mehr) existiert. @Kagemaru weisst du da mehr? Oder @larsUE ists auch okay wenn das dann einfach irgendwann mal mitkommt?

**Comment by larsUE** [comment]
@carlobeltrame was heisst irgendwann? Für mich ist es ok, hauptsache ich kann es nach meinen Ferien dann testen.

**Comment by Kagemaru** [comment]
@carlobeltrame, @larsUE:
Sorry, ich musste den Commit herausnehmen und die Versionen 0.26.2/0.26.3 sauber bundlen. Ich hab sie jetzt mit tags versehen.
Ausserdem war was mit der Bundler version im run Image schief. Dies ist nun auch gefixt.

Dieser Commit kam mit dem Upgrade direkt mit und ist jetzt auf der INT.
