### ISSUE TITLE
Term-Customizer scoping für Prozessgruppen ermöglichen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#327]
Wir brauchen das dringend. Gemäss Antti würden sie gerne einen PR zu diesem Thema akzeptieren: https://github.com/mainio/decidim-module-term_customizer/issues/75

**Comment by carlobeltrame** [comment]
Das verlinkte Issue spricht nur von der Landing Page von einer Prozessgruppe. @larsUE braucht ihr das auch nur auf dieser einen Seite oder wollt ihr es in allen Prozessen der Prozessgruppe haben?

**Comment by larsUE** [comment]
Genau, wir brauchen die Möglichkeit, zusätzlich auch die Landing Pages der Prozessgruppen auswählen zu können. Es müssen nicht alle zugewiesenen Prozesse ebenfalls mit ausgewählt werden, das würde die Flexibilität wohl etwas verringern und die Komplexität erhöhen. Decidim Awesome macht das bereits sehr schön, schau beispielsweise [hier](https://mitwirken.stadt-zuerich.ch/admin/decidim_awesome/config/styles) auf der Prod beim obersten Feld.

![Bildschirmfoto 2022-09-28 um 13 44 56](https://user-images.githubusercontent.com/60926257/192770759-7b0c0a08-0002-4aca-8a99-f18502d9da3d.png)

Die oberste Constraint setzt die Landing Page, die untere einen Prozess. Wäre cool, das könnten wir beim TC auch so machen.

**Comment by carlobeltrame** [comment]
Grobschätzung: 4 PT

Ich habe das mal angeschaut. Die Constraints von Decidim Awesome funktionieren leider anders als die beim Term Customizer, weil der Term Customizer sich "tiefer" / "interner" einnisten muss um seine Arbeit zu verrichten. Wir können daher nur punktuell von Decidim Awesome lernen.
Ich habe unten die technischen Resultate meiner Analyse festgehalten. Im Detail ist es leider relativ kompliziert, was zu dem gefühlt eher hohen Aufwand für die aus User-Sicht wahrgenommene Featuregrösse führt. Der "Wurm" steckt darin dass Prozessgruppen (im Gegensatz zu Prozessen und Assemblies) keine Participatory Spaces sind, und wir die Filterung danach nicht einfach analog zu Prozessen "aktivieren" können, sondern quasi auf ganzer Länge der bestehenden Filterung Spezialfälle für Prozessgruppen einbauen müssen.

## Tech spec
- [ ] In Menü [[1]](https://github.com/mainio/decidim-module-term_customizer/blob/master/app/views/decidim/term_customizer/admin/translation_sets/_constraint_fields.html.erb#L27) [[2]](https://github.com/mainio/decidim-module-term_customizer/blob/master/app/views/decidim/term_customizer/admin/translation_sets/_constraint_fields.html.erb#L33) eine neue Art von non-ParticipatorySpce Constraint ermöglichen, analog wie es [Decidim Awesome macht](https://github.com/Platoniq/decidim-module-decidim_awesome/blob/main/app/helpers/decidim/decidim_awesome/admin/config_constraints_helpers.rb#L7)
- [ ] Im ControllerContext auch die ProcessGroup detektieren, falls wir gerade eine Prozessgruppen-Landing-Page rendern: [in der Base Klasse](https://github.com/mainio/decidim-module-term_customizer/blob/master/lib/decidim/term_customizer/context/base.rb) und [in der abgeleiteten Klasse die sich um den Kontext bei HTTP Requests kümmert](https://github.com/mainio/decidim-module-term_customizer/blob/master/lib/decidim/term_customizer/context/controller_context.rb)
  - Diese Detektion, angenommen man hat einen Request, wird in Decidim Awesome in [dieser Datei](https://github.com/Platoniq/decidim-module-decidim_awesome/blob/main/lib/decidim/decidim_awesome/context_analyzers/request_analyzer.rb) gemacht.
  - Wie man im ControllerContext überhaupt an den Request kommen kann ist noch unklar. Notfalls vielleicht ähnlich wie [hier](https://github.com/hitobito/hitobito/blob/master/config/initializers/cors.rb#L11)
- [ ] Die neue Information (auf welcher Prozessgruppen-Landingpage sind wir, wenn überhaupt) an den Resolver weitergeben: [hier](https://github.com/mainio/decidim-module-term_customizer/blob/master/lib/decidim/term_customizer/engine.rb#L53) und [hier](https://github.com/mainio/decidim-module-term_customizer/blob/master/lib/decidim/term_customizer/engine.rb#L23)
- [ ] Im [Resolver](https://github.com/mainio/decidim-module-term_customizer/blob/master/lib/decidim/term_customizer/resolver.rb#L50..L59) eine Query-Erweiterung schreiben, die nur aktiv ist wenn wir die Landing Page einer Prozessgruppe rendern, und die Constraints auf diese spezifische Prozessgruppe (via id) oder auf alle Prozessgruppen (wenn id leer) sucht.
- [ ] Für alle oben erwähnten angefassten Dateien [Tests](https://github.com/mainio/decidim-module-term_customizer/tree/master/spec/lib/decidim/term_customizer) schreiben
- [ ] Pull request beim Term Customizer eröffnen, auf Antwort warten und allfälligen Änderungswünschen von mainio nachkommen

**Comment by eliegaboriau** [comment]
Hello, 
We might be interested in this feature at Open Source Politics.
Do you plan to work on this ?
If you do, when do you think will it be available ?
If you don't, could we publish those tech specs on the Term Customizer to ask for a feedback ?
Thanks a lot

**Comment by larsUE** [comment]
Hey @eliegaboriau ! Cool, thanks for letting us know. We currently are not working on this, because we found another purpose for process groups. However, this still is interesting for us and we can supply some technical help if you wish. Just ask @carlobeltrame or @Kagemaru :) Thank you!

**Comment by larsUE** [comment]
English translation of the Tech Specs. @carlobeltrame please check if this makes sense:

### Tech spec

-   Enable new type of Non-ParticipatorySpaceConstraint in Menu [[1]](https://github.com/mainio/decidim-module-term_customizer/blob/master/app/views/decidim/term_customizer/admin/translation_sets/_constraint_fields.html.erb#L27) [[2]](https://github.com/mainio/decidim-module-term_customizer/blob/master/app/views/decidim/term_customizer/admin/translation_sets/_constraint_fields.html.erb#L33) e.g. like [Decidim Awesome](https://github.com/Platoniq/decidim-module-decidim_awesome/blob/main/app/helpers/decidim/decidim_awesome/admin/config_constraints_helpers.rb#L7)
- Potentially some adjustments in the [form](https://github.com/mainio/decidim-module-term_customizer/blob/master/app/forms/decidim/term_customizer/admin/translation_set_constraint_form.rb) are required during validation.
- Detect the Process Group in the  ControllerContext auch die ProcessGroup detektieren, if a process group landing page is being rendered [in the base class](https://github.com/mainio/decidim-module-term_customizer/blob/master/lib/decidim/term_customizer/context/base.rb) and [in the deducted class which builds the context for HTTP Requests](https://github.com/mainio/decidim-module-term_customizer/blob/master/lib/decidim/term_customizer/context/controller_context.rb)
- This detection, supposed one has a request, is done in [this file](https://github.com/Platoniq/decidim-module-decidim_awesome/blob/main/lib/decidim/decidim_awesome/context_analyzers/request_analyzer.rb) in Decidim Awesome.
- How we can get to the request from the ControllerContext is unclear. Maybe something similar as done in [hitobito](https://github.com/hitobito/hitobito/blob/master/config/initializers/cors.rb#L11)
- Transmit the new information (on which landingpage we are, if applicable) to the resolver: [here](https://github.com/mainio/decidim-module-term_customizer/blob/master/lib/decidim/term_customizer/engine.rb#L53) and [here](https://github.com/mainio/decidim-module-term_customizer/blob/master/lib/decidim/term_customizer/engine.rb#L23)
-   Write a Query-Extension in the [Resolver](https://github.com/mainio/decidim-module-term_customizer/blob/master/lib/decidim/term_customizer/resolver.rb#L50..L59), which is only active when a landing page of a process group is rendered, and which searches if the constraint  is valid for this specific process group (via ID) or for all process groups (no ID).
- Write [tests](https://github.com/mainio/decidim-module-term_customizer/tree/master/spec/lib/decidim/term_customizer) for all aforementioned files
-Open PR at Term Customizer and adjust according to the wishes of mainio

**Comment by eliegaboriau** [comment]
Hello @larsUE and @carlobeltrame , i've submitted a solution to this issue.
It is slightly less complicated than it was supposed, but it seems to work well.
Feel free to add your review

**Comment by larsUE** [comment]
Implemented by @eliegaboriau in https://github.com/mainio/decidim-module-term_customizer/pull/94, thanks a lot!

We will need to update the term customizer as soon as the PR is approved.
