### ISSUE TITLE
Auf Decidim Version 0.23.1 updaten

### ISSUE THREAD

**Issue by bsantschi** [puzzle/decidim-zuerich#33]
Einige Module haben sich noch nicht mit decidim-0.23.1-fähig markiert, obwohl sie es sind. Für diese Module soll auf puzzle ein Fork unterhalten werden, der automatisiert mit dem Original synchron gehalten wird. Dabei erstellen wir auch in Zukunft jeweils einen Branch pro decidim-Version.
Betroffene Module:
* term customizer
* ...

**Comment by carlobeltrame** [comment]
Die neue und alte Integration laufen jetzt mit decidim 0.23.3. Falls irgendwelche Probleme auftauchen bitte melden. Als nächstes beginne ich mit den besprochenen CI/CD Anpassungen.

**Comment by larsUE** [comment]
Super nice! Sehe bereits viele coole Änderungen. @carlobeltrame: Ich mach jeweils eigene Issues, die ich im Zusammenhang mit dem Update sehe und mach dafür das Tag "Update" und "Bug". Darf ich dich dann gleich zuuweisen?
