### ISSUE TITLE
Session Time-Out: erhöhen oder umgehen bei Umfragen?

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#337]
Bitte nach #334 angehen. Dieses Problem ist noch nicht zufiredenstellen gelöst und tritt immer wieder auf bzw. wird gemeldet. Können wir die Session-Zeit verlängern oder eine Alternative Lösung finden, dass bei einem Session-Time-Out in einer Umfrage kein 500er erscheint?

**Comment by carlobeltrame** [comment]
Die Session-Dauer ist technisch einfach die Lebens- / Gültigkeitsdauer eines Cookies. Cookies gelten immer für eine ganze Domain. Es gibt daher keinen einfachen Weg, die Dauer nur für die Umfragen länger einzustellen.

Wir können die Session-Dauer theoretisch für die ganze Decidim-Instanz hochstellen, aber ich hatte das zuvor bereits einmal versucht und die Einstellung die ich gemacht habe hatte nicht gegriffen.

**Comment by larsUE** [comment]
siehe #334
