### ISSUE TITLE
Themen «Stadtentwicklung & Mobilität» und «Partizipatives Budget» löschen auf Prod

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#347]
Wenn ich die Scopes löschen möchte, kriege ich einen 500er. 

Beim Partiziaptiven Budget sind sicherlich noch Elemente verknüpft. Das spielt aber keine Rolle, die sollen nachher einfach keinen scope haben.

**Comment by Kagemaru** [comment]
@larsUE

Das ist von Decidim tatsächlich so programmiert. Sie haben zwar die Relation auf `optional: true` gesetzt, auf der Datenbank haben sie jedoch die `ON DELETE` Option nicht gesetzt, welche standardmässig `NO ACTION` ist. Dies wirft einen Fehler beim Löschen, wenn es noch verbundene Elemente gibt.

Dies scheint ein Versehen zu sein und ich werde es bei Decidim melden. Ich würde dies lieber nicht direkt bei uns reparieren, da dies Datenbankänderungen erfordert, die ich gerne so nahe wie möglich am Original lassen will. 

In der Zwischenzeit könnte ich die Verbindungen manuell auf NULL setzen und die 2 Themen löschen, wenn das gewünscht ist.

**Comment by larsUE** [comment]
@Kagemaru auf NULL setzen bei uns und Decidim melden wäre super, danke dir!

Wir möchten nun die Filter brauchen und da ist es wichtig, dass die nicht angezeigt werden, da sie nicht gebraucht werden.

**Comment by Kagemaru** [comment]
Erledigt :smile:
