### ISSUE TITLE
Umfrage: Single Choice als Drop-Down

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#351]
Dial bei der Single Choice Antwort-Option hinzufügen, dass die Antworten als Drop-down formatiert werden.

**Comment by Kagemaru** [comment]
@larsUE Hierfür fallen mir 2 Wege ein:

1. Ein Hack mit CSS/Javascript (das originale _single_option überschreiben), dies wúrde ca. 1.5-2 Tage dauern).
2. Decidim um die Option erweitern, dass man die `single_option` als Dropdown darstellen kann. Dies kann ich schlecht einschätzen, weil wir zuerst den genauen Ablauf verstehen müssten. Wahrscheinlich ca. 1 Woche+.

**Comment by carlobeltrame** [comment]
Noch anzumerken: Bei Option 1. würden automatisch alle Single Choice Fragen auf der ganzen Plattform zu Dropdown Menüs geändert werden. Da gibts keine einfache Möglichkeit, nur einzelne zu ändern.

**Comment by larsUE** [comment]
Das habe ich mir gedacht. Und so eine Mischform (also die Single_option duplizieren, und dann das Duplikat per CSS/JS zu hacken) wäre auch nicht möglich? In Anbetracht dessen, was ich in #352 geschrieben habe, dass wir da allenfalls nächstes Jahr noch aufbauen würden und entweder ein Modul machen oder uns einem Modul anschliessen würden.

**Comment by Kagemaru** [comment]
> Noch anzumerken: Bei Option 1. würden automatisch alle Single Choice Fragen auf der ganzen Plattform zu Dropdown Menüs geändert werden. Da gibts keine einfache Möglichkeit, nur einzelne zu ändern.

Um es genauer zu beschreiben: Alle Single Choice Fragen, die keine Optionen mit `Freien Texten` beinhalten, würden geändert werden.

Um es überall zu duplizieren, muss ich erst verstehen, wo es überall verwendet wird. Damit sind wir schon tief in der Option 2 drin und ab da macht es mehr Sinn, dies vollends hinzuzufügen. Da die Hauptarbeit nicht das HTML/CSS/JS ist, dass wir uns am Ende sparen.

**Comment by larsUE** [comment]
Genau, wir möchten Option 2. Die Funktion “Single Choice Frage" wird an folgenden Orten eingesetzt, m.E. ist diese Liste abschliessend:

- Surveys (Beispiel: https://mitwirken.integ.stadt-zuerich.ch/processes/testprozess/f/42/)
- Meeting registrations (Beispiel: https://mitwirken.integ.stadt-zuerich.ch/admin/participatory_processes/testprozess/components/244/manage/meetings/58/registrations/form/edit)
- Online meeting surveys (Beispiel: https://mitwirken.integ.stadt-zuerich.ch/admin/participatory_processes/testprozess/components/244/manage/meetings/59/poll/edit)

**Comment by bsantschi** [comment]
1. Template umbauen
2. Länderliste zusammen mit Lars erstellen (kann möglicherweise von INT auf PROD via Console übernommen werden)
3. PROD bis allerspätestens 4. Januar
4. Pokecode anfragen/PR schicken, ob sie es in Decidim Awesome übernehmen möchten

**Comment by larsUE** [comment]
Funktioniert grundsätzlich gut! Folgendes ist mir beim Testing aufgefallen:
Wenn ich im !dropdown! die erste Option auswähle (also Ägypten bei !sort! oder Tschechien beim normalen dropdown), erscheint dieses Resultat nicht in den Antworten.
<img width="964" alt="Bildschirm­foto 2022-12-29 um 10 28 06" src="https://user-images.githubusercontent.com/60926257/209931635-15a16a52-f86e-469f-a1ed-23ab0064f68d.png">

<img width="1300" alt="Bildschirm­foto 2022-12-29 um 10 29 56" src="https://user-images.githubusercontent.com/60926257/209931843-7f2f9a81-84bb-4512-8124-0c19b53746d3.png">

Antworten, die nirgends die ersten voreingestellten Antworten sind, erscheinen jedoch wie gewünscht:
<img width="1521" alt="Bildschirm­foto 2022-12-29 um 10 31 06" src="https://user-images.githubusercontent.com/60926257/209931983-96297880-d596-4ed1-8414-cc952c0cee54.png">

Dafür funktioniert das Sortieren auch auf Englisch prima, das ist super!
