### ISSUE TITLE
Umfrage: Länderliste

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#352]
Möglichkeit, eine Single-Choice Antwort als Land aus einer Liste aller Länder auszuwählen. In Kombination mit #351 betrachten.

**Comment by Kagemaru** [comment]
@larsUE Auch hier kann ich mir 2 Lösungen vorstellen:
1. Wieder ein Hack, diesmal allerdings komplizierter, da hier die Antworten nicht direkt mitgeliefert werden. Wahrscheinlich würde ich hier mit einem kurzen Textfeld und einem bestimmten Namen die Auswahl bereitstellen.
2. Wie bei #351 kann man es als Erweiterung bei Decidim entwickeln. Auch hier rechne ich mit ~1 Woche. Wenn allerdings beide so gelöst werden, reduziert sich die Zeit für das zweite Feld immens. Hier sind wir allerdings auch drauf angewiesen, dass Decidim dieses Feature als Standard übernehmen will.

**Comment by larsUE** [comment]
OK, danke für die Aufwandschätzung! Wir überlegen uns so oder so, nächstes Jahr etwas Geld in die Hand zu nehmen, um das Umfragefeature auszubauen, u.U. auch z.B. im Rahmen eines bestehenden oder neuen Moduls -> oder gleich für den Core abzielen. Ich kläre den Aufwand ab und melde mich gleich wieder.

**Comment by larsUE** [comment]
Mir fällt gerade noch ein gewichtiger Nachteil der manuellen Erfassung auf: Gesetzt den Fall ich erfasse die Optionen alphabetisch auf Deutsch, dann erscheinen die Länder auf Englisch ja in einer sehr komischen Reihenfolge, da nicht alle gleich sind (z.B. Ägypten/Egypt).

Langristig müssten wir wohl irgendeine andere Lösung hierfür finden, z.B. die Integration dieses Gems: https://www.ruby-toolbox.com/projects/country_select

**Comment by larsUE** [comment]
Die Länderliste ist nun auf Prod und Int als Vorlage verfügbar.
