### ISSUE TITLE
Decidim Cleaner Module installieren

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#355]
https://github.com/OpenSourcePolitics/decidim-module-cleaner

**Comment by Kagemaru** [comment]
@larsUE
Ich musste gleich alle Module auf 0.26.4 ziehen, da dieses Modul darauf basiert.
Dies ging ohne Probleme und wird in den nächsten Minuten auf INT deployed.

**Comment by larsUE** [comment]
Irgendwie sehe ich die Einstellungen im Backend nicht. Eigentlich sollte ja ein separater Tab erscheinen.

Hier noch das Sprachfile, ich sende das auch noch an OSP.

`---
de:
  activemodel:
    attributes:
      organization:
        delete_admin_logs: Löschen von Admin-Protokollen zulassen
        delete_admin_logs_after: Admin-Protokolle löschen nach (Tage, standardmässig 365)
        delete_inactive_users: Inaktive Teilnehmende löschen
        delete_inactive_users_after: Inaktive Teilnehmende löschen nach (Tage, standardmässig 390)
        delete_inactive_users_email_after: E-Mail zur bevorstehenden Konto-Löschung versenden nach Inaktivität von (Tagen, standardmässig 365)
  decidim:
    admin:
      menu:
        clean: Datenbereinigung
    cleaner:
      admin:
        organization_cleaner:
          edit:
            update: Aktualisieren
          form:
            admin_log_cleaner_title: Admin-Log
            inactive_users_cleaner_title: Inaktive Teilnehmende
      inactive_users_mailer:
        warning_deletion:
          body_1: Sie sind seit %{Tagen} Tagen bei <a href="%{Organisation_url}"> %{Organisation_name} </a> inaktiv.
          body_2: Infolgedessen wurde Ihr Konto gelöscht.
          greetings: Freundliche Grüsse,<br/>%{organization_name}<br/><a href="%{organization_url}">%{organization_url}</a>
          hello: Guten Tag
          subject: Ihr Konto wurde gelöscht.
        warning_inactive:
          body_1: Sie sind seit %{Tagen} Tagen bei %{Organisation_name} inaktiv.
          body_2: <a href="%{organization_url}">Wenn Sie sich nicht innerhalb %{remaining_days} Tagen anmelden </a>, wird ihr Konto gelöscht.
          greetings: Freundliche Grüsse,<br/>%{organization_name}<br/><a href="%{organization_url}">%{organization_url}</a>
          hello: Guten Tag
          subject: Ihr Konto ist inaktiv
    components:
      cleaner:
        name: Bereinigung`
