### ISSUE TITLE
Ausbau Kartenfunktion

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#36]
Wichtiger Punkt für TAZ Milestone. Erstmal abwarten, was Decidim V 0.23 für Änderungen bringt. & unbedingt aufbauen auf https://github.com/stadtluzern/decidim-ocl/issues/40.

**Comment by larsUE** [comment]
Vom Style, gemäss städtischem CI/CD: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/openlayers/openlayers.html

**Comment by larsUE** [comment]
Für Testprozess: Lösung für Luzern übernehmen.

**Comment by larsUE** [comment]
Erste Ansätze zur Platzierung befinden sich [hier](https://meta.decidim.org/processes/roadmap/f/122/proposals/13116?filter%5Bdecidim_scope_id%5D=&filter%5Bresource_type%5D=Decidim%3A%3AProposals%3A%3AProposal&filter%5Bterm%5D=a&order=with_more_authors&page=2&per_page=100#list-of-endorsements).

**Comment by carlobeltrame** [comment]
Die Änderung kommt erst mit decidim 0.24, aber es wäre nicht allzu schwierig, sie schon vorher zu übernehmen.

**Comment by larsUE** [comment]
Anbindung z.B. an [Stadtplan](http://www.stadtplan.stadt-zuerich.ch/zueriplan3/stadtplan.aspx#route_visible=true&basemap=Basiskarte+(Gebäudeschrägansicht)&map=&scale=8000&xkoord=2683299&ykoord=1247363&lang=&layer=&window=&selectedObject=&selectedLayer=&toggleScreen=&legacyUrlState=&drawings=), Hier die Karte im Geoportal: https://www.stadt-zuerich.ch/geodaten/download/Basiskarte_Zuerich_Raster

@carlobeltrame : Läuft die Kartenanbindung eigentlich über WMS/WFS Anbindungen? Supercool wärs z.B. als langfristiges Feature, wenn eigene WMS-Links pro Modul (z.B. in den Komponenteneinstellungen) hinzugefügt werden könnten.

**Comment by carlobeltrame** [comment]
Die Anbindung ist etwas allgemeiner als WMS/WMF, aber diese sind möglich. Als Mittelweg könnte ich mir mittelfristig vorstellen, dass wir in den Einstellungen eine fixe Auswahl an Layern einrichten (das kann decidim bereits seit 0.23), und dann in den Komponenten jeweils die Layers ausgewählt werden können (das fehlt noch).

Dass die User selber einen "Link" zu einem neuen Layer eingeben wäre wohl etwas schwieriger an decidim zu "verkaufen", weil wir uns entweder auf WMS limitieren müssen (der aktuelle Approach ist es, theoretisch möglichst alle Kartendienste zu ermöglichen), oder aber der User noch viel mehr technische Metainformationen eingeben muss (verwendetes Koordinatensystem, verfügbare Zoom-Stufen, etc.).

**Comment by wernerliechtenhan** [comment]
Im Nachgang zu den Inputs von Claudio Sparascio zum Thema Kartenmaterial hat sich nun Christian Gees von GeoZ, Leiter Geschäftsbereich des städt. GIS-Zentrum, gemeldet und gefragt, ob wir auf die städtischen Karten zugreifen möchten. 

>Möchten wir dort unsere Karten verwenden?
Beispiele:
o	Basiskarte Schrägansicht
o	Basiskarte
o	Luftbild 

Die Stadt verfügt selber offenbar über sehr gute, eigene digitale Karten und wir sollten vorzugsweise diese einsetzen. Könnt ihr mal klären, ob wir unser eigene Kartenservices nutzen können, bzw. welche Voraussetzungen dazu notwendig sind? 

Bitte kontaktiert Christian Gees  Christian.Gees@zuerich.ch, 044 412 27 51, oder direkt Georg Andersson, GIS-Spezialist, (georg.andersson@zuerich.ch, 044 412 46 01).

**Comment by larsUE** [comment]
Super, danke! Christian Gees habe ich auch bereits mal kennengelernt. Das schauen wir direkt mit ihnen an!

**Comment by carlobeltrame** [comment]
Notizen vom Meeting:
https://www.ogc.stadt-zuerich.ch/mapproxy/demo/
https://www.ogc.stadt-zuerich.ch/mapproxy/wmts/1.0.0/WMTSCapabilities.xml
Für den Moment mal WMTS basiskarte_zuerich verwenden.

**Comment by larsUE** [comment]
To-Do wenn ausgerollt: testen, ob #108 wieder auftritt.

**Comment by larsUE** [comment]
Hier zur info noch ein leaflet Bug, der auf V0.26 noch auftritt: https://github.com/decidim/decidim/pull/9269

**Comment by bsantschi** [comment]
Bitte danach https://github.com/puzzle/decidim-zuerich/issues/254 (Adress-Suche geografisch einschränken) umsetzen.

**Comment by larsUE** [comment]
@carlobeltrame, falls noch nicht zu spät: bitte die [Basiskarte schrägansicht](https://www.ogc.stadt-zuerich.ch/mapproxy/demo/?srs=EPSG%3A2056&format=image%2Fpng&wms_layer=basiskarte_zuerich_gebaeudeschraegansicht#) statt die normal Basiskarte aufsetzen :) Danke!

**Comment by carlobeltrame** [comment]
Ich konnte die Karte soweit umsetzen, ist auf der Integration verfügbar. @larsUE @innosmith bitte testen obs aussieht wie gewünscht.

Leider funktioniert wies aussieht jetzt tatsächlich #108 wieder nicht, nachdem wir den entsprechenden Workaround für #184 wieder entfernt haben.

**Comment by larsUE** [comment]
Cool, danke! Was mir noch auffällt, bzw. noch finegetuned werden könnte:

- **Zwingend für Update-Prod-Release** die Karte leer ist, ist der Standard-View ganz nah auf den HB hineingezoomed. Könnte hier stattdessen eine Zoomstufe gesetzt werden, die das ganze Stadtgebiet zeigt?
- **Zwingend für Update-Prod-Release** Für #108 müssten wir tatsächlich noch einen besseren Fix finden.
- **Zwingen für Update-Prod-Release** Wenn ich auf der MeinQuartier-Plattform auf einen Pin klicke, (z.B. Startseite bei den Veranstaltungen), dann spicke ich auf der Seite herum. Bei einzelnen Pins öffnet sich ein Veranstaltungsfenster, aber so gross, dass ich nicht alles sehen kann. Das sieht stark nach folgenden Bugs aus: https://github.com/decidim/decidim/pull/7335 und https://github.com/decidim/decidim/issues/7465

Für später:
- Die Icons haben noch eine hohe Transparenz und eine komische Rahmenfarbe. Das kann ich jedoch mit CSS flicken.
- Die Strassennamen sind ziemlich gross. Verglichen mit dem [Stadtplan](https://www.stadtplan.stadt-zuerich.ch/zueriplan3/stadtplan.aspx#route_visible=true&basemap=Basiskarte+(Gebäudeschrägansicht)&map=&scale=1000&xkoord=2683042.089069998&ykoord=1247350.1676826926&lang=&layer=&window=&selectedObject=&selectedLayer=&toggleScreen=&legacyUrlState=&drawings=) werden noch andere Tiles geladen. Scheinbar werden auf dem Stadtplan verglichen mit uns bei gleicher Zoomstufe andere Massstäbe geladen. -> auch das können wir nach dem Prod-Release anschauen.

**Comment by innosmith** [comment]
@carlobeltrame danke! Ich muss MeinQuartier noch genauer testen. Gibt es keine Luftbildkarten mehr?

**Comment by carlobeltrame** [comment]
>     * **Zwingend für Update-Prod-Release** die Karte leer ist, ist der Standard-View ganz nah auf den HB hineingezoomed. Könnte hier stattdessen eine Zoomstufe gesetzt werden, die das ganze Stadtgebiet zeigt?

Ja, kann ich machen.

>     * **Zwingend für Update-Prod-Release** Für [Karte: Verlinkungsfehler #108](https://github.com/puzzle/decidim-zuerich/issues/108) müssten wir tatsächlich noch einen besseren Fix finden.

Ja. Ich habe das Ticket mal ins Projekt aufgenommen, vergibst du noch die entsprechenden Labels und ordnest es gemäss Prio ein?

>     * **Zwingen für Update-Prod-Release** Wenn ich auf der MeinQuartier-Plattform auf einen Pin klicke, (z.B. Startseite bei den Veranstaltungen), dann spicke ich auf der Seite herum. Bei einzelnen Pins öffnet sich ein Veranstaltungsfenster, aber so gross, dass ich nicht alles sehen kann. Das sieht stark nach folgenden Bugs aus: [Truncate description in meetings map popup decidim/decidim#7335](https://github.com/decidim/decidim/pull/7335) und [Meetings : when the description is too long, the box in the map is cut off or not shown decidim/decidim#7465](https://github.com/decidim/decidim/issues/7465)

Klingt nach demselben Problem das ich bei Luzern in https://github.com/stadtluzern/decidim-ocl/issues/103 schon geflickt hatte. Das tritt auf wenn das Popup-Fensterli wegen zu ausführlicher Beschreibung zu hoch ist. Ich kann einen Scrollbalken im Popup-Fensterli einfügen, wie ich es in Luzern auch schon gemacht habe.

**Comment by carlobeltrame** [comment]
> Gibt es keine Luftbildkarten mehr?

@innosmith Die gibt es schon, du musst mir nur sagen welches Layer aus dem Abschnitt WMTS (nicht WMS) du gerne hättest: https://www.ogc.stadt-zuerich.ch/mapproxy/demo/
Zum Beispiel basiskarte_zuerich_orthofoto

**Comment by larsUE** [comment]
@carlobeltrame super, danke!

> Ja, kann ich machen.
am besten so weit raus, dass im Westen noch keine weissen Flächen sichtbar sind (Kantonsgrenze), und möglichst die ganze Stadt drauf ist (also entweder Zoomstufe 2 mit leicht östlicherem Mittelpunkt (prio) oder Stufe 3).

> Ja. Ich habe das Ticket mal ins Projekt aufgenommen, vergibst du noch die entsprechenden Labels und ordnest es gemäss Prio ein?
 #108 ist nun richtig priorisiert und getaggt.

> Klingt nach demselben Problem das ich bei Luzern in https://github.com/stadtluzern/decidim-ocl/issues/103 schon geflickt hatte. Das tritt auf wenn das Popup-Fensterli wegen zu ausführlicher Beschreibung zu hoch ist. Ich kann einen Scrollbalken im Popup-Fensterli einfügen, wie ich es in Luzern auch schon gemacht habe.
Das wäre perfekt!

> @innosmith Die gibt es schon, du musst mir nur sagen welches Layer aus dem Abschnitt WMTS (nicht WMS) du gerne hättest: https://www.ogc.stadt-zuerich.ch/mapproxy/demo/
Zum Beispiel basiskarte_zuerich_orthofoto

Ich würde auch das Orthophoto nehmen, weil es den ganzen Kanton abdeckt, während die Luftbilder nur das Stadtgebiet verdecken.

**Comment by larsUE** [comment]
Neu sind alle Punkte in eigenen Tickets. Gemäss Testing von Werner kam neu noch #262 dazu.

**Comment by carlobeltrame** [comment]
Ist alles umgesetzt und auf Integration ausgerollt.

**Comment by larsUE** [comment]
@carlobeltrame grandios, danke! Hab alles auf beiden INTs getestet und es funktioniert wie gewünscht.

**Comment by wernerliechtenhan** [comment]
Super! Danke auch von mir! Ist es möglich auf der MeinQuartier-Plattform die Karte bei der Veranstaltungsübersicht um einen Zacken zu vergrössern und ganz leicht nach links zu schieben, damit sie bildfüllend ist? 
![image](https://user-images.githubusercontent.com/78415323/172632729-9e2c4e96-4592-44a1-a056-23421dbb01db.png)

**Comment by innosmith** [comment]
Auch von meiner Seite besten Dank @carlobeltrame! 

Ergänzend folgendes Detailfeedback:
- Wenn ich eine einzelne Veranstaltung anklicke, erscheint auf der Veranstaltungs-Detailseite fast flächendeckend das adressierte Zielgebäude, siehe Bild. Die meisten Nutzenden werden zuerst etwas wegzoomen müssen, um zu erkennen, wo das Gebäude ist. Können wir defaultmässig wieder etwas mehr Vogelperspektive erhalten?
- Ob die Basiskarte oder das Luftbild als Default besser geeignet ist, muss die Stadt Zürich @wernerliechtenhan  entscheiden. Beide Kartenmaterialien sind sehr schön. Zur Navigation arbeite ich persönlich lieber mit Luftbildern, da ich mich damit besser orientieren kann.

**Comment by carlobeltrame** [comment]
Zoom und Ränder um automatisch angezeigten Ausschnitt sind jetzt auf der Testumgebung angepasst.

**Comment by innosmith** [comment]
Danke @carlobeltrame. Das sieht für mich gut aus, Detailansicht und Veranstaltungsübersicht. Ich bitte Werner es noch zu bestätigen.

**Comment by carlobeltrame** [comment]
@innosmith @larsUE wie am Meeting besprochen, die Karten auf Integration die keinen oder mehr als einen Marker anzeigen zeigen nun immer den gleichen vordefinierten Kartenausschnitt.

**Comment by larsUE** [comment]
Cool, danke! Ich schaus morgen an!könntest du möglichst bald noch #269 anschauen? Sorry, das hatte ich heute morgen vergessen zu erwähnen.

**Comment by innosmith** [comment]
Wenn nur die Veranstaltungen EINER Organisation angezeigt werden, ist der neue Fix-Modus ungünstig. Bsp. QV Witikon https://test.meinquartier.zuerich/assemblies/qvwitikon/f/160/. Hier wäre es gut, die vorherige Implementation zu haben. Ob der Standard-Kartenausschnitt für das gesamte städtische Gebiet ausreicht, könnt ihr besser beurteilen als ich ;-)

**Comment by carlobeltrame** [comment]
> Cool, danke! Ich schaus morgen an!könntest du möglichst bald noch #269 anschauen? Sorry, das hatte ich heute morgen vergessen zu erwähnen.

@larsUE #269 ist bereits gelöst und geschlossen. Das waren eben der neue "Modus" der Karten, den Decidim eingeführt hat. Hast du das falsche Issue verlinkt oder funktioniert da etwas doch noch nicht und wir müssten das Issue wieder eröffnen?

**Comment by larsUE** [comment]
@carlobeltrame sorry, ich meinte #267
