### ISSUE TITLE
Mitwirkungsprozesse aktualisieren nicht bei Filtereinstellungen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#366]
Wenn ich einen Scope/Area-Filter setze bei der Übersicht auf der Seite /Processes, dann wird die Seite nicht automatisch aktualisiert. Mit einem Reload lande ich auf den gefilterten Einstellungen.

**Comment by Kagemaru** [comment]
Repariert & deployed auf INT

**Comment by larsUE** [comment]
@Kagemaru das funktioniert bei mir leider noch nicht. Test Case: [hier](https://mitwirken.integ.stadt-zuerich.ch/processes) das Thema "Verkehr" auswählen. Es sollte nur der VBZ Testprozess erscheinen.

**Comment by Kagemaru** [comment]
Ticket für Filter entfernen Bug: https://github.com/decidim/decidim/issues/8611

**Comment by larsUE** [comment]
@Kagemaru Kannst du abschätzen, was es bedeutet, dies zu flicken? Auf Meta.Decidim funktionieren die Filter (siehe: https://meta.decidim.org/processes) ausser, wie von Andres im Ticket https://github.com/decidim/decidim/issues/10552 erwähnt, in den Prozessgruppen. Könntest du eine Aufwandschätzung machen für 
a) Flicken bei /processes (nur Zürich)
b) Flicken bei Process groups (inkl. PR bei Decidim, aufbauend auf `release/0.27-stable`

**Comment by larsUE** [comment]
Noch zur Info: In Luzern funktioniert dies wie gewünscht: https://dialogluzern.ch/processes?filter%5Bscope_id%5D%5B%5D=21&filter%5Barea_id%5D=

**Comment by Kagemaru** [comment]
Dies scheint ein Problem mit der modifizierten Gruppenanzeige zu sein. Ich schätze 1–2 Tage Arbeit.

**Comment by larsUE** [comment]
Nach Absprache mit Werner kann das umgesetzt werden.

**Comment by larsUE** [comment]
Bitte Zusammenhang mit https://github.com/decidim/decidim/pull/10829 prüfen - allenfalls entsteht da bereits ein Fix.

**Comment by larsUE** [comment]
Und same mit diesem hier: https://github.com/decidim/decidim/pull/11248

**Comment by larsUE** [comment]
Die oben erwähnten PRs sind sind teil von Decidim V0.27.4. Bitte also zuerst https://github.com/puzzle/decidim-zuerich/projects/4#card-90016669 ausführen, und danach dieses Ticket nochmals anschauen :)

**Comment by larsUE** [comment]
Ebenfalls potenziell relevant: https://github.com/decidim/decidim/pull/11438

**Comment by Kagemaru** [comment]
Ich bin nun etwas weiter. Wenn ich das Template `index.html.erb` entferne geht es.

Mit dem Template kommt das ganze Layout zurück.

Wenn ich aber gleichzeitig noch `index.js.erb` überschreibe mit dem gleichen Content wie in decidim, funktioniert es wieder normal.

Aber anstatt dies weiter zu verfolgen, würde ich aus dem Template override gerne ein Deface override machen. Dann sollten wir dieses Problem in Zukunft nicht mehr haben.

**Comment by Kagemaru** [comment]
Mit deface funktioniert jetzt die .js Antwort wieder. Aber leider verhält sich der Filter noch nicht richtig.

Da ich morgen nicht für Puzzle arbeite, kannst du, @carlobeltrame morgen mal reinschauen, ob du es zum Laufen bringen kannst?

**Comment by carlobeltrame** [comment]
Ich konnte es jetzt fixen. Wenn man einen Filter auswählt und den Dialog schliesst werden jetzt die korrekten Teile der Seite neu geladen.
Wenn man danach auf die Filter Pille klickt, verschwindet diese und es hat keine Wirkung. Das ist aber auch auf DialogLuzern und sogar auf MetaDecidim so. Darum habe ich das vorerst noch nicht weiter verfolgt.
Fix ist jetzt auf INT aufgeschaltet.

**Comment by larsUE** [comment]
Ich habe das ebenfalls getestet und komme zum gleichen Schluss wie du @carlobeltrame . Alles andere funktioniert. Da im Redesign eh ganz viele Bug fixes kommen und die Filter auch anders aussehen, bitte keine Zeit mehr aufwenden.
