### ISSUE TITLE
Seite «Profileinstellungen» löst einen 500er aus

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#373]
Die Seite https://mitwirken.integ.stadt-zuerich.ch/notifications_settings löst bei mir einen 500er aus. Hat wahrscheinlich mit der neu eingeführten Push-Notifikationen zu tun

**Comment by Kagemaru** [comment]
Fehlende Einstellungen für die neuen Vapid Notifications. Hinzugefügt und wartet auf Deployment.
