### ISSUE TITLE
Alle Meeting-Komponenten lösen einen 500er aus

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#374]

**Comment by Kagemaru** [comment]
Hängt zusammen mit der entfernten Suche, die wir ab und an referenzieren. Zum Beispiel in den LatestBlogPosts (die ich vorher schon gefixt hatte) und in den Meetings. Ist hier nun auch gefixt und wartet auf das nächste Deployment.

**Comment by larsUE** [comment]
Bestens!
