### ISSUE TITLE
Prozess Weiterleitung funktioniert nicht mehr 

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#376]
Die [automatischen Prozessweiterleitung mittels Konvention](https://github.com/puzzle/decidim-zuerich/issues/152) in der Ankündigung läuft seit dem Update nicht mehr.

**Comment by Kagemaru** [comment]
Die CSS Klassen haben sich geändert. Der fix ist im Moment am builden für auf die INT.

**Comment by larsUE** [comment]
Alles bestens!
