### ISSUE TITLE
Meetings / Veranstaltungsübersicht führt auf Decidim 0.27 zu einem 500er Serverfehler

### ISSUE THREAD

**Issue by bsantschi** [puzzle/decidim-zuerich#377]
Klick auf Veranstaltungsübersicht auf INT führt zu 500er Fehler.

**Comment by Kagemaru** [comment]
Ist gefixt, kommt auf INT im nächsten Build.

**Comment by larsUE** [comment]
@Kagemaru Das funktioniert bei mir noch nicht, kannst du nochmals schauen?
https://test.meinquartier.zuerich/meetings

**Comment by carlobeltrame** [comment]
Ist erledigt. Es war derselbe Fix wie bei #374. Merci @larsUE für den Tipp.

**Comment by larsUE** [comment]
Juhuu, danke! Habs bereits getestet, alles i.o.
