### ISSUE TITLE
Bilder Upload auf Testumgebungen geht nicht

### ISSUE THREAD

**Issue by bsantschi** [puzzle/decidim-zuerich#378]
Ich schaffe es nicht auf den Testumgebungen von MeinQuartier.Zuerich oder «Mitwirken an Zürichs Zukunft» Hauptbilder oder Kachelbilder für neue Prozesse hochzuladen. Geht das bei euch? Könntet ihr das testen und ggf. flicken? Ich bin euch dankbar, wenn ihr das möglichst rasch anschaut.
 
Merci vielmal und liebe Grüsse
Werner

**Comment by Kagemaru** [comment]
Das Problem waren benötigte CORS Regeln auf unseren S3 Buckets. Ausserdem musste ich WAF Regeln anpassen aufgrund von einem leeren body Feld im POST request.

**Comment by larsUE** [comment]
Getestet und funktioniert
