### ISSUE TITLE
403 bei Upload von reinem Text

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#379]
Wenn ich ein neues Result der Stadtidee hinzufüge, kriege ich wiederholt einen 403, obwohl ich nur Text hochlade.

Betroffene Komponente (neues Ergebnis erstellen): https://mitwirken.stadt-zuerich.ch/admin/participatory_processes/stadtidee/components/313/manage/

Betroffener Text ist angehängt.
[tauschmobil.docx](https://github.com/puzzle/decidim-zuerich/files/11275297/tauschmobil.docx)

Erwartetes Verhalten: kein 403

EDIT: Auch auf der INT wird ein 403 ausgelöst

**Comment by Kagemaru** [comment]
Wir haben ausnahmsweise mal wieder eine neue WAF Regel ausgelöst. Ich habe die Ausnahme hinzugefügt.

Alle Umgebungen benötigen einen kleinen Unterbruch (<30 Sekunden), um die neue Regel zu verbreiten.

STZH-INT und STLU-INT wurden bereits erledigt und sind bereit zum Testen.

Todo:
- [x] STZH-INT
- [x] STLU-INT
- [ ] STZH-PROD
- [ ] STLU-PROD

**Comment by larsUE** [comment]
Danke dir! Gerne auf Prod ausrollen.
