### ISSUE TITLE
Miro-Einbettung als Component

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#38]
Möglichkeit, Miroboards einzubetten als Komponente für Beteiligungsprozesse. Vielleicht kann das Jitsi-Modul angepasst werden? https://github.com/alabs/decidim-module-jitsi-meetings

**Comment by carlobeltrame** [comment]
Nur mal vorab, dass euch das schon mal bewusst ist:
> The option to share boards for public editing is available on paid plans only.

https://help.miro.com/hc/en-us/articles/360016335640-Embedding-Editable-Boards-into-Websites

**Comment by larsUE** [comment]
Jap, so teuer ist Miro ja zum Glück nicht. Aber was denkst du, technisch sollte das möglich sein?

**Comment by carlobeltrame** [comment]
Ja, es sollte sicher machbar sein. Auf jeden Fall sollten wir ein neues Modul dafür erstellen, was wir halt noch nie gemacht haben. Aber sieht wirklich so aus als könnte man das meiste beim Jitsi-Modul abschauen.

**Comment by carlobeltrame** [comment]
Habe gerade entdeckt dass das decidim awesome Modul auch eine iframe Komponente mitbringt: https://github.com/Platoniq/decidim-module-decidim_awesome/#8-fullscreen-iframe-component

Damit sollte die Einbindung von einem Miro-Board in einen Prozess oder ein Gremium möglich sein. Probierts doch mal aus sobald #35 gemacht ist.

**Comment by larsUE** [comment]
<img width="948" alt="Bildschirmfoto 2021-02-09 um 09 47 40" src="https://user-images.githubusercontent.com/60926257/107338767-37f2ff80-6abc-11eb-9540-7fabbf728075.png">

Works like a charm!
