### ISSUE TITLE
Datenverlust bei Umfragen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#380]
Wir haben einen merkwürdigen Bug bei uns auf den Umfragen. Wenn ich eine Frage mit einer Bedingung habe, dann wird die Antwort der Bedingung nicht gespeichert, wenn eine Fehlermeldung in der Umfrage aufgetreten ist.

### Ausführliche Beschreibung

**Schritt 1: Umfrage mit einer bedingten Frage erstellen**
![Bildschirm­foto 2023-04-20 um 09 30 31](https://user-images.githubusercontent.com/60926257/233292757-c2b4a404-0deb-4092-a6f9-4dbf0d3c05c1.png)

**Schritt 2: Umfrage inkl. Bedingung und Fehler in erster Antwort ausfüllen**
![Bildschirm­foto 2023-04-20 um 09 31 41](https://user-images.githubusercontent.com/60926257/233293051-7f558cd3-106f-4c1b-a030-c956af431d26.png)

**Schritt 3: Umfrage abschicken und Fehler provozieren**
![Bildschirm­foto 2023-04-20 um 09 32 47](https://user-images.githubusercontent.com/60926257/233293289-fb8d13d5-9123-47c3-8c5c-2b1a957c5d09.png)

**Schritt 4: Fehler beheben und Umfrage erneut abschicken**
![Bildschirm­foto 2023-04-20 um 09 33 36](https://user-images.githubusercontent.com/60926257/233293493-d0f54e5a-eecc-49bd-b92a-24cc7aff7ccf.png)

**Schritt 5: Antworten prüfen, feststellen, dass die Antwort der Bedingung nicht gespeichert wurde**
![Bildschirm­foto 2023-04-20 um 09 35 11](https://user-images.githubusercontent.com/60926257/233293896-068d9389-5fb7-4db3-bcca-2a7b047e42f6.png)

### Test Cases

Getestet hier: https://mitwirken.integ.stadt-zuerich.ch/admin/participatory_processes/testlars/components/394/manage/
- Lokales Caching von Decidim Awesome aktiviert und deaktiviert -> Fehler tritt in beiden Cases auf
- Testing auf INT (V0.27) und Prod (V0.26)-> Fehler tritt in beiden Fällen auf
- Testing auf unterschiedlichen Plattformen -> Fehler tritt nur im Zürcher System, nicht aber auf decidim.swiss auf (getestet auf testen.gemeinsamer.space)

### Vermutung
Ich vermute deshalb, dass dieser Error mit den von uns eingeführten Dropdown/Sort Funktion #351 zusammenhängt.

**Comment by larsUE** [comment]
Ich kann es auch nur auf den ZH INT und PROD nachstellen. Merkwürdig! Wichtig ist, dass du zuerst einen Fehler auslöst, bevor du die Umfrage abschickst. Wir hatten es nun bereits in verschiedenen Umfragen, dass deshalb keine Daten gesammelt wurden für einzelne Fragen.

**Comment by larsUE** [comment]
@Kagemaru evtl. reicht ein update auf 27.3: https://github.com/decidim/decidim/pull/10448

**Comment by Kagemaru** [comment]
Good catch, deployed auf INT

**Comment by larsUE** [comment]
Super, funktioniert nun alles :)
