### ISSUE TITLE
Kartenfehler: Geodaten Identifier wechseln

### ISSUE THREAD

**Issue by bsantschi** [puzzle/decidim-zuerich#382]

**Comment by innosmith** [comment]
Danke fürs schnelle fixen @carlobeltrame. Ist es korrekt, dass du es auf PROD umgesetzt hast und das HTML-Snippet auf INT kopiert hast? Wenn ich auf INT das richtige Quartier anwähle, wird der richtige Quartierfilter unmittelbar auf PROD anstatt INT angezeigt. In wenigen Fällen verwirrt das Admins auf INT ev. Da die Filter auf INT und PROD unterschiedlich sind, müssen eigentlich zwei Versionen des HTML-Snippets gepflegt werden. Hättest du ev. das Original noch von INT und könntest das analog adaptieren?

**Comment by carlobeltrame** [comment]
Ah, das hatte ich nicht bedacht. Ich habe dein per Mail geschicktes Snippet angepasst und an beiden Orten eingefügt. Lieber so rum als anders, aber das fixe ich natürlich auf INT noch.
