### ISSUE TITLE
Neue Crowdin Keys laden

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#385]

**Comment by carlobeltrame** [comment]
Das können wir leider nicht. Crowdin Übersetzungen werden von Decidim mit den Releases zusammen gebündelt. Die Übersetzungen müssen ja auch jeweils zu den Keys passen, welche sich bei jedem Decidim-Release ändern können.

Wenn du spezifische Übersetzungsänderungen schon haben musst bevor sie bei Decidim released werden, müsstest du mir eine Liste machen, oder sie wie bisher im Term Customizer eintragen.

**Comment by larsUE** [comment]
Ok, danke für die Rückmeldung. Dann ziehe ich bei Bedarf per Term Customizer noch Begriffe nach. Da V0.27.3 erst am Donnerstag released wurde sollten wir sowieso auf einem sehr aktuellen Stand sein.
