### ISSUE TITLE
Umfrageresultate können nicht zurückgesetzt werden.

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#389]
Wenn man die Umfrageresultate löschen möchte (d.h. Häckchen bei «Resultate bei Veröffentlichung der Komponente» setzen, dann Komponente ent- und neu veröffentlichen), dann werden die Resultate nicht gelöscht. Kann auf INT und PROD getestet werden, z.B. hier: 

https://mitwirken.integ.stadt-zuerich.ch/admin/participatory_processes/testlars/components/394/manage/

**Comment by larsUE** [comment]
Bitte auch Zusammenhang mit https://github.com/puzzle/decidim-zuerich/commit/ce8e4dc051865012743651000d2b41bfccabc705 prüfen

**Comment by wernerliechtenhan** [comment]
Hallo Zusammen, 
Solange dieser Bug besteht, kann die Umfrage nicht mehr angepasst werden. Deshalb sehr dringend. Danke euch fürs beheben. LG

**Comment by larsUE** [comment]
Der Fehler tritt auch auf demo.decidim.org auf, ist also ein Bug in V0.27.2

**Comment by larsUE** [comment]
Ich habe zusätzlich ein Ticket bei Decidim eröffnet: https://github.com/decidim/decidim/issues/10895

**Comment by larsUE** [comment]
Nach weiterem Testing stellt sich heraus, dass das Feature abgeändert wurde. Allerdings bin ich mir nicht sicher, ob das absichtlich so gemacht wurde. Und zwar funktioniert das Löschen mit folgendem Vorgehen, vorausgesetzt, das Häckchen bei der Checkbox ist aktiviert.
1. Umfragekomponente unveröffentlichen
2. Neu: Umfrage speichern (und ggf. bearbeiten).
3. Umfrage veröffentlichen
Da dieses Vorgehen auch in Ordnung ist, bitte nicht am Ticket arbeiten.
