### ISSUE TITLE
Städtisches CI/CD anpassen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#39]
Anpassung an städtisches CI/CD. Abklären mit Verantwortlicher Stadt Zürich, ev. UX Designer holen für weitere visuelle Upgrades.

**Comment by maximilianstern** [comment]
Und allenfalls checken, was sich von https://omastadi.hel.fi/ (Helsinki-Instanz von Decidim) übernehmen lässt.

**Comment by swaldis** [comment]
Styleguide
Die Referenz-Seite ist unter https://dece.stadt-zuerich.ch/refpage/

Header + Footer
Diese sollen ja 1:1 von der Stadt übernommen werden, inklusive gleichen Objekten / Menüs, pixelgenau. Ich gehe davon aus wir machen über den decidim-Header und unter den decidim-Footer noch Header und Footer der Stadt Zürich, da ja decidim sonst nicht dieselben Objekte / Menüs im Header hat.
Zudem: Pixelgenauigkeit über verschiedene Browser und Bildschirmgrössen hinweg existiert nicht, auch die exakt selbe Schriftart wird auf verschiedenen Browsern und Betriebssystemen leicht unterschiedlich gerendert. Wir können höchstens das CSS der Stadt für den Header exakt übernehmen.
Aufwand: 1PT.
Generell: Bei einigen der gewünschten Änderungen muss viel View Code (der für die Ansichten verantwortlich ist) kopiert und nur sehr leicht angepasst werden. Diese Änderungen sind unten mit Entfernung von decidim markiert. Bei decidim-Upgrades wird oft der Original-View-Code für neue Features angepasst, und wir müssen dann jeweils alle unsere Modifikationen auf die neuen Originale erneut anwenden, damit die neuen Features auch bei uns funktionieren. Solche Änderungen sollten somit wo möglich vermieden werden, und wo wirklich nötig ist bei jedem decidim-Upgrade pro solche Änderung mit ca. 0.5 - 1PT Aufwand zu rechnen.
CSS der Stadt übernehmen
Es gibt in CSS keine direkte Entsprechung zum Konzept “anschnallen und mappen”. Wir können das CSS einfach ins Projekt übernehmen, es ist aber zu erwarten dass sehr vieles nicht einfach out of the box wie gewünscht aussehen wird. Es kommt zudem darauf an wie das CSS der Stadt aufgebaut ist.
•	Wenn das CSS der Stadt Element-basiert ist (wie es im Styleguide aussieht), dann besteht das Risiko dass irgendwo in einer Ecke von decidim ein Element (z.B. <p>) anders verwendet wird als wir es erwarten, und das kann auch mit jeder Neuerung an decidim wieder aufs Neue auftreten.
•	Wenn das CSS der Stadt auf CSS-Klassen basiert, wäre dieses Risiko zwar kleiner, dafür hätten wir mehr Aufwand bei der Einführung, und die Entfernung von decidim wäre grösser.
Aufwand falls Element-basiert: 0.5PT + 1.5PT manuelle Tests und entsprechende Anpassungen, + 0.5PT jedes Mal wenn in Zukunft ein neues Feature von decidim ein HTML-Element auf unerwartete Art einsetzt
Aufwand falls CSS-Klassen-basiert: 0.5PT + 3PT Anpassungen an den wichtigsten Stellen.
Icons
Es ist schwierig, abschliessend nach allen Icons zu suchen. Es gibt soweit ich weiss keinen zentralisierten Ort an dem die Icons einmalig ausgetauscht werden könnten, und auch wenn es diesen gäbe gäbe es auch kein garantiertes 1:1 Mapping für jedes Icon von decidim zu einem Icon der Stadt Zürich. Man muss also fast jedes Icon einzeln anschauen, auch wieder wenn neue Features zu decidim hinzukommen. Bei einer grossen Menge ersetzter Icons steigt zudem die Entfernung von decidim
Aufwand: Pro 5 ersetzte Icons 0.5PT, bei decidim-Upgrades können neue Icons auftauchen.

Keine Kapitälchen
Aufwand: Pro 5 ersetzte Stellen 0.5PT

Texte links angeschlagen
Muss wie bei den Icons für jeden Text einzeln gemacht werden. Entfernung von decidim steigt.
Aufwand: Pro 5 abgeänderte Textstellen 0.5PT, bei decidim-Upgrades können neue Stellen auftauchen.

Schriftart HelveticaNeueLTW01
Aufwand: Einmalig 0.5PT

Farben übernehmen, inkl. Hintergründe und Ampelfarben
Aufwand: Einmalig 1PT
Accessability + hover-Hervorhebung
Aufwand: Einmalig 0.5PT

Site Templates
Bin nicht sicher ob ich genau verstehe was hier gemeint ist. Die Kacheln (Cards) sind in Schriftgrössen und Formatierung bereits standardisiert. Jede Anpassung die wir machen wirkt sich auf alle Kacheln aus. Die Grösse der Bilder oben an den Kacheln variiert je nach hochgeladenem Bild. Wir können das auch standardisieren, es braucht aber Mehraufwand falls z.B. kein Bild hochgeladen wird, und es müssen alle Bildschirmgrössen bedacht werden.
Aufwand Erarbeitung 2PT, Umsetzung je nach Resultat 0.5 - 1.5PT

**Comment by wernerliechtenhan** [comment]
Lasst uns möglichst bald einen ersten Wurf erarbeiten insb. mit Header und Footer und allem, das nicht bei jedem Update wieder von neuem angepasst werden muss. Dann besprechen wir dies mit Claudio Sparascio (CI/CD-Verantwortlicher). 

In einem zweiten Schritt kann sich UE weiteren Verbesserungen des Look & Feel annehmen, z. B. mit Elementen der Helsinki-Plattform.

**Comment by wernerliechtenhan** [comment]
Die neue Energieplattform der Stadt Zürich ist auch noch ein gutes Vorbild für unser Decidim-Layout: https://www.stadt-zuerich.ch/energie.

**Comment by larsUE** [comment]
Ich habe mal die [Referenzseite](https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/index.html) abgesucht und herausgepickt, welche Elemente wir übernehmen könnten:

**Header** -> falls möglich: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/header/header.html
-> falls pixelgenaue Umsetzung nicht möglich (siehe oben)
- Suchfeld: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/searchfield/searchfield.html
- Persönliches Profil: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/myaccountaccess/myaccountaccess.html
- Sprachwahl: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/langnav/langnav.html
- Logo (muss vergrössert werden): https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/logo/logo.html
- Top-Menu: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/topnav/topnav.html

**Footer**
- Generell (genauere Anpassungen folgen): https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/footernavigation/footernavigation.html

**Box Grid** (Ideen, Debatten, Events, Übersicht Beteiligungsprozesse)
- Normaler Grid: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/teaserlist/teaserlist.html, oder https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/subpageslist/subpageslist.html
- Hervorgehobener Prozess: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/pagetitlemicrosite/pagetitlemicrosite.html

**Forms**
- File Upload: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/index.html
- Sonst: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/form/form.html

**Blog**
- https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/blog/blog.html

**Notifizierungen**
- Alerts (ev. positiv (grün) und negativ (rot) farblich hinterlegen): https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/alert/alert.html

**Weiteres**
- Download-Link File: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/downloadlink/downloadlink.html; Beispiel: https://quartieridee.ch/processes/quartierideeWipkingen/f/44/projects/45 (obwohl ich die Decidim-Version schöner finde)
- Button: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/button/button.html
- alternativ: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/cta/cta.html
- Error-Page (404): https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/pages/error_page/error_page.html
- Login-Page: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/pages/general_login_page/general_login_page.html

**Wünsche** (wäre nice to have)
- Bannerbild als Karussel (würde aber einige Änderungen an Decidim selbst bedingen): https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/carousel/carousel.html
- Breadcrumb: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/breadcrumb/breadcrumb.html

**Comment by skzind** [comment]
> Die neue Energieplattform der Stadt Zürich ist auch noch ein gutes Vorbild für unser Decidim-Layout: https://www.stadt-zuerich.ch/energie.

...ist nicht wirklich ein Beispiel, da zu 100% über das interne AEM WCMS produziert.

**Comment by larsUE** [comment]
Hier finden sich erste Infos zu den geplanten Decidim-Style Anpassungen. Gottseidank nichts bahnbrechendes, dass bei uns alles umstellen würde, sonder eher ein Aufräumen und Zugänglicher-Machen.

*Test-Umgebung*
https://decidim-design.herokuapp.com/public/#

*Workshop*
https://www.youtube.com/watch?v=iaMPPSo7Yzc

cc @carlobeltrame
