### ISSUE TITLE
Umfrage kann nicht abgesendet werden

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#390]
Wenn ich Umfragen ausfülle, welche ein Mandatory Text-Feld aufweisen, dann erscheint zwar sofort eine Fehlermeldung – dies geht aber schnell vergessen. Ich kann aber Ende dennoch die Umfrage absenden, den «Sind Sie sicher?» Dialog bejahen und dann geschieht nichts: Keine Fehlermeldung und keine Erfolgsmeldung.

https://github.com/puzzle/decidim-zuerich/assets/60926257/5a5046e1-7fb2-4cc1-968f-47fdbed0dd44

_Hinweis: bei so kleinen Umfragen mag das nicht dramatisch wirken. Aber grösseren Umfragen mit Trennzeichen und Bedingung tritt dieser Fehler sehr schnell ein und es ist dann unklar, wo sich der Fehler befindet._

Bei allen anderen Test-Cases läuft es wie folgt ab: Ich fülle die Fragen nicht/fehlerhaft aus, versuche die Umfrage auszufüllen und erhalte dann die Fehlermeldung, als Banner und direkt bei der Frage.

https://github.com/puzzle/decidim-zuerich/assets/60926257/6f683765-b248-4d4f-9183-346f224fe376

Als erwartetes Verhalten möchte ich, dass ich entweder beim Absenden bei allen Fragen eine Fehlermeldung kriege (wohl einfacher umzusetzen) oder die Umfrage aber gar nicht absenden kann, solange noch Fehlermeldungen bestehen.

Dies wurde auch auf dem [Decidim-Github](https://github.com/decidim/decidim/issues/9649) bereits bemerkt. Wenn ihr den Fehler behebt, gerne also gleich ein PR bei Decidim eröffnen.

**Comment by Kagemaru** [comment]
@larsUE 
Ich habe herausgefunden, dass die Javascript Validierung von `required="required"` Textfeldern nicht funktioniert. Es würde mehr Zeit in Anspruch nehmen, den Grund herauszufinden.

Was ich jedoch mit diesem Wissen machen konnte, war die Deaktivierung der Validierung zu fixen (dies sieht nach einem unbeabsichtigten Verhalten auf Seiten Decidim aus). Nach diesem Fix konnte ich Umfrage-Textfeldern einen weiteren Parameter hinzufügen, der die JS Validierung deaktiviert.

Somit wird nun nach dem Absenden alles geprüft und bei Fehlern werden die bekannten Fehler angezeigt.

Das Update ist nun auf der INT Umgebung eingespielt.

**Comment by larsUE** [comment]
Danke, das fixed es mal soweit :) Ich habs getestet. So was ähnliches hab ich mir gedacht. Bei Mandatory Fields beobachten wir noch eine Menge weiterer Glitches (z.B. dass die Umfrage manchmal trotz leerem *-Feld abgeschickt werden kann).

Könntest du deine Findings bei Decidim eingeben? Z.B. https://github.com/decidim/decidim/issues/9649 oder hier https://github.com/decidim/decidim/issues/10815 ? Ich bespreche nächste Woche mit Werner, ob wir es selbst fixen möchten.

**Comment by BigSnicker** [comment]
Gibt es Pläne, dies in decidim/decidim zu integrieren?

**Comment by larsUE** [comment]
@BigSnicker Probably not, because this is only a workaround for a broken feature, not a fix to it.
