### ISSUE TITLE
Bilder werden in Umfragen gelöscht

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#396]
**Folgendes Verhalten**: Ich kann in Umfragen Bilder hochladen (z.B. im Beschreibungsfeld). Wenn ich die Umfrage abspeichere und im Frontend anschaue, wird das Bild auch angezeigt. Wenn ich nun eine weitere Anapssung an der Umfrage vornehme, werden die bestehenden Bilder gelöscht & es erscheinen nur die Bilder die ich in diesem Edit neu hinzugefügt habe.

**Mögliche Zusammenhänge:** Zusammenhang mit automatischen Übersetzungen prüfen.

**Nachstellbar hier:** https://mitwirken.stadt-zuerich.ch/processes/frk-zhwest/f/457/surveys/149
1. Bild in ein Feld hochladen (ob manueller Upload oder Drag & Drop spielt keine Rolle).
2. Umfrage speichern, Forntend anzeigen, Bild sehen
3. Umfrage erneut bearbeiten und in einem anderen Feld ein Bild hochladen.
4. Umfrage abspeichern und feststellen, dass im Front- und Backend nur noch das neu hinzugefügte Bild angezeigt wird.

**Comment by Kagemaru** [comment]
Das Handling der Textfelder ist hier etwas seltsam.
Es zählt eine Textbox, in der nur ein Bild drin ist als leeres Feld.
Und ein leeres Feld wird natürlich beim nächsten Speichern auch als solches gespeichert.

Der einfachste ~Fix~ ist es, zusätzlich Text zum Bild einzugeben.
Der Code Fix ist etwas komplizierter, da dieses Handling wahrscheinlich irgendwo im Javascript liegt.
Wahrscheinlich ist es hier einfacher, diesen Bug zu melden.

**Comment by larsUE** [comment]
Super cool, danke! Das funktioniert. Kannst du mit den nötigen Tech Specs ein Issue bei Decidim eröffnen? Ich close hier mal.
