### ISSUE TITLE
Upgrade 0.27.4

### ISSUE THREAD

**Issue by bsantschi** [puzzle/decidim-zuerich#397]
Hier in Progress: https://github.com/puzzle/decidim-zuerich/pull/398

**Comment by larsUE** [comment]
Es fehlt noch das Deutsch Sprachfile...

Aus Crowdin:
[de-DE.yml.zip](https://github.com/puzzle/decidim-zuerich/files/12549418/de-DE.yml.zip)

**Comment by larsUE** [comment]
0.27.4 ist auf INT, bleibt noch in Progress, weil einzelne JS Dependencies aktualisiert werden müssen. Das betrifft den Release aber nicht.

**Comment by larsUE** [comment]
Stand Testing: 

- [ ] Karten sind noch defekt. Allenfalls fehlt dieser Fix von @carlobeltrame ? https://github.com/stadtluzern/decidim-ocl/commit/4a3da6dfaf1b3ffb61e86e20c1bcb922895a713e Zusätzlich finde ich keine Karteneinstellungen im System-Backend. Gibts das nur auf Decidim.Swiss?

**Comment by carlobeltrame** [comment]
@larsUE ich habe mal den äquivalenten Fix von Luzern übernommen. Lokal hatte ich gemischte Ergebnisse, also bitte noch gut testen ob es funktioniert wo ihr es braucht.
Die Karteneinstellungen im System-Backend haben wir nur für decidim.swiss umgesetzt, weil unter den züricher Tenants bisher noch kein Bedarf für unterschiedliche Karteneinstellungen vorhanden war.

**Comment by larsUE** [comment]
OK, danke! Irgendwie funktioniert es aber noch nicht, z.B. auf der Startseite: https://mitwirken.integ.stadt-zuerich.ch
oder bei den Ideen: https://mitwirken.integ.stadt-zuerich.ch/processes/stadtidee/f/63/

**Comment by carlobeltrame** [comment]
Ja, ich sehe es auch gerade. Der Fehler ist immer noch derselbe, der eigentlich vom luzerner Fix hätte behoben werden müssen. Ich schau nochmals genauer rein.

**Comment by carlobeltrame** [comment]
So, jetzt konnten wir korrekt deployen. @larsUE bitte erneut testen.

**Comment by larsUE** [comment]
Perfekt! Ich konnte alle Cases mit Maps durchtesten und es funktioniert wieder wie gewünscht. Ihr könnt den Prod Release nun durchführen.
