### ISSUE TITLE
Einbau Open Source Politics Weiterentwicklung (Umfragen mehrfach ausfüllen)

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#399]
As soon as PR is submitted, please check &  deploy on INT.

(In english in case there are any problems later on)

**Comment by bsantschi** [comment]
Heute im Laufe des Tages soll das Gem von Open Source Politics für das mehrfache der Umfrage kommen. Bitte einbauen und auf INT deployen.

**Comment by simonaszilinskas** [comment]
Hi! To add the gem: 
`gem "decidim-survey_multiple_answers", git: "https://github.com/alecslupu-pfa/decidim-module-survey_multiple_answers", branch: "main"
`
Release in rubygems upcoming.

**Comment by larsUE** [comment]
@Kagemaru The gem has been updated with the fixes and we can go ahead and install ist

**Comment by larsUE** [comment]
@simonaszilinskas Does the main branch contain the current fix? Or should we install [fix/multiple-answers](https://github.com/alecslupu-pfa/decidim-module-survey_multiple_answers/tree/fix/multiple-answers) instead?

**Comment by simonaszilinskas** [comment]
@larsUE for now it hasn't been merged, we're waiting for a merge after our last devs approve it today. If you need it today, you can use that branch, if you need it tomorrow, I think it will be merged into main.

**Comment by larsUE** [comment]
@simonaszilinskas Thanks!
@Kagemaru let's wait until tomorrow.

**Comment by wernerliechtenhan** [comment]
Von OSP ist gerade ein E-Mail gekommen mit einer definitiven Version: The definitive version of multiple survey answers was done and the release can be found here: https://rubygems.org/gems/decidim-survey_multiple_answers

**Comment by Kagemaru** [comment]
Erledigt und ist am deployen auf INT.
