### ISSUE TITLE
Token für Einladungen von 2 auf 7 Tage erhöhen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#400]
Einladungstokens (z.B. für private Prozesse oder Prozess-Admin Einladungen) für unregistrierte Nutzende laufen im Moment nach 2 Tagen ab. Das ist aus praktischer Sicht zu knapp (z.B. wegen Teilzeitarbeit, Ferienabwesenheiten) und beschert den Projektleitenden einen grossen Zusatzaufwand.

Können wir den Token auf 7 Tage hochsetzen? Wäre das aus Security-Sicht vertretbar?

**Comment by Kagemaru** [comment]
@larsUE ich kann das leider nicht nachstellen:
Diese Einladung habe ich heute verschickt und sie ist 2 Wochen lang gültig:

![image](https://github.com/puzzle/decidim-zuerich/assets/12155/45d09a8f-9c31-4835-aaab-7b2b93583e59)

Dies deckt sich auch mit den Standardeinstellungen deckt. Ist es bei dir anders?
