### ISSUE TITLE
Zugangscodes um Umfrage einmalig auszufüllen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#402]
Wir empfinden im Moment alle bestehenden Optionen zu Verifizierung der Nutzenden als sehr umständlich. Wir sind auf der Suche nach einer Lösung, bei dem eine fixe Anzahl Links/QR-Code verschickt werden können, und wenn diese QR Codes/Links geöffnet werden folgendes passiert:
- Registrierungs- bzw. Login-Fenster wird geöffnet (optional, u.U. auch anonyme Teilnahmen ermöglichen)
- Bei Anmeldung oder Kontoerstellung ist der User automatisch verifiziert und kann z.B. bei einer Umfrage mitmachen.
- Der Link / QR-Code bei erfolgreicher Verifizierung verfällt (bzw. bei Einstellung nach X Anwendungen)

Wir brauchen dies, damit wir z.B. eingeschränkte Umfrage (z.B. auf eine Strasse oder eine bestimmte Zielgruppe  bezogen) durchführen können. 

**Diskutierte & verworfene Lösungen**

- _Code per Post_: Standardverifikationsmethode von Decidim. Ist mühsam, weil zuerst ein Konto erstellt werden muss und erst dann ein Briefversand angefordert werden kann.
- _Automatische SAML-Abfrage via MeinKonto_: vorläufig nicht möglich, weil MeinKonto die Daten nicht verifiziert und gar keine vollständige Datensätze besitzt
- _Access Codes Modul_: Besteht bereits (und könnte dementsprechend ergänzt werden), es müssen aber die E-Mail-Adressen der Teilnehmenden bekannt sein. Was bei uns nicht der Fall ist.

**Mögliche Module, die ergänzt werden könnten**
- https://github.com/OpenSourcePolitics/decidim-module-half_sign_up
- https://github.com/Platoniq/decidim-module-access_codes

**Siehe auch**
- https://github.com/decidim/decidim/blob/develop/decidim-verifications/README.md
- https://decidim.org/modules/#auth

Gerne sind wir offen für weitere technische Lösungen!

**Comment by carlobeltrame** [comment]
Am naheliegendsten scheint mir, beim decidim-module-access_codes das Feature zu ergänzen dass die Access Codes nicht an eine Liste von E-Mails versendet werden müssen, sondern als QR-Code-Bilder heruntergeladen werden können. Dann hätten wir wohl "nur" ca. 4-5 PT Arbeit (Einarbeitung, E-Mail-loses Formular programmieren, QR-Codes generieren und zippen, herunterladen oder per Mail versenden, Kommunikation mit Platoniq und allfällige Verbesserungswünsche umsetzen). Allenfalls könnte da noch etwas dazukommen, falls euch dann die Frontend User Experience dieses Moduls nicht gefällt und wir da noch Dinge anpassen sollten (z.B. falls die QR-Codes gleich beim Scannen zur Verifizierungs-Seite mit ausgefülltem Code leiten sollen, braucht das noch Anpassungen).

Falls Platoniq gar nicht offen für dieses Feature wäre, scheint mir ihr Code vorbildlich genug, dass wir ein eigenes Modul auf Basis einer Kopie ihres Moduls machen könnten, und dort eure Wünsche umsetzen könnten. Der Aufwand ist dann wohl eher bei ca. 6-7 PT.

Anonyme Teilnahmen kann ich mir aktuell noch nicht vorstellen. Unterstützt denn das anonymous-proposals-Modul Verifikationen? Ich dachte bisher, Decidim bindet die Verifikationen direkt an User-Accounts. Also ohne User Account auch keine Verifikation..?
Automatische Verifizierung bin ich noch nicht sicher ob das möglich ist, ich glaube das wäre ein Sicherheitsrisiko wenn wir via einen QR-Code-Scan eine Status-Mutation (Verifikation) implementieren würden. Müssten wir noch detailliert anschauen wie wir das am besten machen.

**Comment by larsUE** [comment]
Eben gesehen: Die Decidim Roadmap sieht den Einbau eines QR-Code Generators zur Anmeldung an Meetings vor, ev. kann man diese Funktion gemeinsam nutzen, bzw. wir sollten mit ihnen abklären, ob es Synergien gibt:

> [DIT29] [Meetings] Generate QR codes for managing registrations/attendance at a meeting and design a backoffice system for mobile-based attendance tracking at the meeting.

https://github.com/orgs/decidim/projects/22?pane=issue&itemId=34383425

Zusätzlich sollten wir auch die Sign-Up Improvements berücksichtigen: 
> [DIT23] [Registration] Improve registration and verification flow: 1) Reduce the steps. 2) Invite participants to verify themselves upon completing registration and be able to assign one or multiple verifications, all configurable within the system.
> [DIT24] [Registration] Standardize direct verification for one-time participation. Enable ephemeral user verification, meaning "direct verification without registration for one-time participation," and after participation, invite the participant to register. This feature can be activated/deactivated in different participation spaces.
> [DIT25] [Registration] [BCN] Integration with digital identity verification systems such as idCAT Mòbil.
https://github.com/orgs/decidim/projects/22?pane=issue&itemId=34383439

@carlobeltrame die erwähnten "ephemeral user verification" wären das, was ich mir unter der anonymen Teilnahme vorgestellt habe. Ist aber sicher nicht prioritär.

**Comment by larsUE** [comment]
**Zusammenfassung der Sitzung vom 14. November 2023**
### User journey Projektleitung
Nachdem meine Umfragekomponente erstellt wurde möchte ich definieren, wie viele Menschen teilnehmen sollen. Es wird eine Liste an Links erstellt, die ich zum Versand, beispielsweise physisch und mit QR-Codes versehen vorbereiten kann. Jeder QR-Code soll ein Mal zur Beantwortung der Umfrage genutzt werden können.

### User journey Teilnehmende
Ich erhalte einen QR-Code per Post und möchte teilnehmen. Wenn ich den Code einscanne werde ich direkt auf die Umfrage geleitet und kann sie absenden.

### 
Neu diskutierte Lösung: Es wird eine Funktion gebaut, mit der man im Backend eine Einstellung hat, um eine gewisse Anzahl Codes/IDs und Links (ev. mit URL Shortener) zu erstellen, welche zur Teilnahme an einer Umfrage (in einem späteren Schritt/nach Bedarf dann weitere Komponenten) ermöglichen. Beim Aufrufen der Seite wird eine Decidim-externe Seite geöffnet, die ein Code beim User hinterlegt. Mit diesem wird auf die Umfrage weitergeleitet. Sobald die Umfrage abgeschickt wird, wird der Code gelöscht bzw. ist nicht mehr gültig. Bis dahin kann er beliebig oft geöffnet werden (aber die Umfrage kann nur einmal abgesendet werden). 

### Next steps / To-Do's

- [ ] @Kagemaru challenged die Idee mit @carlobeltrame und macht eine Aufwandschätzung.

- [ ] @larsUE klärt mit der Stadt Zürich ab, ob sie eigene Link-Shortener im Einsatz haben.

Ziel ist der Entwicklungsstart im neuen Jahr.

**Comment by larsUE** [comment]
Issue auf Meta.decidim: https://meta.decidim.org/processes/roadmap/f/122/proposals/17595

**Comment by nicolefreypuzzle** [comment]
Lieber Lars @larsUE 

folgend unsere Aufwandschätzung für dieses tolle, aber wie du gleich siehst auch relativ grosse Feature:

- Aufwand Umsetzung (inkl. Koordination, Syncs, etc.): 9 Tage
- Aufwand bei Release: ja, zusammenschliessen mit anderen Features/Fixes
- Aufwand bei nächstem Upgrade: 1-1.5 Tage je nach Notwendigkeit gem. veröffentlichtem Upgrade

Wie besprochen "Out of Scope" ist:
- Nach Ausfüllen der Umfrage Verlinkung zu User (Lösung: keine Verlinkung zu allfällig vorhandenem User)
- Deaktivierte / als gelöscht markierte QR-Codes können reaktiviert werden (Lösung: Nur löschen möglich, wenn gelöscht, dann gelöscht)
- Codes können aus Decidim versendet werden (Lösung: können exportiert und über Versandart ausserhalb Decidim verschickt werden)

Bei Fragen melde dich gerne. Und lass uns gerne wissen, ob wir die Umsetzung einplanen dürfen / das Budget dafür kriegen.
Liebä Gruess, Nicole

**Comment by nicolefreypuzzle** [comment]
Auftrag wird an PokeCode (über Drittentwicklungsbudget) vergeben. Task wird für Puzzle abgeschlossen.

**Comment by larsUE** [comment]
Wird durch #423 erledigt
