### ISSUE TITLE
Halböffentliche Prozesse ermöglichen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#405]
Wir möchten gerne Prozesse haben, die nur per Link aufrufbar sind.

Das bedeutet:
- Der Prozess wird nicht mit Suchmaschinen indexiert
- Der Prozess erscheint nirgends im Frontend (/processes oder /search), ausser von Menschen, die den Link haben
- Wenn der Link vorhanden ist, kann mit dem Prozess aber wie ein öffentlicher Prozess umgegangen werden

Dafür braucht es:
- Eine Einstellung im Backend unter "Visibility"
- Anpassungen, die oben genannte Kriterien erfüllen.

**Comment by carlobeltrame** [comment]
Ist das nicht schon genau das Verhalten, wenn man den Prozess nicht veröffentlicht? Du kannst dann ja trotzdem die "Vorschau" anschauen. Die URL des Prozesses kannst du dann teilen.

**Comment by larsUE** [comment]
Nicht ganz, weil man die URLs nur öffnen kann, wenn man selber (Prozess-)Admin-Rechte hat . Ansonsten kommt die "Zugriff nicht gestattet" Fehlermeldung. Es gibt aber die "Teilen"-Funktion, die einen Token erstellt. Dieser ist allerdings nur 24-Stunden gültig und muss dann manuell erneuert werden, was eine neue URL kreiert. Zusätzlich kann das Token nur für einzelne Komponenten, nicht für ganz Prozesse erstellt werden & ist nur für registrierte Nutzende (aber auch solche, ohne Backend-Zugriff) einsehbar. Aber grundsätzlich wäre genau das die Lösung, nur mit flexibleren Handhabung der Token Dauer, für ganze Prozesse und einsehbar für nicht-registrierte User.

![Bildschirmfoto 2023-11-02 um 10 18 35](https://github.com/puzzle/decidim-zuerich/assets/60926257/ad98c7ef-ad5f-43bd-88f1-fde69db25c32)

**Comment by larsUE** [comment]
@carlobeltrame wie versprochen hier noch die Links.
Einen neuen Token legst du an, in dem du in der Komponentenübersicht bei einer Komponente auf "Share" klickst:
<img width="1613" alt="Bildschirmfoto 2023-12-04 um 19 41 19" src="https://github.com/puzzle/decidim-zuerich/assets/60926257/81ed50a9-7928-4fbf-9ad7-d8686bc58f76">

Danach kannst du in den Komponenteneinstellungen zuunterst alle erstellten Tokens ansehen (siehe Bild im Kommentar oben). Beispiel auf INT (zuunterst): https://mitwirken.integ.stadt-zuerich.ch/admin/participatory_processes/testlars/components/394/edit
Der Block zum URL Sharing erscheint im Moment standardmässig, wenn die Komponente nicht veröffentlicht wurde. Dieses Verhalten ist sinnvoll und soll beibehalten werden.

Konkret wünschen wir uns also in den Komponenteneinstellungen, am besten dort wo die Übersicht der erstellten Tokens ist, zwei Einstellungen:
1. Eine Einstellung, wo die Dauer eines Tokens eingestellt werden kann
2. Eine Einstellung, die regelt ob man auf die URL nur registriert oder auch anonym Zugriff hat.

Diskussion auf Meta.Decidim: https://meta.decidim.org/processes/roadmap/f/122/proposals/17597

**Comment by carlobeltrame** [comment]
Grober Umsetzungsplan:
- [ ] [Standard-Gültigkeitsdauer](https://github.com/decidim/decidim/blob/develop/decidim-core/app/models/decidim/share_token.rb#L44) von Share Tokens von 1 Tag auf 100 Jahre überschreiben (0.5 PT)
  - [ ] Variante falls das später an Decidim Core contributet werden soll: Einstellung auf Komponente mit der die Gültigkeitsdauer in Tagen für neue Tokens dieser Komponente gesetzt werden kann (1 PT + die originalen 0.5 PT zum Überschreiben)
- [ ] Herausfinden, warum die [Permissions](https://github.com/Platoniq/decidim/blob/develop/decidim-core/app/permissions/decidim/permissions.rb#L166) den Zugriff scheinbar nur für eingeloggte User erlauben, und ändern (2 PT)
  - [ ] Pro Komponente konfigurierbar machen, ob Share Tokens für diese Komponente auch von anonymen Usern verwendet werden dürfen (1 PT)
Zu diesen total 4.5PT kommt noch 0.5PT für ein Deployment und bei Decidim Upgrades ca. 0.25 - 0.5 PT Aufwand das zu überprüfen und zu aktualisieren.

**Comment by nicolefreypuzzle** [comment]
Hallo @larsUE 

Folgend die Aufwandschätzung hierfür:
- Umsetzungsaufwand: 5 Tage
- Aufwand für Deployment: ja, zusammen mit anderen Features/Fixes
- Erhöhung Wartungsaufwände /-Kosten: 0.5 Tage

Lass uns gerne wissen, wenn wir das umsetzen dürfen.

Liebä Gruess,
Nicole

**Comment by nicolefreypuzzle** [comment]
Meeting für Entscheid Budget auf April verschoben worden
