### ISSUE TITLE
SMS Verifikation von Quartieridee übernehmen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#41]
SMS-Integration aus Quartieridee übernehmen: https://github.com/puzzle/quartieridee/issues/75

**Comment by bsantschi** [comment]
- Sollen wir denselben ASPSMS Account verwenden?
- Wie soll der SMS Text lauten? (bei der Quartieridee lautet er "Dein Zugangscode zur Quartieridee ist:")
- es wird etwas Aufwand anfallen um die Implementation so umzubauen, damit sie generisch verwendet werden kann

**Comment by larsUE** [comment]
Das müssten wir zu einem späteren Zeitpunkt klären. Es ist zur Zeit noch nicht klar, wie der Stadtidee-Prozess strukturiert wird und ob es die SMS-Verifikation überhaupt gebraucht wird. Deshalb mal im Backlog lassen.

Der SMS-Text und Absender-Name kann übrigens im Term-Customizer selbst angepasst werden.

**Comment by maximilianstern** [comment]
Hello Zusammen, zur Info: "Mein Konto" bietet bereits zwei Sicherheitsstufen: Einmal nur eMail und einmal mit SMS-Verifizierung. Wichtig wäre also, dass Decidim dies sieht... ich weiss nicht genau, wie sich das lösen lässt...

**Comment by larsUE** [comment]
Super, danke für die Info. Dann führen wir die Diskussion in #28 weiter

**Comment by bsantschi** [comment]
Anbindung wird nun doch gewünscht:

- ASPSMS anbinden
- Margot Gagliani organisiert Kontingent/Credentials
- nur +41 Nummern zulassen
- nur für Tenant "Mitwirken" (Quartierplattform evtl. später)

**Comment by carlobeltrame** [comment]
@larsUE Ist umgesetzt und auf Integration aufgeschaltet

**Comment by larsUE** [comment]
Habs getestet und es funktioniert wie gewünscht, danke! Die Keys sind die gleichen wie bei der Quartieridee?
Ich hatte zusätzlich noch Probleme mit der der http-Auth. Wenn ich ein Projekt auswähle (z.B. hier: https://mitwirken.integ.stadt-zuerich.ch/processes/stadtidee/f/47/budgets/3/projects) passiert zuuerst auch nichts, bis der Server ein Timeout meldet, dann kann ich alles wie gewünscht testen. Ist das gleiche wie https://github.com/puzzle/decidim-zuerich/issues/148

**Comment by carlobeltrame** [comment]
Translation Keys sind dieselben, aber mit `decidim_zuerich` statt `quartieridee`:
`de.decidim_zuerich.verifications.sms.aspsms_gateway.sms_text` und `de.decidim_zuerich.verifications.sms.aspsms_gateway.sms_originator_max_11_alphabetic_characters`

**Comment by carlobeltrame** [comment]
Ich weiss auch nicht wieso die Basic Authentication hier so ein Problem ist, bei der vorherigen Testumgebung von Decidim Zürich hatten wir doch nicht so viele Probleme? Oder haben wir da nicht so tief getestet?

**Comment by larsUE** [comment]
Supi, danke! Es ist kein neues Problem, sondern auch hier verursacht das Favicon.ico das Timeout. Von dem her wirklich das gleiche wie #148 . Soweit ich mich erinnere war die letzte Testversion von Decidim gar nicht HTTP-AUTH geschützt? Und ja, dort haben wir bestimmt nicht so tief getestet.
