### ISSUE TITLE
Captcha fragen erweitern

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#415]

**Comment by larsUE** [comment]
Mögliche Fragen:

- [ ] Nenne eine Farbe, die auf dem Schweizer Wappen vorkommt. (rot/weiss)
- [ ] Nenne die kleinste der folgenden Zahlen: 3 / 5 / 9 (3/drei) 
- [ ] Was ergibt 2 plus 3? (5/fünf)

**Comment by nicolefreypuzzle** [comment]
@larsUE soll die aktuell vorhandene Frage "Nenne eine Farbe des Zürcher Wappens." drin bleiben oder durch die drei genannten ersetzt werden?
PS. Ursprünglich lautete die Frage "Nennen Sie eine Farbe des Zürcher Wappens." - ich habe sie an die neuen Fragen angepasst umgeschrieben (Sie-Form > Du-Form).

**Comment by nicolefreypuzzle** [comment]
@larsUE auf INT,  kann getestet werden

**Comment by larsUE** [comment]
Die Fragen funktionieren, danke! Ich mache noch einen kleinen Change zur "Sie"-Form. Es fehlen auf der Registrierungsseite noch einige Übersetzungen, aber das besprechen wir in #419
