### ISSUE TITLE
Rückbau Prozesssortierung nach Prozessgruppen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#418]
Per Ticket https://github.com/puzzle/decidim-zuerich/issues/246 haben wir eine eigene Prozesssortierung eingeführt. Diese möchten wir nun rückgängig machen, da die Seite mit Installlation von Decidim GEO sehr lange wird und vorläufig in V0.29 die Scopes und Areas überarbeitet werden, was erweiterte Filtermöglichkeiten zulässt. Somit ist die Sortierung nach Prozessgruppen obsolet und wir würden gerne zum Standard zurückkehren.

Bitte abklären, welche der unten genannten Tickets auch nach Umbau der Entwicklung noch gebraucht werden, ansosnten ebenfalls zurückbauen.

### Relevante Issues
#246 
#366 

### Relevante commits (bitte überprüfen)
fcb3b43d72756568db445f132d3be10ae1a37708
ba3d376375fd5ea3227b08931158eb81aaa1a039 (eventuell)
a0459d6ad16b1f2c3b6df066ede88c8c47feb0b0 (eventuell)
b10af29a70c7c06ae6555a1b36c27f45e5f5f3ee
a9277cf89b73faf9d9b4e9941cdca39756ea047c
ffc05171c4479f3c46ac075614e2c22602851c13
35dd26998be38579a9dd5d33c0b64f75d0c0515c
c31d9691d7148d4df6146121fb6e347d2ef5e3e2

**Comment by Robin481** [comment]
@larsUE 
Ist auf INT.
Die Gruppen sind halt leer weil man das vorher so geändert hat.
Wenn man im Admin Interface die HTML Blocks wieder reinschiebt taucht auch tatsächlich wieder etwas auf :smile: 
Eventuell ist der Filter aufgrund des entfernen dieses Features nun auch wieder kaputt. (Quelle Thomas der Allwissende)

**Comment by larsUE** [comment]
Alles gut, das war so zu erwarten. Da muss ich dann eh noch aufräumen. Auf den ersten Blick fällt mir tatsächlich auf, dass die Filter nicht funktionieren. Kann man die Filter-Fixes drin lassen bzw. wieder einbauen?

Siehe: https://github.com/puzzle/decidim-zuerich/commit/35dd26998be38579a9dd5d33c0b64f75d0c0515c
https://github.com/puzzle/decidim-zuerich/commit/c31d9691d7148d4df6146121fb6e347d2ef5e3e2

**Comment by Robin481** [comment]
> Alles gut, das war so zu erwarten. Da muss ich dann eh noch aufräumen. Auf den ersten Blick fällt mir tatsächlich auf, dass die Filter nicht funktionieren. Kann man die Filter-Fixes drin lassen bzw. wieder einbauen?
> 
> Siehe: [35dd269](https://github.com/puzzle/decidim-zuerich/commit/35dd26998be38579a9dd5d33c0b64f75d0c0515c) [c31d969](https://github.com/puzzle/decidim-zuerich/commit/c31d9691d7148d4df6146121fb6e347d2ef5e3e2)

 @larsUE ich schaue mir das Morgen mit Thomas an :+1:

**Comment by Robin481** [comment]
@larsUE der Filter ist geflickt und auf INT deployed :smile_cat: (merci auch an @Kagemaru)

**Comment by larsUE** [comment]
Sehr cool, danke! Mir fällt nur noch etwas auf: und zwar ist der bei den zeitlichen Filtern jeweils der erste als aktiv/blau eingefärbt (ich glaube, das habe ich oder Carlo via CSS und Decidim Awesome eingebaut), aber das ist gar nicht der aktuelle ausgewählte, sondern einer, den ich neu setzen kann. 

Es gibt ja folgende auszuwählende Optionen: Alle | Bevorstehende | Vergangene | Zukünftige(?)
Per Decidim Standard werden nur Filter angezeigt, die nicht der aktuellen Auswahl entsprechen, da dies bereits via Titel bekannt gegeben wird. Wir möchten aber an erster Stelle den aktuell gesetzten Filter (in blau) und dann nachfolgend die weiter auswählbare Felder. Etwas kompliziert zu erklären, aber du kannst es dir auf der Prod noch anschauen. 

Ich bin mir nicht ganz sicher, in welchem Commit dies eingabaut wurde, ev. https://github.com/puzzle/decidim-zuerich/commit/b10af29a70c7c06ae6555a1b36c27f45e5f5f3ee oder https://github.com/puzzle/decidim-zuerich/commit/a9277cf89b73faf9d9b4e9941cdca39756ea047c. Könntest du nur diesen Teil wieder einbauen?

**Comment by Robin481** [comment]
@larsUE Ich habe heute auf den Code geschaut und bin noch nicht auf einen grünen Zweig gekommen. 
Morgen kann ich das sicher noch kurz mit Thomas besprechen und wir werden dich am Weekly updaten :v:

**Comment by Robin481** [comment]
@larsUE Anpassung ist gemacht und auf INT deployed.
Ich habe noch ein Follow-Up Ticket gemacht: https://github.com/puzzle/decidim-zuerich/issues/421 da die vorgesehene und nachhaltigere Lösung aufgrund von Ladethematiken nicht geklappt hat.

**Comment by larsUE** [comment]
@Robin481 Perfekt, danke! Somit passt nun alles.
