### ISSUE TITLE
Mails: Formatierung flicken

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#42]
Logos und Bilder werden zur Zeit nicht mitgeliefert. Problem bestand schon bei Quartieridee: https://github.com/puzzle/quartieridee/issues/54

**Comment by larsUE** [comment]
@Kagemaru konntet ihr das mit diesem Issue https://github.com/stadtluzern/decidim-ocl/issues/17 lösen?

**Comment by larsUE** [comment]
Gerade gesehen: Die Notifizierungsmails kommen mit Logo! 🍾

<img width="584" alt="Bildschirmfoto 2021-02-05 um 13 24 34" src="https://user-images.githubusercontent.com/60926257/107033375-7f744580-67b5-11eb-9712-c6257e11f3b9.png">

**Comment by larsUE** [comment]
Umsetzung läuft für Stolzehüsli (puzzle/quartieridee#87 und puzzle/quartieridee#80) und Luzern

**Comment by larsUE** [comment]
Möglicherweise wurde das hier gelöst: https://github.com/decidim/decidim/issues/7079

**Comment by larsUE** [comment]
Sorry, dass das jetzt trotzdem priority ist. Aber scheinbar funktioniert der Mailversand mit Logo nur auf der INT, auf der Prod  nicht. Deshalb entweder noch den Hack, der alles entfernt einbauen, oder kurz versuchen, ob der Fix funktioniert.

**Comment by carlobeltrame** [comment]
Das könnte vielleicht aber noch am Passwortschutz gelegen sein..? Kannst du nochmals kurz probieren?

**Comment by larsUE** [comment]
Gerade probiert, leider immer noch ohne Bilder. Scheint dasselbe wie auf den anderen Umgebungen auch zu sein.

**Comment by carlobeltrame** [comment]
Ich habe die priority Tickets implementiert und gleich auf Integration und Produktion ausgerollt, da du insbesondere dieses hier speziell noch auf der Produktion testen wolltest.

**Comment by larsUE** [comment]
Es hat geklappt, halleluja! :)
Könntest du noch kurz die Balken oben (schwarz) und unten (dunkelgrau) auf weiss ändern? Dann wär das schon mal super.

Ich mach dann im nächsten Schritt noch mehr CI/CD Anpassungen für den Newsletter als separates Ticket, das gehen wir dann aber später an.

**Comment by carlobeltrame** [comment]
Mails lokal zu testen ist noch etwas schwierig. Kannst du mir irgendwie eine E-Mail von decidim zusenden, in dem ich analysieren kann welche Änderung ich genau machen muss?

**Comment by larsUE** [comment]
Kannst du auf der Integ den newsletter subscriben (kannst du in deinen Profileinstellungen)? Dann verschicke ich einen

**Comment by carlobeltrame** [comment]
:+1: bin abbonniert
