### ISSUE TITLE
Anonymous access codes einbauen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#423]
Siehe: https://github.com/openpoke/decidim-module-anonymous_codes, sobald Entwicklung soweit ist.

**Comment by nicolefreypuzzle** [comment]
Umsetzung nächste Woche (KW19) wäre ausreichend

**Comment by larsUE** [comment]
@Kagemaru @Robin481 Bitte noch kurz warten mit der Installation, bis dieser PR fertig ist: https://github.com/openpoke/decidim-module-anonymous_codes/pull/21

Darin enthalten sind die letzten Feedbacks & noch einige Verbesserungen.

**Comment by nicolefreypuzzle** [comment]
Macht @Kagemaru noch bis Mittwoch, 8.5. oder wenn's nicht reicht, @Robin481 nächste Woche (ab 13.5.)

**Comment by Robin481** [comment]
@larsUE
Ich habe das neue Modul auf INT hinzugefügt. 
Selber konfiguriert habe ich nichts.
Dementsprechend warte ich auf dein Feedback :v:
