### ISSUE TITLE
Scopes und areas aufräumen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#424]
Für Decidim Geo muss ich alle Scopes und Areas miteinander tauschen. Ich könnte dies manuell machen, aber müsste hierfür jede einzelne Ressource, die mit einem Scope/Area verknüpft ist, suchen und anpassen. Hierfür fehlt mir Zeit und Überblick. Könnt ihr:

Auf INT

- [x] alle Areas,
- [x] die Scopes Energieversorgung, Gebäude, Participatory Budgets & xx_Testplanung,

und auf PROD

- [x] alle Scopes
- [x] alle Areas

löschen?

**Comment by Robin481** [comment]
Wir haben das einfach mal auf Mitwirken gemacht. 
Falls MeinQuartier auch erledigt werden soll holen wir das noch nach.

**Comment by larsUE** [comment]
Vielen Dank @Robin481 ! Auf MeinQuartier beabsichtigen wir derzeit nicht, DecidimGEO zu nutzen. Sollte sich das ändern mache ich ein neues Ticket.
