### ISSUE TITLE
Upgrade Decidim V0.27.6

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#427]
Siehe: https://github.com/decidim/decidim/releases/tag/v0.27.6

**Comment by nicolefreypuzzle** [comment]
@Robin481 erste Schritte nächste Woche (ab 13.5.) durchführen soweit möglich, Rest ab 20.5. mit tbu

**Comment by Robin481** [comment]
@larsUE
Ich habe die Änderungen auf INT Deployed. 
Selber getestet habe ich relativ wenig da ich mich noch nicht genug auskenne um die wichtigen Stellen auswendig zu wissen :grin: 
Dementsprechend warte ich auf dein Feedback :v:

**Comment by larsUE** [comment]
Danke dir! Minor releases sind immer etwas schwierig zu testen, aber grundsätzlich gilt wenn mal nichts kaputt ist, dann läufts schon mal gut. Ich teste noch etwas und schliesse dann das Ticket. Wir könnten dann für nächste Woche einen Prod-Release planen.
