### ISSUE TITLE
Plattformtexte/-sprache

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#43]
Es geht hier am die allgemeinen Plattform-Texte wie Notifizierungen, Anweisungen, Bezeichnungen usw. der Grundplattform. Mein Vorschlag wäre, dass wir eine saubere Sprachbasisversion einpflegen (die können wir dann auch auf Crowdin laden (https://github.com/puzzle/quartieridee/issues/59)). Mit dem term-Customizer können wir dann Prozessabhängig weitere Anpassungen vornehmen (z.B. in der Stadtidee dann den Begriff "Idee" statt "Vorschlag" verwenden. Es geht hier noch nicht um die Texte, die frei auf der Plattform eingefügt werden können (wie Begrüssungs-/Erläuterungstexte, FAQ). 
Ich wäre froh, wenn wir folgende Fragen möglichst bald geklärt hätten, vielleicht gibt es da ja auch Vorgaben seitens der Stadt Zürich (@wernerliechtenhan):

- Grundsätzlich: Sie oder du-Form?
- Wie bezeichnen wir die Nutzer*innen der Plattform, bzw. wen sprechen wir an? Einwohner*innen? Städter*innen?
- Gendern mit Stern oder was anderem?

**Comment by larsUE** [comment]
@carlobeltrame ich sehe gerade, die derzeitige Deutsche Crowd-In Übersetzung ist bei 99%. Ist das nach wie vor das schlechte/maschinelle Deutsch, dass wir bei der Quartieridee hatten, oder heisst das, dass mittlerweile eine bessere Übersetzung hinzugefügt wurde (z.B. von Decidim Berlin). Dann könnten wir natürlich auch die neue Übersetzung holen und als Ausgangspunkt nehmen.

**Comment by carlobeltrame** [comment]
99% bezeichnet nur die Anzahl Texte / Sätze die irgendeine deutsche Übersetzung haben. Das war auch schon nach der Google-Translate-Übersetzung so.

Ich habe aber tatsächlich selber im Dezember etwa zwei Drittel der Übersetzungen die ihr für die Quartieridee gemacht habt auf Crowdin eingepflegt, und bin auch sonst immer wieder mal dran, noch mehr Übersetzungen zu verbessern und neue gleich richtig zu machen wenn sie in decidim dazukommen (aktuell z.B. viele Abstimmungs-Features, den neuen Texten zu Folge). Diese verbesserten deutschen Übersetzungen sind auch schon auf dem GitHub von decidim drin, das passiert immer automatisch sobald jemand in Crowdin etwas ändert.

Aber leider ist seit ich mit diesen Verbesserungen begonnen habe keine neue Version von decidim mehr rausgekommen. 0.23.1 wurde am 12. November released. Und um diese neuen Übersetzungen zu "holen" gibt es fast keine andere praktikable Lösung als auf das nächste decidim-Release zu warten und zu updaten.

Übrigens: Bei den offiziellen Übersetzungen von decidim benutze ich immer die Sie-Form, und korrigiere allfällige Übersetzungen in Du-Form sobald ich sie antreffe. In die Richtung Genderkorrektheit ist hingegen noch praktisch nichts gemacht. Oft wird von einem Benutzer, Bürger, Wahlhelfer etc. gesprochen. Ich bin auch nicht sicher, ob der Gender-Stern in Deutschland gleich verbreitet / populär ist wie in der Deutschschweiz.

**Comment by wernerliechtenhan** [comment]
> Ich wäre froh, wenn wir folgende Fragen möglichst bald geklärt hätten, vielleicht gibt es da ja auch Vorgaben seitens der Stadt Zürich (@wernerliechtenhan):

Grundsätzlich: Sie oder du-Form?
Wie bezeichnen wir die Nutzerinnen der Plattform, bzw. wen sprechen wir an? Einwohnerinnen? Städter*innen?
Gendern mit Stern oder was anderem?

Die Richtlinien der Stadt Zürich finden sich [hier](http://intranet.stzh.ch/richtlinien-verzeichnisse/richtlinien/sprache-rechtschreibung).

Ich bin grundsätzlich für die Sie-Form. 
Gleichstellung gemäss städtischen Vorgaben: Wenn vom Platz her möglich Doppelnennen, z. B. Nutzerinnen und Nutzer.  Wenn der Text kurz sein muss kann auf das Binnen I ausgewichen werden.

**Comment by larsUE** [comment]
Super danke! Ich arbeite das so ein. Wie siehst du es bei folgenden Begriffen, wie sie derzeit auf decidim verwendet werden:

- Beteiligungsprozesse: Ich glaube, die Stadt verwendet jeweils "Mitwirkungsprozesse", oder?
- Events: Hier spricht die Stadt jeweils von Veranstaltungen, oder?

**Comment by wernerliechtenhan** [comment]
Meist verwenden wir den Begriff <Mitwirkung>, manchmal auch <Mitwirkungs- und Beteiligungsprozesse> oder eine Kombination wie [hier](https://www.stadt-zuerich.ch/mitwirken). 
Die Begriffe Partizipation - Beteiligung- Mitwirkung gelten als Synonyme.

**Comment by larsUE** [comment]
Super, danke! Dann lasse ich den Begriff "Beiteiligungsprozesse" vorerst mal stehen.
