### ISSUE TITLE
Regelmässige 429er auf MeinQuartier

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#430]
Ich habe treffe Besuch der MeinQuartier-Prod regelmässig auf den «Too many requests» Error.

**Comment by larsUE** [comment]
Eben konnte ich diesen Bug auch bei Mitwirken feststellen. Wahrscheinlich wirkt sich auch Decidim GEO negativ auf den Schwellwert aus.

**Comment by nicolefreypuzzle** [comment]
Da noch nie von ausserhalb / Users gemeldet und Lars auf mehreren Umgebungen viele Aktivitäten auslöst, zuerst mal Test mit Cookies löschen.

**Comment by nicolefreypuzzle** [comment]
Passiert mittlerweile auch auf Mitwirken sehr oft.
Vermutung auf Decidim.GEO (viele Requests?)

**Comment by nicolefreypuzzle** [comment]
Schrittweises Anpassen der Request-Limits von WAF, nginx, Rails, RackAttack.
@Kagemaru
Reihenfolge wird noch dokumentiert.

**Comment by Kagemaru** [comment]
Reihenfolge der Anpassung:
  - [ ] Nginx-Gatekeeper
  - [ ] WAF
  - [ ] Nginx Rails
  - [ ] Rack::Attack
  - [ ] Decidim

**Comment by larsUE** [comment]
Wir haben nun auch von einer Nutzerin erstmalig die Meldung bekommen, dass sie einen 429er hatte. Scheint also noch nichts gebracht zu haben bislang. Bei Decidim GEO habe ich das Verhalten ebenfalls gemeldet.

**Comment by nicolefreypuzzle** [comment]
Nächste Woche (mit Thomas) anschauen @Kagemaru

**Comment by larsUE** [comment]
Zum Reproduzieren: auf mitwirken.stadt-zuerich.ch/processes ein paar Mal die Filtereinstellungen von Decidim GEO anpassen. Dann kommt der 429er relativ schnell

**Comment by nicolefreypuzzle** [comment]
Bei Thomas auf "mein Quartier" besser reproduzierbar und erst nach VPN deaktivieren

**Comment by nicolefreypuzzle** [comment]
Hey @larsUE 
Thomas nimmt sich dem jetzt gleich an und meldet sich bei neuen Erkenntnissen / Informationen bei dir.

**Comment by Kagemaru** [comment]
Wir haben nun die S3 URLs und redirects von Rack::Attack ausgenommen. Deployed auf INT/PROD und auch bereits getestet mit dem Segen von Lars. :rocket:
