### ISSUE TITLE
500er beim Vorschlagsmodul auf INT

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#434]
Derzeit besteht bei den meisten Vorschlagskomponenten auf der INT einen 500er

**Comment by Kagemaru** [comment]
Fix deployed, @larsUE prüft die Umgebung.

**Comment by larsUE** [comment]
Jetzt habe ich doch einiges bemerkt, das nicht so sein sollte und die wohl damit zusammenhängen:
- Ich kann in Decidim Awesome bei den Custom Styles keine scopes mehr setzen bzw. werden die Prozesse dazu nicht mehr angezeigt.
