### ISSUE TITLE
Aufbau Produktionsumgebung

### ISSUE THREAD

**Issue by bsantschi** [puzzle/decidim-zuerich#44]

**Comment by Kagemaru** [comment]
PROD ist deployed und das Zertifikat ist installiert.

**Comment by carlobeltrame** [comment]
Organisation ist erstellt, und ich habe Thomas und Lars als Admins eingeladen. Lars kann nun nach Bedarf weitere Leute einladen.

Als Sprache habe ich vorsichtshalber mal nur Deutsch aktiviert, damit wir nicht in dasselbe Problem wie bei Dialog Luzern laufen (Sprachen hinzufügen ist möglich in Decidim, aber [Sprachen nachträglich entfernen ist sehr viel schwieriger](https://docs.decidim.org/en/develop/fixing_locales/)). Bitte melden wenn wirklich damit begonnen wird, mehrsprachige Inhalte abzufüllen, dann aktiviere ich noch Englisch.

**Comment by larsUE** [comment]
Super, danke euch! Englisch kannst du aktivieren, das sollten wir bereits ab Start haben. Könntet ihr die Prod allenfalls noch passwortschützen? z.B. gleiches pwd wie bei der int?
