### ISSUE TITLE
Timeout bei Anpassung von Term Customizer Sets (PROD und INT)

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#444]
Wenn ich ein TC Set anpassen möchte (z.B. anderer Titel oder anderer Scope, oder einfach ein neues Set erstellen möchte) so führt dies zu einem Timeout.

**Comment by nicolefreypuzzle** [comment]
seit Cookies-Löschen bei Lars nicht mehr aufgetreten. "Standby"

**Comment by larsUE** [comment]
Ich beobachte, dass dies nun nach dem Datenbank-Fix wieder auftritt. Es tritt jeweils gemeinsam mit weiteren Bugs auf:

1. Hochgeladene Bilder bleiben auf der Stufe "validiert" hängen
2. Neue Custom Styles auf Awesome können nicht hinzugefügt werden bzw. führen zu Timeouts

@Kagemaru : Könnte dies nicht auch mit der WAF bzw. dem 429er zusammenhängen?

**Comment by larsUE** [comment]
Computer-Neustart hat das Problem gelöst
