### ISSUE TITLE
Sharing tokens (Pokecode) installieren

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#450]
Hallo zusammen! Über den Sommer entwickelt Pokecode für uns bzw. den Decidim Core ein Modul, mit dem sich das Teilen von Componenten/Spaces etwas flexibler handhaben lässt.  Da der Core diese Weiterentwicklung für V0.30 akzeptiert hat, müssen wir einen Backport erstellen, um es auf V0.27 zu haben. Pokecode fragt, was für uns der einfacher Weg wäre:

> 1. Create a branch in a Decidim fork and backport the functionality there (for instance, ours) then we point your Decidim to use that branch in the Gemfile. This is the easiest solution for us (a bit less work and quicker). Why a fork? Because Decidim has this policy of not backporting new features, they won't backport these sharing improvements to version 0.27.
> 2. Add overrides to your Decidim application, this means to create classes and views to backport the functionality just to you Decidim. It implies a bit more work for us, probably will consume a bit more time.

Ich danke euch für ein Feedback!

**Comment by larsUE** [comment]
Yeah, thanks. Das hilft schon mal weiter.

**Comment by Robin481** [comment]
Hello @larsUE 

Switching to English so we all understand each other :)

Just a few notes so we are on the same page:
If we start using the forked Decidim version we are completely reliant on it instead of the "standard" decidim version. 
This means no more upgrades from the main decidim branch unless they are implemented in the forked version. 
This means no updates happen if they don't happen in this forked branch until we jump to 0.30. 
This is not to mean that we shouldn't do it, I just want us all to be aware of this 😃 
@larsUE wanna give me a short Feedback that you are aware of this and want me to continue?

**Comment by larsUE** [comment]
Hmm, yes this may be an issue. 

On the other hand: What would happen if the branch updates faster than we do?

@microstudi @paarals What are your thoughts on this?

**Comment by microstudi** [comment]
Let's see:
1. The 0.27 branch series, we will keep update if news security fixes appear. For this, no worries. You can also ping us at any time to do it if we forget about it.
2. We've just spoke with product and this feature will be integrated in the version 0.30. In case you want it for the 0.28 or 0.29 we should also create a backport for this. However, fear not, this is going to be an easy backport (as is the same design from the 0.28 and up)

**Comment by larsUE** [comment]
@microstudi Cool, thanks a lot! Does this mean you're on V0.27.9 now? We'll be updating to that version as well. 

And hooray for the core feature! We will most likely jump directly to V0.29 (or even 0.30 directly), approx. next Spring.

**Comment by larsUE** [comment]
@microstudi could you quickly confirm this? :-)

**Comment by microstudi** [comment]
@larsUE yes. it is in the 0.27.9 now that branch

**Comment by larsUE** [comment]
@Kagemaru @Robin481 Ich sehe dieses Feature derzeit noch nicht auf INT

**Comment by Robin481** [comment]
@larsUE Ja das war tatsächlich noch nicht deployed, sorry für das Missverständnis. 
Habe ich jetzt korrigiert :+1:

**Comment by nicolefreypuzzle** [comment]
Deployment auf PROD geplant am Do, 14.11. ab 17 Uhr @Kagemaru
