### ISSUE TITLE
Modul für Veranstaltungsanmeldung ohne Registrierung übernehmen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#459]
Siehe PR: https://github.com/puzzle/decidim-zuerich/pull/458

**Comment by nicolefreypuzzle** [comment]
Zieltermin PROD eingespielt: Ende September

**Comment by nicolefreypuzzle** [comment]
wird zwischen Robin und Thomas besprochen & validiert, wenn iO, auf INT

**Comment by Robin481** [comment]
@larsUE ist auf der Testumgebung deployed 😸

**Comment by larsUE** [comment]
Alles soweit i.O.!

**Comment by Robin481** [comment]
@larsUE Auf Prod Deployed :heavy_check_mark:
