### ISSUE TITLE
Update Decidim V0.27.9

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#460]

**Comment by nicolefreypuzzle** [comment]
Fix-Thema rund um Templates, die in bestimmter Situation crashen.

beurteilung seitens Puzzle, ob / wann sinnvoll

**Comment by larsUE** [comment]
Abhängigkeit mit #450

**Comment by Robin481** [comment]
Löst sich mit direkt mit dem erledigen von #450

**Comment by nicolefreypuzzle** [comment]
Deployment auf PROD geplant am Do, 14.11. ab 17 Uhr @Kagemaru
