### ISSUE TITLE
Decidim Geo aktualisieren (auf V0.2.5.)

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#464]

**Comment by Kagemaru** [comment]
@larsUE Etwas seltsam ist, dass auf dem Git tag 0.2.5 die Version 0.2.4 des Moduls liegt. Eine Version 0.2.5 des Moduls finde ich hingegen nirgends. Ich habe jetzt mal den tag 0.2.5 deployt.

**Comment by larsUE** [comment]
Der gewünschte Bugfix scheint darin enthalten zu sein! Vielen Dank!

**Comment by nicolefreypuzzle** [comment]
Deployment auf PROD geplant am Do, 14.11. ab 17 Uhr @Kagemaru
