### ISSUE TITLE
Kein Bild-Upload möglich

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#465]
Im Moment führt jeder Upload eines Bildes direkt zu einer Fehlermeldung. dies betrifft alle Zürcher Umgebungen, INT und Prod. 

**Zum Nachstellen:**
Irgendwo auf der Plattform ein Bild hochladen, Fehler feststellen.
![Image](https://github.com/user-attachments/assets/0c478497-0797-43d7-b30c-a0398ba778d2)

**Geprüftes:**
- Unterschiedliche Bilder
- unterschiedliche Formate
- unterschiedliche Dimensionen

Alles ohne Effekt.

**Comment by larsUE** [comment]
Fehlermeldung dazu: 

![Image](https://github.com/user-attachments/assets/a52c4389-c54b-46cb-836f-7e6404d567b5)

**Comment by Kagemaru** [comment]
Beim Upgrade des Storage der Bilder hat es einen Bug in der neuen Software. Dieser wird frühestens nächste Woche gefixt. Momentan haben wir einen Workaround implementiert bekommen,  der das Problem kurzfristig löst.

Betroffen waren seit vorgestern übrigens alle Plattformen und Instanzen von Luzern & Zürich.
