### ISSUE TITLE
Access links 500er

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#469]
In einigen Kompoenten (unklar genau, welchen) löst das Access Link Modul einen 500er Fehler aus. z.B. hier: https://mitwirken.integ.stadt-zuerich.ch/admin/participatory_processes/testlars/components?locale=en

Bitte kurz überprüfen ob der Fehler bei uns liegt (z.B. fehlende Übersetzung) oder ein Bug bei Pokecode ist.

**Comment by larsUE** [comment]
> Habe das Problem gefunden. Im Backport von Pokecode war noch eine Migration, von der wir nichts wussten.
Ich deploye gerade auf INT.

**Comment by nicolefreypuzzle** [comment]
Deployment auf PROD geplant am Do, 14.11. ab 17 Uhr @Kagemaru
