### ISSUE TITLE
Nutzungsbedingung & Datenschutzerklärung erstellen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#49]
@swaldis: Seid ihr da zuständig? Falls ja, könnt ihr gerne die Terms von der [Quartieridee](https://quartieridee.ch/pages/terms-and-conditions) übernehmen (müssten wohl aber noch jurisitisch abgeklärt werden) oder kurz bei Luzern nachfragen. Sie haben auch unsere Version genommen und weiterbearbeitet.

**Comment by wernerliechtenhan** [comment]
Der ISDS-Prozess für die Decidim-Plattform hat die OIZ durchlaufen. Wir treffen uns nun am 1.3. mit dem Datenschutzbeauftragten der Stadt, um zu klären, ob es für die einzelnen Prozesse jedesmal wieder eine Datenschutzvereinbarung braucht.

**Comment by larsUE** [comment]
Ah super! Aus Plattformsicht wäre es etwas kompliziert, für jeden Prozess eigene Vereinbarungen zu machen. Die Nutzungsbedingungen sind mit dem Login verknüpft. Im Backend kann eingestellt werden, dass die Nutzungsbedingungen z.B. von allen Nutzenden neu angenommen werden müssen, wenn es etwa grössere Änderungen gab. Da müssten wir sonst irgendwie abfangen, in welchem Prozess sich der Nutzende gerade befindet und protokollieren, welche Bedingungen welches Prozesses er*sie bereits angenommen hat. 
Auch aus UX-Sicht ist es wohl nicht ganz ideal, wenn immer wieder neu Bedingungen angenommen werden müssen. Bei mir persönlich löst das jeweils immer ein bisschen Misstrauen aus, wenn ich z.B. immer wieder die Google Nutzungsbedingungen akzeptieren muss  :)

**Comment by larsUE** [comment]
Hier übrigens die Nutzungsbedingungen der Stadt Luzern: https://dialogluzern.ch/pages/terms-and-conditions

@wernerliechtenhan @swaldis: Soll ich davon mal eine Zürcher Version erstellen?

**Comment by wernerliechtenhan** [comment]
Das ist sicher ein guter Ausgangspunkt. Wir können das dann immer noch anpassen bei Bedarf.

**Comment by swaldis** [comment]
Ja ich denke auch, das ist eine gute Idee

**Comment by larsUE** [comment]
Ich hab sie mal hierhin kopiert, auf ZH-Verhältnisse angepasst und Unklares bzw. Anzupassendes gelb markiert. Wär cool, wenn ihr mal drüberschauen könnt! https://docs.google.com/document/d/1namKQxiqi7H82Ki7lRuSY4xft23ehVgLm8HvntDFXjY/edit?usp=sharing
