### ISSUE TITLE
Kontakt Mail-Adresse festlegen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#51]

**Comment by larsUE** [comment]
@wernerliechtenhan oder @swaldis: Ist schon klar, welche Mail-Adresse(n) für die Kommunikation verwendet werden? Die Plattform braucht eine Hauptmail und allenfalls weitere Kontaktmöglichkeiten (je nachdem, wie ihr euch intern organisiert, kann das aber auch alles die gleiche Adresse sein).  

1. Adresse, unter deren Namen decidim Notifizierungen versendet.
2. Kontaktadresse, unter der Nutzende der Plattform die Trägerschaft kontaktieren kann.
3. Allenfalls unterschiedliche Kontaktadressen der einzelnen Beiteiligungsprozesse (ich nehme an, diese Verantwortung liegt dann bei der durchführenden OE).

**Comment by swaldis** [comment]
1. Was sind das für Arten von Notifikationen? technisch, Info über Tool..?
2. Ich denke das ist eher bei der STEZ?
3. Das sehe ich bei der DA mit dem Owner zu jeweiligen Umfrage

**Comment by larsUE** [comment]
Wird wird bei OIZ_Helpdesk bestellt.

**Comment by wernerliechtenhan** [comment]
Zwei E-Mail-Adressen wurden generiert: mitwirken@zuerich.ch und mitwirken-kontakt@zuerich.ch. Im Moment ist es so eingerichtet, dass Max und ich diese E-Mails erhalten. Funktioniert.

**Comment by bsantschi** [comment]
Lieber @wernerliechtenhan, wir benötigen für mitwirken@zuerich.ch den SMTP Host, Port, Username und Password. Kannst du uns das über einen sicheren Kanal (z.B. Signal) mitteilen?

**Comment by wernerliechtenhan** [comment]
Guten Morgen, ich kenne diese Angaben nicht und habe bei der OIZ nachgefragt. Erwarte im Verlaufe des Tages eine Antwort.

**Comment by wernerliechtenhan** [comment]
Ich habe folgende Rückmeldung von der OIZ erhalten: 

"Das Postfach STE-Mitwirken ist normal von extern erreichbar. Es braucht dazu kein spezieller SMTP Host (welcher ohnehin nur aus dem städtischen Netz erreichbar wäre). Die Weiterleitungen können direkt an mitwirken@zuerich.ch erfolgen."

Könnt ihr damit etwas anfangen oder soll ich nochmals nachhaken?

**Comment by carlobeltrame** [comment]
Das reicht uns leider noch nicht. Decidim muss Mails via diese Mailadresse versenden. Dazu müssen wir Decidim mitteilen, bei welchem Mailserver es sich wie authentifizieren kann. Eine einfache Mail-Weiterleitung reicht für mitwirken@zuerich.ch im Gegensatz zu mitwirken-kontakt@zuerich.ch nicht. Wir brauchen wirklich diese Angaben.

**Comment by wernerliechtenhan** [comment]
Die Antwort der OIZ: 
"Es wird jedoch nicht möglich sein mit der Email Adresse mitwirken@zuerich.ch von extern an ein städtisches Postfach zu versenden. Dies wird auf unserem Internetgateway geblockt. Wäre dies die Anforderung?"

**Comment by Kagemaru** [comment]
Hallo Zusammen
Ich habe gerade noch mit Rolf Brun wegen der Mailserver Problematik telefoniert.
Er findet wir sollen direkt im Namen von Zürich vom APPUiO Server aus unsere Mails verschicken. (mxout.appuio.ch)
Die notwendige Änderung im DNS bestellt er gerade. Sobald diese durch ist, müssen wir nur noch die offiziellen E-Mail-Adressen bei uns als Versandadressen eintragen.

**Comment by Kagemaru** [comment]
Der SPF Eintrag ist nun erledigt und die Mailadressen sind eingetragen.
Es muss noch getestet werden, ob das Whitelisting bei der Zürcher Firewall geklappt hat. Dies kann von uns nicht getestet werden.

**Comment by larsUE** [comment]
Klappt nun bei mir auch regelmässig! Wuhuuu!

**Comment by Kagemaru** [comment]
> Es muss noch getestet werden, ob das Whitelisting bei der Zürcher Firewall geklappt hat. Dies kann von uns nicht getestet werden.
Rolf Brun hat gemeldet, dass dies auch auf ihrer Seite funktioniert.
