### ISSUE TITLE
Term Customizer server timeout fix von der Quartieridee übernehmen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#52]
siehe: https://github.com/puzzle/quartieridee/commit/f19109054b5f85f4595ddcbb77f82b6985b99c2d

**Comment by carlobeltrame** [comment]
Ich habe den Fix auf der [alten Testumgebung](https://pitc-decidim-zuerich-int.ocp.puzzle.ch/) ausgerollt. Die war allerdings auch vorher nicht down. Meintest du eine andere Instanz? Ich habe bisher auf keine anderen Instanzen von der Stadt Zürich Zugriff. Falls der Fix wie gewünscht funktioniert hat, wäre es aber für Thomas trivial, das auszurollen.

**Comment by bsantschi** [comment]
Die Adresse der neuen Integrationsumgebung lautet: https://mitwirken.integ.stadt-zuerich.ch

**Comment by larsUE** [comment]
Jetzt bin ich auch verwirrt, ich meinte hier: https://pitc-decidim-zuerich-new-int.ocp.puzzle.ch

**Comment by bsantschi** [comment]
Wollen wir das Github Wiki nutzen, um URLs, etc. zu dokumentieren? https://github.com/puzzle/decidim-zuerich/wiki

**Comment by larsUE** [comment]
Also, kurz geklärt: @bsantschi's Link ist die externe URL, welche scheinbar noch nicht läuft, da noch DNS Anpassungen vorgenommen werden müssen. 

Mein [Link](https://pitc-decidim-zuerich-new-int.ocp.puzzle.ch) ist die neue Testumgebung. @carlobeltrame kannst du den Fix hier ausrollen? Ich schlage vor, wir verwenden ab jetzt nur noch die neue Testumgebung.

Das Wiki zu nutzen find ich super & würde mich dann mal darum kümmern.

**Comment by carlobeltrame** [comment]
Kann ich leider nicht, da ich noch keinen Zugriff auf diese Umgebung habe. Aber @Kagemaru bringt das in einer freien Sekunde sicher hin, der Fix muss nur noch ausgerollt werden.
