### ISSUE TITLE
DNS Einträge bei OIZ bestellen

### ISSUE THREAD

**Issue by bsantschi** [puzzle/decidim-zuerich#55]

**Comment by bsantschi** [comment]
Macht gemäss Stefan Nik.

**Comment by Kagemaru** [comment]
INTEG muss noch auf APPUiO umgestellt werden. Ich schreibe Nik mit den genauen Angaben.

**Comment by bsantschi** [comment]
@Kagemaru bitte nächste Woche direkt mit Nik schauen.
