### ISSUE TITLE
Headeranpassungen: Profil

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#60]
Gemäss: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/myaccountaccess/myaccountaccess.html

**Comment by larsUE** [comment]
Schon mal mega cool, danke! Hier fehlt noch die Hover-Action: Ohne Mouse hover ist das Profil transparent und erst bei einem mouse hover wirds blau mit weisser Schrift.

**No hover**
![Bildschirmfoto_ 2021-03-12 um 10 02 08](https://user-images.githubusercontent.com/60926257/110917280-04550080-831a-11eb-8c60-a28bc2bbec65.png)

**Hover**
![Bildschirmfoto 2021-03-12 um 10 03 23](https://user-images.githubusercontent.com/60926257/110917426-2fd7eb00-831a-11eb-835e-8af07dc17e4e.png)

Zusätzlich hab ich noch so einen komischen hellblauen Rahmen rundherum, als hätte ich das menü irgendwie selektiert (Safari). Könntest du da noch entfernen?
![Bildschirmfoto 2021-03-12 um 10 05 15](https://user-images.githubusercontent.com/60926257/110917671-74638680-831a-11eb-8388-c17ff3b12d82.png)

**Comment by carlobeltrame** [comment]
Bist du sicher mit dem hover? Dein Screenshot ist vom Zustand "My Account Access Not Logged In User", also wenn man nicht eingeloggt ist. Diesen Zustand habe ich nicht umgesetzt, weil in decidim zwei Links "Registrieren" und "Anmelden" da sind (müssten beide in einem Button sein? oder je ein Button pro Link?). Hingegen der "Default" Zustand hat bei mir immer einen blauen Hintergrund. Siehe https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/myaccountaccess/myaccountaccess.html

Den blauen Rahmen bei Fokus kann ich entfernen. Das ist zwar aus Accessibility-Sicht bad practice (User die die Seite nur mit Tastatur oder Screen Reader bedienen), aber in diesem Fall wohl vertretbar, da es zumindest ein Stück weit visuelle Indikatoren gibt, wo der Fokus gerade liegt.

**Comment by larsUE** [comment]
Ah super, du hast natürlich Recht mit dem Hover. In dem Fall vorerst mal so lassen. Wir können dann nach der Mein-Konto integration mal schauen, ob wir vielleicht daraus auch ein Dropdown (Einloggen/Registrieren) machen wollen oder nicht.

Den blauen Rahmen bzw. das Accessabilitythema traktandiere ich mal für unsere CI Sitzung nächste Woche.

**Comment by larsUE** [comment]
Also gemäss Sitzung würden wir den blauen Rahmen mal entfernen/überschreiben (analog zur städtischen Website).

**Comment by Kagemaru** [comment]
> Den blauen Rahmen bei Fokus kann ich entfernen. Das ist zwar aus Accessibility-Sicht bad practice (User die die Seite nur mit Tastatur oder Screen Reader bedienen), aber in diesem Fall wohl vertretbar, da es zumindest ein Stück weit visuelle Indikatoren gibt, wo der Fokus gerade liegt.

Diese Indikatoren gibt es nur beim Benutzen einer Maus. Screen Reader verlassen sich z.B. sehr darauf, dass diese Outlines funktionieren, da sonst ihr Pointer teilweise einfach verschwindet. Somit ist die Navigation im Speziellen nach der Registrierung sehr eingeschränkt, wenn wir die Outlines entfernen.

**Comment by larsUE** [comment]
Auf Safari ist bei mir der Rahmen noch sichtbar, auf Chrome ist er weg. Kannst du das noch anpassen?

**Comment by carlobeltrame** [comment]
Hmm schwierig, ich habe keinen Safari zum testen, und ich habe hier nichts gemacht weil es auf Chrome eben einfach weg war. Ich kann mal einen relativ groben Fix machen, aber schwer zu testen ob es wirklich funktioniert. Könntest du mir vielleicht noch einmal einen Screenshot machen? Oder siehts immer noch genau so aus wie oben? Ich verstehe eben nicht genau welches Element den Fokus hat sodass der Button wie auch das Dropdownmenü gleichzeitig eingerahmt werden...

**Comment by larsUE** [comment]
Sieht noch gleich aus wie oben. Weiss nicht genau, wie ich mit den Tools herausfinden kann, welches Objekt den Rahmen auslöst, am ehesten so wie Screenshot? Sonst lassen wir den fix mal noch weg.

<img width="546" alt="Bildschirmfoto 2021-04-12 um 15 56 37" src="https://user-images.githubusercontent.com/60926257/114406240-ab41ec00-9ba7-11eb-8883-e7bcd02370f5.png">

**Comment by carlobeltrame** [comment]
Merci. Das Element das du ausgewählt hast hat "Fokussiert Nein", und ich müsste wissen welches Element fokussiert ist während die Outline angezeigt wird. Der Form des blauen Rands nach zu urteilen müsste das entewder das `<ul class="dropdown menu">` oder das `<li class="is-dropdown-submenu-parent">` sein, aber diese beiden Elemente können in HTML gar nicht fokussiert werden.
Safari hat eine gewisse History mit Problemen mit diesen Outlines, und auch dass die Outline einfach irgendwo abbricht sieht sehr buggy aus. Ich würde das jetzt mal so lassen. Es ist auch möglich, dass das nur einzelne Versionen von Safari betrifft.

Die mit-Kanonen-auf-Spatzen-schiessen-Alternative wäre, sämtliche Outlines auf der ganzen Seite auszuschalten, aber das ist aus Accessibility-Sicht wie schon mehrfach erwähnt eine sehr schlechte Idee (siehe unter anderem http://www.outlinenone.com/). Ausserdem habe ich auch Reports gelesen, wo in gewissen Safari-Versionen nicht einmal das etwas geholfen hat.

**Comment by larsUE** [comment]
Dann lassen wir es sein :)
