### ISSUE TITLE
Header: Logo

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#62]
Gemäss: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/logo/logo.html
Responsive vergrössern aber bis max. 265 x 53px

@wernerliechtenhan: Welches städtische Logo soll auf die Plattform? Gibt es ein eigenes (z.B. Stadt Zürich – Mitwirken)?

**Comment by wernerliechtenhan** [comment]
Auf die Plattform muss das "normale" Stadt Zürich-Logo. Es gibt kein spezielles Logo fürs Thema Mitwirken/Beteiligung. Die Vorgaben dazu finden sich [hier](https://www.stadt-zuerich.ch/cd/de/index/grundlagen_und_elemente/logo.html
).

**Comment by larsUE** [comment]
Schneinbar häkt sich die Stadt auch nicht an ihre eigenen Vorgaben und die Logos sind grösser. Bei mir stoppt die skalierung bei 242 X 79 px (vor allem die Höhe ist relevant). @carlobeltrame könntest du da noch anpassen?
