### ISSUE TITLE
Header: Top-Menu

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#63]
Gemäss: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/topnav/topnav.html

**Comment by larsUE** [comment]
**Noch CI/CD Feedback abwarten.** Allenfalls Menü linksbündig statt zentriert machen.

**Comment by larsUE** [comment]
Schon mal super! Es fehlt noch die Linie die Teils sichtbar ist. Ist dieselbe Linie wie bei #68 . Wäre bei uns sicher noch hilfreich, um das Menü z.B. auf der Hilfeseite besser abzuheben.
![Uploading Bildschirmfoto 2021-03-12 um 14.38.03.png…]()

**Comment by carlobeltrame** [comment]
Okay, kann ich noch machen. Soll die Linie die ganze Bildschirmbreite einnehmen oder nur so breit sein wie der Rest des Inhalts (so wie die section header Linien)?

**Comment by larsUE** [comment]
Cool, danke! So wie bei den anderen, wie der restliche inhalt

**Comment by carlobeltrame** [comment]
Linie ist jetzt da

**Comment by larsUE** [comment]
Kannst du das Menü linksbündig und die Schrift noch etwas kleiner machen? Gemäss [Style-Guide](https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/topnav/topnav.html) wären das die Werte:
![Bildschirmfoto 2021-03-16 um 09 23 40](https://user-images.githubusercontent.com/60926257/111277949-4db69000-8639-11eb-9556-cb028acab693.png)

Falls Decidim das aber überschreibt, vorerst mal sein lassen.

**Comment by larsUE** [comment]
@carlobeltrame ich sehe gerade, dass die font-size immer noch zu gross ist (verglichen z.B. mit hier: https://www.stadt-zuerich.ch/portal/de/index.html). 

Aktuell (ich hoffe, das ist das richtige Element:
![Bildschirmfoto 2021-04-07 um 09 52 50](https://user-images.githubusercontent.com/60926257/113830557-05e1df00-9787-11eb-8bcd-427ebd6959f8.png)

Gewünschte size siehe Bild oben: .88125 rem

**Comment by larsUE** [comment]
Ich sehe da die Änderung noch nicht (meinte aber, sie vorher mal kurz gesehen zu haben)

**Comment by carlobeltrame** [comment]
Bist du auf der richtigen Umgebung? https://pitc-stzh-decidim-int.appuioapp.ch/
In deinem Video https://github.com/puzzle/decidim-zuerich/issues/83#issuecomment-815037956 ist die kleinere Schrift ja sogar auch zu sehen.

**Comment by carlobeltrame** [comment]
Oder meintest du die Schriftgrösse auf der ganzen Seite? Ich dachte du meinst nur im Top-Menü, daher in diesem Issue. Wenns überall gemeint ist, gehörts wohl eher in #68 oder?

**Comment by larsUE** [comment]
Neinnein, ich meins schon so (nur im Top-Menu): Schau mal im Direktvergleich Decidim (links) und stadt Zürich (rechts). Beide Seiten sind unskaliert, was du an der Grösse des Banners sehen kannst.
![Bildschirmfoto 2021-04-07 um 19 27 35](https://user-images.githubusercontent.com/60926257/113909058-8c261180-97d7-11eb-8794-ff5f9042c720.png)

**Comment by carlobeltrame** [comment]
Ah jetzt seh ichs, ich hatte vergessen welche der menü-ebenen du top menü nennst ;) wird noch gemacht.
