### ISSUE TITLE
Absender Adresse per Organisation

### ISSUE THREAD

**Issue by Kagemaru** [puzzle/decidim-zuerich#70]
# Probleme
- Mails werden nicht mit Org spezifischen Settings versendet.
- Bei demAbsender-Label wird ein E-Mail Format erzwungen

#Nachforschungen
- [ ] set_smtp (ActionMailer after_action) wird nicht aufgerufen, dies sollte Org Settings auf die Mail packen.
- [ ] org.smtp_settings['from'] wird nicht richtig gesetzt.
  - [ ] Sollte in /system passieren nach dem speichern
    - [x] save_organization wird aufgerufen
    - [x] form.encrypted_smtp_settings wird aufgerufen
    - [ ] set_from returniert immer nil
      - [ ] Hash access mit Strings statt mit Symbols
- [ ] Eine Validierung forciert eine E-Mail Adressvalidierung

**Comment by carlobeltrame** [comment]
Beide Probleme wurden in https://github.com/decidim/decidim/issues/6901 gemeldet und für decidim 0.23.2 implementiert. Lösungsweg könnte also auch ein Upgrade auf 0.23.2 sein.

**Comment by carlobeltrame** [comment]
Das Decidim Upgrade ist abgeschlossen. Ich konnte verifizieren, dass beide Probleme gelöst sind (indem ich meine persönlichen Daten auf dem Profil zum Download angefordert habe, dann bekommt man eine E-Mail).
