### ISSUE TITLE
TermCustomizer Translation Fix entfernen.

### ISSUE THREAD

**Issue by Kagemaru** [puzzle/decidim-zuerich#71]
Unser TermCustomizer Hotfix, ist jetzt im master branch und can bei uns nach einem Gem update entfernt werden.

https://github.com/puzzle/decidim-zuerich/blob/master/app/overrides/models/decidim/term_customizer/translation_override.rb

**Comment by carlobeltrame** [comment]
Gem update ist gemacht, man könnte das jetzt vermutlich einfach entfernen.

**Comment by larsUE** [comment]
Go for it!
