### ISSUE TITLE
Fehlermeldungen bei Components

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#72]
Wenn ich auf das Meeting zugreifen möchte, kommt die Fehlermeldung "Auf unserem Server ist ein Problem aufgetreten". Wahrscheinlich ein Bug mit der Kartenfunktion? War bis jetzt nach einem Update immer so ;) #33

**Comment by larsUE** [comment]
Fazit nach Test mit allen Modulen: es muss definitiv mit einer Kartenfunktion zusammenhängen, da es nur Module betrifft, die Karteninformationen darstellen.

**Comment by carlobeltrame** [comment]
Habe neu deployed, die erwähnten Seiten funktionieren jetzt alle. Die Miro Karte verstehe ich nicht ganz was die anzeigen sollte, die zeigt jetzt gerade die ganze Schweiz. Ist das so wie es sein sollte? Falls nicht, würde ich ein separates Issue dafür vorschlagen.

**Comment by larsUE** [comment]
Danke! :) Klappt bei mir auch. Versteh auch nicht ganz, was die Karte macht, sie hat bis jetzt aber auch noch nie funktioniert ;)
