### ISSUE TITLE
Newsletter speichern führt zu Problem

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#75]
Wenn ich ein Newsletter erstelle, dann erscheint beim Speichern die Seite "Auf unseren Servern ist ein Problem" aufgetreten. Hängt vermutlich nicht mit den Newsletter-Problemen (#42 , https://github.com/stadtluzern/decidim-ocl/issues/82) zusammen, sondern mit dem Upgrade #33 .

**Comment by carlobeltrame** [comment]
Etwas das damit verwandt sein könnte wurde [hier](https://github.com/decidim/decidim/pull/6681) schon gemeldet und für 0.24 und [für 0.23](https://github.com/decidim/decidim/pull/6752) gefixt. Vielleicht hat dieser Fix dein Problem auch erst verursacht. Ich sehe jedenfalls den Fehler im Log, und er tritt auf wenn Bilder im Formular nicht den Regeln ensprechen, die auf der Organisation und auf dem Formular definiert sind, oder wenn die Bilder nicht verarbeitet werden können. Ich weiss im Detail aber weder, welche Regeln, noch welche Verarbeitungen da greifen.

Um das korrekt zu reproduzieren und zu debuggen wäre es nützlich, wenn du uns das Bild (biene.png) senden kannst, das du im Formular eingefüllt hast. Im Log sehe ich folgende Parameter die du eingesendet hast:

```
Parameters: {
  "utf8"=>"✓",
  "authenticity_token"=>"<snip>",
  "newsletter"=>{
    "subject_de"=>"Nochmals Mail Test",
    "subject_en"=>"",
    "settings"=>{
      "introduction_de"=>"<p>Häts es Bild?</p>",
      "introduction_en"=>"",
      "cta_text_de"=>"Link",
      "cta_text_en"=>"",
      "cta_url_de"=>"http://ww.urban-equipe.ch ",
      "cta_url_en"=>"",
      "body_de"=>"<p>Vielleicht vielleicht</p>",
      "body_en"=>""
    },
    "images"=>{
      "main_image"=>#<ActionDispatch::Http::UploadedFile:0x000000000e300468 @tempfile=#<Tempfile:/tmp/RackMultipart20210309-1-rppl3r.png>, @original_filename="biene.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"newsletter[images][main_image]\"; filename=\"biene.png\"\r\nContent-Type: image/png\r\n">
    }
  },
  "newsletter_template_id"=>"image_text_cta"
}
```

**Comment by larsUE** [comment]
Stimmt! Ich habs mit einem kleineren Bild versucht (das Ursprungsbild war 2900*2100 gross). Mit kleinerem Bild klappts (ausser, dass dann die üblichen Formatierungsfehler auftreten). Schick dir das Bild per Mail, ist auch zu gross für Github😂
