### ISSUE TITLE
Drop shadow entfernen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#77]
Das haben wir bei der Quartieridee hinzugefügt, kann nun aber weg, an folgenden Stellen:

- [ ] Hervorgehobenes Inhaltsbanner
![Bildschirmfoto 2021-03-12 um 15 06 53](https://user-images.githubusercontent.com/60926257/110950801-970a9500-8344-11eb-80ff-f6b866235cc0.png)

- [ ] Prozessheader
![Bildschirmfoto 2021-03-12 um 15 07 29](https://user-images.githubusercontent.com/60926257/110950882-adb0ec00-8344-11eb-9204-aeb191d40fac.png)

**Comment by Kagemaru** [comment]
@larsUE Das Inhaltsbanner hat sich in der Zwischenzeit verändert. Kannst du schauen, ob es so gut ist?
Das andere ist umgesetzt und wird heute Abend noch auf INT landen.

**Comment by larsUE** [comment]
Es hat noch einen Schatten um die weisse Untertitel (auf beiden Seiten). Kannst du die auch noch entfernen?
