### ISSUE TITLE
Subnav Menü Beteiligungsprozesse

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#81]
Muss noch besprochen werden. Nicht aufwändige Optionen wären:

- Top Menü nochmals übernehmen: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/topnav/topnav.html
- Oder Left Nav vom Style horizontal denken: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/leftnav/leftnav.html

**Comment by larsUE** [comment]
Umsetzen wie Menü auf https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/header/header.html. Gemeint ist dieses Optionenauswahl-Menü, wird nicht auf der Seite per vorgestellt:

![Bildschirmfoto 2021-03-15 um 17 22 45](https://user-images.githubusercontent.com/60926257/111186194-13a2ab00-85b3-11eb-9a20-fb441f1a29b7.png)

**Comment by larsUE** [comment]
Gemäss Rücksprach mit Claudio und @carlobeltrame folgendermassen lösen: 
Bei erstmaligem öffnen eines Prozesses: Slider wird ganz angezeigt. Wenn dann aber ein Reiter im Subnav/Prozessmenü angeclickt wird, automatisch page runterscrollen, bis Sub-Nav direkt unter dem Main nav erscheint.

![Bildschirmfoto 2021-04-27 um 10 29 09](https://user-images.githubusercontent.com/60926257/116210896-9470cd00-a743-11eb-9194-335c7a091260.png)
Page View, wenn Prozess geöffnet wird


![Bildschirmfoto 2021-04-27 um 10 30 05](https://user-images.githubusercontent.com/60926257/116210937-a18dbc00-a743-11eb-84d8-e4ee28edd117.png)
Page View, wenn Reiter im Prozess angeclickt wird (Top Menü muss noch verschwinden, gemäss https://github.com/puzzle/decidim-zuerich/issues/60)

**Comment by larsUE** [comment]
Bei einer mehrstufigen Umfrage klappt dies noch nicht, sondern man landet immer wieder zuoberst. Das führt insbesondere bei längeren Umfragen zu mühsamen Scrollen. Bitte noch anpassen.

**Comment by Kagemaru** [comment]
Da dies mit Javascript gemacht wird und nicht mit vollen redirects, muss man dies allenfalls auch dort lösen. Eventuell kann sich @carlobeltrame dies noch anschauen.

**Comment by larsUE** [comment]
Zusätzlich zu den Umfragen funktioniert das Springen bei den Budgets noch nicht.

**Comment by larsUE** [comment]
Wird in #279  weiterbehandelt
