### ISSUE TITLE
Teilnahme ohne Login bzw. mit Gast-Login ermöglichen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#82]
Die Teilnahme ohne Account ist ein gewünschtes Feature der Stadt. Bin mir etwas unsicher, wie sinnvoll das ist, bzw. wie das überhaupt umgesetzt werden könnte und starte deshalb ein Brainstorming:

**Bestehende Rechte von Besuchenden ohne Account**

- Haben lesend Zugriff auf die Seite
- Können Umfragen ausfüllen, falls aktiviert.

**Umsetzungsmöglichkeiten**
- Sammlung von Gastlogins, die sich regelmässig löschen (und den Content dann einem "gelöschten Benutzer" zuweisen.
- Ideen, welche ohn Login erstelllt werden, werden automatisch einem Super-User "Stadtbevölkerung" zugewiesen.

**Pro's**

- Einfacher und schneller Zugang
- Vollständig anonyme Teilnahme möglich (wäre es jetzt auch z.B. mit einer 10 min Mail)

**Con's**

- Spambots können viel einfacher Content posten, da ganzes Mail-Bestätigung Vorgehen umgangen wird.
- Der häufig im Zusammenhang mit Decidim zitierte Spam- und Trollschutz Nr. 1, die soziale Verantwortung fehlt. Moderationsbedarf würde enorm steigen.
- Technische Umsetzungsschwierigkeiten: Doppelabstimmungen mit User-Account usw.
- Vernetzungsaspekt der User*innen fällt weg (da nicht zuweisbar).
- Hürden sind auch heute nicht hoch. Nur eine E-Mail-Adresse wird benötigt. Das ist auf vielen News-Portalen auch der Fall.
- Mein Konto haben wahrscheinlich doch schon viele Zürcher*innen
- Login muss nur 1mal vorgenommen werden und kann danach für alle Prozesse verwendet werden. Grosser Vorteil dieser Plattform -> Frage der Kommunikation
- Keine Kontaktmöglichkeit zu Inputgebenden (aber auch nicht immer benötigt).

**Persönliches Fazit**
Ich würde deshalb vorerst dazu tendieren, dass das nicht sinnvoll ist. Aus irgendwelchen Gründen verfügt Decidim (ziemlich sicher wohlüberlegt) nicht über dieses Feature. Eine anonyme Gast-Userschaft würde sehr viele Funktionen von Decidim überschreiben und den Community/Vernetzungsaspekt, mit dem wir etwa bei der Quartieridee sehr gute Erfahrungen gemacht haben, stark abschwächen.

**Alternativen**
- Registrierung weiter vereinfachen (indem zu Beginn z.B. nur Mail und Passwort benötigt wird), Pseudonym dann aber in den Kontoeinstellungen angepasst werden kann.
- Mehr Social Logins (nicht mein persönlicher Favorit, aber möglich)
- Email-Bestätigung deaktivieren (https://docs.decidim.org/en/admin/system/, zuunterst)
- Teilnahme ohne Registrierung wird nur für gewisse Funktionen ermöglicht (z.B. Kommentare)

@wernerliechtenhan @sabethtoedtli @bsantschi @carlobeltrame @maximilianstern: was denkt ihr?

**Comment by wernerliechtenhan** [comment]
Die Teilnahme als Gast wurde bei den Zebralog-Prozessen zur [Altersstrategie](https://www.stadt-zuerich.ch/gud/de/index/departement/strategie_politik/alterspolitik/mitwirkung/online-mitwirkung.html) (ich glaube leider nicht mehr einsehbar) und der VBZ ermöglicht (https://www.vbz-mitreden.ch/pikmi). 
Gemäss PL des Pikmi-Prozesses brauchte es keinen Benutzernamen, keine E-Mailadresse, keine Annahme von Nutzerbedingungen. "Wir wollen die Partizipation für alle so einfach zugänglich wie möglich machen. Bei Pikmi haben über 70% mit dem Handy mitgemacht. Wenn da noch eine Registration vorher wäre, wären bestimmt viele abgesprungen." Seitens der Dienstabteilungen der Stadt wurde die Möglichkeit eines Gast-Accounts ausdrücklich gewünscht. Die Zahl an Teilnehmenden an einem Prozess ist gemäss Zebralog deutlich höher, wenn auch ohne Registrierung mitgemacht werden kann. 
Wir haben diese Anforderungen deshalb im Projektteam beschlossen. Sie müsste eigentlich im jetzigen Auftrag enthalten sein.

**Comment by bsantschi** [comment]
Ich verstehe den Wunsch, möchte aber noch eine Ergänzung anbringen: Durch den grossen Eingriff würden wir uns vom Original weit entfernen. Nebst dem einmaligen Aufwand für den Umbau würde dadurch der Lifecycle (Upgrades auf neue Decidim Versionen, Wartung, Support) komplexer, aufwändiger und wiederkehrend teuerer.

**Comment by wernerliechtenhan** [comment]
Wir müssen einen Weg finden. Wenn es bei der Umfrage möglich ist, sollte es auch bei Dialogen möglich sein. Aus sicht der VBZ beispielsweise wird das als zwingen erachtet: "Ich finde, es braucht zwingend eine Möglichkeit ohne Login. Sonst werden wir viele vergraulen…".

**Comment by larsUE** [comment]
Wir finden schon eine Lösung. :) Vorschlag: Wir müssen sehr klar definieren, was genau ohne Login erreicht werden darf (z.B. einen Vorschlag einreichen). @wernerliechtenhan : Die Erfahrung stammt aus Prozessen, wo hauptsächlich Inputs gesammelt wurden, darüber auf der Plattform aber keine grosse Diskussion (z.B. in den Kommentaren) stattfand, bzw. der*die Autor*in auch nicht nachträglich kontaktiert werden musste (also unilaterale Partizipation), richtig? Ab einer gewissen Stufe der Partizipation muss eine Registration incentiviert/zwingend erforderlich sein, weil sonst decidim schlichtweg nicht funktioniert. 

**Aktuelle relevante Diskussionen zu diesem Thema auf Decidim**
Vorschläge ohne Registrierung: https://meta.decidim.org/processes/roadmap/f/122/proposals/15752?commentId=23200
Teilnahme an Veranstaltungen ohne Registrierung: https://meta.decidim.org/processes/roadmap/f/122/proposals/15114
Veranstaltungen erstellen ohne Registrierung: https://meta.decidim.org/processes/roadmap/f/122/proposals/15114
Abstimmung ohne Registrierung: https://github.com/decidim/decidim/issues/5438
Kommentare ohne Registrierung: keine Diskussion gefunden.

**Vorgehensvorschlag**
Für mich am einfachsten erscheint ein Feature zu bauen, bei dem im Login-Dialog ein "Anonym teilnehmen" Button erscheint. Wird dieser angewählt, so wird automatisch ein unique "anonymous-User_1223" mit generic Passwort (z.B. "Decidim1234" erstellt, welcher gewisse Rechte hat (z.B. Proposals einreichen). Möchte der anonymous_user dann aber weitere Dinge auf der Plattform machen (z.B. kommentieren oder abstimmen) wird er aufgefordert, dass er sein Account personalisieren muss, d.h. Namen und Passwort ändern und eine Mail-Adresse angeben.

**Vorteile**
- Flexibilität, User kann sein Account während der Session in ein normales Account umwandeln
- Prozessadministratoren haben Handlungsspielraum, indem sie auf das anonyme Account zugreifen können (und z.B. Trolling, Werbung direkt über das User-Account löschen können)
- Könnte ein paar Wünsche auf Meta-Decidim lösen
- Klare incentive und Aufforderung zur Umwandlung des Accounts (kann auch gut erklärt werden)
- Keine Anpassung an den Modulen benötigt (es sei denn, dieses Feature sollte (de)aktivierbar gemacht werden.
- Funktionsweise von decidim bleibt grösstenteils erhalten

**Nachteile**
- Neue Benutzerrolle mit bestimmten Rechten muss erstellt werden.
- Hoher Aufwand, dies bei decidim-Updates einfliessen zu lassen, es sei denn, dieses Feature schafft es in den Core (schätze die Chancen als realistisch ein).
- Doch etwas komplexer in der Realisierung.

**Comment by wernerliechtenhan** [comment]
> Ab einer gewissen Stufe der Partizipation muss eine Registration incentiviert/zwingend erforderlich sein... 
Finde ich gut! Einfaches Beiträge setzen ist möglich, für Kommentare, liken, abstimmen braucht es die Registrierung. 
 
> Für mich am einfachsten erscheint ein Feature zu bauen, bei dem im Login-Dialog ein "Anonym teilnehmen" Button erscheint.
Ist es möglich den Button mit "als Gast teilnehmen" zu beschriften?

**Comment by carlobeltrame** [comment]
Dazu, ob dieses Feature es in den Core schafft, muss ich noch hinzufügen, dass das dann erst nach einem Release von decidim und Update auf unserer Seite so "offiziell" eingebaut sein wird. Releases finden alle paar Monate statt, aktuell sind wir auf 0.23, Beta-Versionen von 0.24 sind verfügbar, und bis das in den Core eingebaut ist wird es frühestens 0.25 oder 0.26. Falls wir das Feature schon vorher einsetzen wollen, müssen wir es zuerst bei uns "einpatchen", bei jedem Update wieder neu komplett durchtesten und flicken, und schliesslich wieder ausbauen wenn der offizielle Support dafür landet.

Eine Alternative wäre, das in ein eigenes Modul zu packen, aber ich bin nicht sicher, ob das Modul-System von Decidim derart grundlegende Eingriffe ermöglicht.

**Comment by larsUE** [comment]
Jup, das werden wir wohl so machen müssen. @carlobeltrame: Was hältst du grundsätzlich vom Vorgehensvorschlag? Würde der im Grundsatz funktionieren oder hättest du eine Idee, wie das einfacher umgesetzt werden könnte?

**Comment by carlobeltrame** [comment]
Ich finde die Idee grundsätzlich gut. Statt ein generisches Passwort würde ich dem User kein Passwort (oder ein zufälliges) vergeben, sodass niemand sich später als all die Gast-User wieder einloggen und unter fremdem Namen Aussagen machen kann.

**Comment by larsUE** [comment]
Update: hier wird das Projekt auch auf Meta Decidim besprochen. Scheint vielerorts auf Interesse zu stossen: https://meta.decidim.org/processes/roadmap/f/122/proposals/15752?locale=en

**Comment by larsUE** [comment]
Ist den schon Weihnachten? 

https://github.com/PopulateTools/decidim-module-anonymous_proposals

@Kagemaru kannst du das kurz installieren?

**Comment by carlobeltrame** [comment]
Wow, sieht super aus. Habs kurz lokal bei mir installiert, scheint genau das abzudecken was hier gewünscht ist.

Leider wehrt es sich noch dagegen, auf der Integrationsumgebung installiert zu werden. @Kagemaru siehe letzte Builds auf Appuio. Ich habe auch schon das Base Image neu gebaut, hat nichts geändert. Die Datei `/app/overrides/decidim/proposals/proposals/_wizard_header/contextual_info.html.erb.deface` wird nicht gefunden, obwohl sie im GitHub Repository des Moduls drin ist.

Zur Referenz für die Installation auf Produktion: Es ist noch ein einmaliger Zusatzschritt notwendig, damit man mit anonymen Vorschlägen loslegen kann. Folgender Befehl muss in einem rails- oder worker-Container abgesetzt werden:
```
rake decidim_anonymous_proposals:generate_anonymous_group[Anonym,Anonym,anonym@mitwirken.zuerich.ch]
```

**Comment by carlobeltrame** [comment]
Habs hingekriegt, war ein sehr seltsamer [Konflikt mit dem Term Customizer](https://github.com/mainio/decidim-module-term_customizer/issues/65). Das Modul ist jetzt auf der Integration verfügbar.

Ich empfehle, es auf englisch auszuprobieren, da die angezeigten Warnungs-Texte bisher nur auf englisch verfügbar sind. So könnt ihr diese dann korrekt übersetzen mit dem Term Customizer.

**Comment by larsUE** [comment]
Super, danke fürs umsetzen! Klappt auch bei mir wunderbar! Seh  ich das  richtig, dass im Moment alle Proposals ohne Login  eingereicht werden können? Sprich, das kann gar nicht eingestellt werden?

**Comment by carlobeltrame** [comment]
Ja, soweit ich das sehe macht das Modul das so. Es ist ja noch sehr neu. Einzig auf einer Multitenant-Instanz könnte man es pro Tenant einrichten.

**Comment by larsUE** [comment]
Ok. Dann würde ich sagen, wir lassen das mal so & schauen, ob das Modul noch Update erfährt. Sonst müssten wir dann das  Vorschlagsmodul klonen: einmal mit und einmal ohne anonymer Teilnahme.

**Comment by carlobeltrame** [comment]
Oder selber Erweiterungen am Anonym-Modul implementieren. Der Release-Zyklus ist dort nicht an denjenigen von decidim gebunden. Wenn unsere Änderungen also dort akzeptiert würden könnten wir sie praktisch sofort ausrollen.

**Comment by bsantschi** [comment]
Hinweis: Auf PROD anonyme Gruppe mit rake Befehl erstellen.

**Comment by larsUE** [comment]
@Kagemaru ist das zur Zeit in der richtigen Spalte (Deployed on Prod)? Ich kann jetzt zwar als anonymer User Ideen auf der Prod eingeben, allerdings kann ich im Backend noch nicht einstellen, ob ich die anonyme Teilnahmen möchte oder nicht.

**Comment by Kagemaru** [comment]
@larsUE Sorry, es ist mir aus Versehen verrutscht.

**Comment by Kagemaru** [comment]
@larsUE Nun ist es auf der INT Umgebung testbar.

**Comment by larsUE** [comment]
Funktioniert wunderbar! Allerdings ist mir jetzt #121 aufgefallen.
