### ISSUE TITLE
Header-Banner übernehmen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#83]
Absolut CI/CD prio, da Unique Identifier der städtischen Websites. Vorschlag: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/header/header.html -> Option "Header with Logo (Two Lines) übernehmen, allerdings hat unser Logo nur one line.

**Comment by larsUE** [comment]
https://www.stadt-zuerich.ch/portal/de/index.html

**Comment by carlobeltrame** [comment]
Habe das mal so ungefähr umgesetzt auf Integration, kannst du mal testen und mir noch rückmelden wo wir noch verfeinern wollen?

**Comment by larsUE** [comment]
Wow! Mega cool :) mir fällt nur gerade auf, dass auf den städtischen Seiten das Top-Menü (mit Suchfeld, und Profil) "weggescrollt", sobald unterhalb des blauenweissen Logobanners gescrollt wird. Falls das einfach umsetzbar ist, gerne noch machen & ansonsten die anderen CI/CD Sachen zuerst machen.

Version INTEG:
![Decidim](https://user-images.githubusercontent.com/60926257/113898575-49127100-97cc-11eb-95ef-b8d7e7c863d8.gif)

Version Stadt:
![Stadt](https://user-images.githubusercontent.com/60926257/113898621-53346f80-97cc-11eb-930c-a1203dfff056.gif)

**Comment by carlobeltrame** [comment]
Ja, das habe ich mal noch weggelassen, weil es JavaScript verlangt, und weil ich nicht gerade auswendig wusste wie man das implementiert (vor allem beim Hochscrollen verhält es sich noch etwas anders). Ich mach mich dann noch da dran wenn das restliche wichtige CI/CD Zeugs erledigt ist.

**Comment by larsUE** [comment]
Wäre es hier noch möglich, das logo linksbündig auf der Höhe des Inhalts zu platzieren? Siehe Gifs oben: Damit Logo, Menü und Page-Inhalt alle auf der gleichen Linie sind.

**Comment by larsUE** [comment]
Falls es einfacher i
st (und eigentlich wäre das sogar besser):
Den gesamten Inhaltsabstand nach links auf Logohöhe verschieben (statt logo dem Inhalt anzupassen):
<img width="1260" alt="Bildschirmfoto 2021-04-12 um 13 24 20" src="https://user-images.githubusercontent.com/60926257/114387144-652e5d80-9b92-11eb-8fc5-4752699fd964.png">
städtische Website oben, decidim unten

**Comment by carlobeltrame** [comment]
Es wäre ungefähr gleich einfach, aber ein Stück riskanter, den gesamten decidim-Inhalt breiter zu machen, statt nur den "custom" Stadt-Zürich-Header schmaler.

**Comment by larsUE** [comment]
Ich würds mal ausprobieren. Was könnte schiefgehen? Dass sich nachher Elemente ungewünscht anordnen?

**Comment by carlobeltrame** [comment]
Ja, oder dass ich nicht alle Orte erwische wo ich es breiter machen müsste (wenns irgendwo von Hand ausprogrammiert ist oder in Zukunft dazukommt), oder falls irgendwo solche Spalten verschachtelt eingesetzt werden.
Aber ich machs mal und deploye dann gleich auf Produktion, damit du dort durch die wirklich eingerichteten Inhalte durchklicken kannst, okay?

**Comment by larsUE** [comment]
Nach Rücksprache mit Claudio Java-Script Lösung von oben nun implementieren.

**Comment by carlobeltrame** [comment]
Habe eine gute Lösung fürs Scrollen gefunden. Testbar auf Integration.

**Comment by larsUE** [comment]
Perfekt, wie gewünscht. Kann ausgerollt werden.
