### ISSUE TITLE
Titleimage anpasse

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#84]
Gemäss: https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/pagetitlemicrosite/pagetitlemicrosite.html, default Version
Bestehender Decidim Text wäre dann rechts mit Call to action button

**Comment by larsUE** [comment]
Besser (und vielleicht einfacher umzusetzen): 
https://dece.stadt-zuerich.ch/refpage/artifact/v8.6.6/modules/stageimage/stageimage.html im Style vom Carousel Slide default.

**Comment by larsUE** [comment]
Sehr coole Anpassung! :)  Aber eigentlich habe ich das Hauptbild auf der Startseite gemeint. Sorry, das hatte ich nicht klar genug beschrieben. Das wäre super, wenn wir da bis morgen noch hätten. Und die bissherige änderung bei den Prozessen lassen wir, die sieht nämlich super aus!

**Comment by larsUE** [comment]
Ich habe soeben noch die Rückmeldung erhalten, dass mit den neuen Banner-Bildern man fast von zu viel blau erschlagen wird & stimme dem eigentlich zu. Könntest du die Backgroundfarbe de Banners auf der Startseite auf die Farbe "Hervorheben" und die des Banners der Prozesse auf die Farbe "Hervorheben, Alternative" ändern (Siehe Bild, stammt aus den Seiteneinstellungen) Dann kann ich es jeweils selbst anpassen.
<img width="1396" alt="Bildschirmfoto 2021-04-13 um 09 59 24" src="https://user-images.githubusercontent.com/60926257/114517749-ee02d300-9c3e-11eb-8983-1087feb6ad72.png">

**Comment by carlobeltrame** [comment]
Ok, kann ich machen. Passt denn das noch mit den CI/CD Vorgaben zusammen? Gut, notfalls kannst dus ja trotzdem wieder auf dasselbe Blau setzen.
Die Schriftfarbe darauf wird aber weiterhin weiss bleiben, also helle Farben werden nicht gut klappen.

**Comment by larsUE** [comment]
Super danke! Ja das passt gut. Die Stadt verwendet unterschiedliche Farben z.B. auch auf der [Startseite](https://www.stadt-zuerich.ch/portal/de/index.html) und ich habe die Farben jetzt mal aus ihrer Styleguide übernommen.
