### ISSUE TITLE
INTEG verschickt keine Mails zum Datenexport

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#88]
Wenn ich im INT backend Daten exportieren (z.B. beim Term customizer) möchte, dann kriege ich keine Mails. Wäre wichtig zu flicke, sonst muss ich alle Terrm Customizeer Sachen nochmals neu starten.

**Comment by carlobeltrame** [comment]
Das wurde wohl durch den Umzug der Integrationsumgebung auf Appuio verursacht. @Kagemaru hier müsste man wohl in der Config die Mailer-Einstellungen anpassen. Weisst du gerade ob es auch ein ähnliches Mail Relay in Appuio gibt wie wir es auf dem Puzzle-Openshift hatten?

**Comment by carlobeltrame** [comment]
@larsUE Habe das mal versuchsweise behoben, kannst du testen ob es jetzt funktioniert?

**Comment by larsUE** [comment]
Klappt wieder, danke!
