### ISSUE TITLE
Term Customizer Modul funktioniert nicht

### ISSUE THREAD

**Issue by carlobeltrame** [puzzle/decidim-zuerich#9]
Beim Term Customizer bekomme ich Fehler, wenn ich ein neues Set anlegen will:
![image001](https://user-images.githubusercontent.com/7566995/92598802-9d428a80-f2a9-11ea-971b-7edade85eb24.jpg)

Egal was ich für einen Namen wähle, auch "test" akzeptiert das Modul nicht.

Mache ich dann einen 2. Versuch kommt ein 400er:
![image002](https://user-images.githubusercontent.com/7566995/92598806-9f0c4e00-f2a9-11ea-9269-c3b030396653.jpg)

Auch Egal ob ich eine Constraint definiere oder nicht.

Sollte ja auch ohne constraint gehen gemäss Hinweis, damit ein Set auf alle Prozesse angewendet wird.

**Comment by TSydekum** [comment]
Fehler gefunden: Hatte englisch eingestellt und Lösung wollte aber einen Titel in deutsch (Primäre Sprache nehme ich an)
Weiter konnte ich nicht testen, da mir noch nicht klar ist wie ich an die Key Info komme, damit ich den richtigen Term erwische.
Habe es mit de.decidim.term_customizer.menu.term_customizer versucht, da dieser Key im UI als fehlend ausgegeben wird... Hat nichts bewirkt.. Über die html source finde ich nichts heraus. Any Tips?

**Comment by carlobeltrame** [comment]
Ich habs hingebracht mit `decidim.term_customizer.menu.term_customizer`, ohne das führende `de.` (der gleiche Translation Key gilt ja für alle Sprachen).
Danach musste ich aber den Begriff auf alle vier Sprachen übersetzen und noch auf der Translation Sets Seite Clear Cache anklicken. Dann hats endlich geklappt.

An die Keys kommt man heran, wenn man den "Add Multiple" Button verwendet und z.B "Vorschlag" zu tippen beginnt (falls das UI auf Deutsch eingestellt ist, bei Englisch stattdessen "Proposal" tippen). Dann kann man im Dropdown-Menü die anzupassenden Übersetzungen anklicken, und mit Add die entsprechenden Keys zur Liste hinzufügen lassen. Wenn man stattdessen im Suchfeld ENTER drückt, bekommt man eine JSON-Liste mit allen Suchresultaten, was für End-User wohl nicht wirklich geeignet ist.
