### ISSUE TITLE
Vorschläge-Forms anpassbar machen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#91]
Könnte für den Klimabudget-Prozess sehr wichtig sein. Folgende Änderung im Auge behalten:
https://github.com/Platoniq/decidim-indices/issues/18

**Comment by larsUE** [comment]
https://github.com/Platoniq/decidim-module-decidim_awesome/pull/74

**Comment by larsUE** [comment]
To-Do: Abklären inwiefern Lösung von Decidim-Awesome bereits übernommen werden konnte.

**Comment by larsUE** [comment]
To-Do: Die decidim-awesome Lösung zum Testen auf die Integration übernehmen.

**Comment by carlobeltrame** [comment]
Habe auf Integration deployed. @larsUE Bitte testen und melden falls ich das wieder rückgängig machen soll. @Kagemaru In der Zwischenzeit können wir auch nicht einfach auf Produktion deployen, wir müssen diesen Change immer zuerst wieder rausnehmen.

**Comment by larsUE** [comment]
Yeaaah! Funktioniert auf dem ersten Blick bereits sehr gut. Einige Bugs sind mir auch bereits aufgefallen, ich ergänze hier laufend:

- [ ] Umlaute werden im Text als Eingabe nicht akzeptiert und in Codes umgewandelt (z.B. "&#xE4;" = ä)
- [ ]
