### ISSUE TITLE
Private Process information entfernen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#92]
Auf privaten Prozessen steht zuunterst im Beschreibungstext "[gremium]: Dies ist eine privates Gremium". Da bei privaten Prozessen bereits oben eine Notifizierung erscheint mit dem selben Text und der Text den Lesefluss stört, bitte entfernen.

![Bildschirmfoto 2021-04-13 um 08 54 15](https://user-images.githubusercontent.com/60926257/114509487-d70bb300-9c35-11eb-870f-7bc504c96c7c.png)

**Comment by larsUE** [comment]
https://pitc-stzh-decidim-int.appuioapp.ch/assemblies/test

**Comment by carlobeltrame** [comment]
Du sprichst hier wiederholt von Prozessen, aber du meinst wohl nur Gremien / Assemblies / Organisationen oder?

**Comment by larsUE** [comment]
Yes, sorry. Hab gemerkt dass das nur bei den Gremien der Fall ist.
