### ISSUE TITLE
Reply-to Adresse ändern / Mailtag anpassen

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#96]
Können wir die reply-to Adresse auf mitwirken-kontakt@zuerich.ch anpassen?

**Comment by larsUE** [comment]
Zusätzlicher Wunsch von Werner: das Mailtag zu "Mitwirken an Zürichs Zukunft " ändern

**Comment by carlobeltrame** [comment]
Das "Mailtag" kann man im System-Dashboard ändern, bei SMTP Einstellungen im Feld "Beschreibung". Habe das gleich angepasst.

**Comment by carlobeltrame** [comment]
Es gab noch einen Bug in decidim, der das Setzen der Reply-To-Adresse verhindert hat. Ich habe den [Fix](https://github.com/decidim/decidim/pull/7641), der erst vor 22 Tagen gemerged wurde, bei uns vorgeholt. Ist auf Integration deployed.

**Comment by larsUE** [comment]
Mailtag sehe ich auf der Prod, Reply-to auf der Int. Nach einem Deployment also alles gut! :)
